### ISSUE TITLE
Model instances without primary key value are unhashable

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#1010]
#### Brief summary of issue / Description of requested feature:
When a non-persistent script is interrupted by a server reload, the script cannot be reinstantiated.

#### Steps to reproduce the issue

I'm on a nearly-stock install. There is no problem until a server reload. Upon reload, trying to instantiate the same script fails.

Basically CmdAttack does some preliminary checks to make sure the target is a valid arg and is in the same room, then instantiates an AttackScript on that user.

Here are the properties of the script. Obviously there are some implementation flaws but I was working on it:

    class AttackScript(Script):
    
        key = "AttackScript"
        desc = "Combat between two characters."
        persistent = False

        def at_script_creation(self):
            self.interval = 4
            self.repeats = 0

        def at_repeat(self):
            # Attack target 
            self.obj.attack(self.obj.ndb.current_target)

#### Error output / Expected result of feature
The first time I use CmdAttack, the script executes, and the character goes into auto-attack mode.

If I do a reload, the script terminates as it should, but I cannot instantiate it again. Trying CmdAttack now yields:

> (EV) johnny@johnny-VirtualBox:~/workspace/fury$ 2016-07-22T02:06:29+0000 [AMPProtocol,0,127.0.0.1] [::] Traceback (most recent call last):
> 2016-07-22T02:06:29+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/home/johnny/workspace/evennia/evennia/commands/cmdhandler.py", line 464, in _run_command
> 2016-07-22T02:06:29+0000 [AMPProtocol,0,127.0.0.1] [::]     ret = yield cmd.func()
> 2016-07-22T02:06:29+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/home/johnny/workspace/fury/commands/command.py", line 115, in func
> 2016-07-22T02:06:29+0000 [AMPProtocol,0,127.0.0.1] [::]     self.caller.scripts.add("typeclasses.scripts.AttackScript")
> 2016-07-22T02:06:29+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/home/johnny/workspace/evennia/evennia/scripts/scripthandler.py", line 76, in add
> 2016-07-22T02:06:29+0000 [AMPProtocol,0,127.0.0.1] [::]     autostart=autostart)
> 2016-07-22T02:06:29+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/home/johnny/workspace/evennia/evennia/utils/create.py", line 204, in create_script
> 2016-07-22T02:06:29+0000 [AMPProtocol,0,127.0.0.1] [::]     new_script.save()
> 2016-07-22T02:06:29+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/home/johnny/workspace/evennia/evennia/utils/idmapper/models.py", line 397, in save
> 2016-07-22T02:06:29+0000 [AMPProtocol,0,127.0.0.1] [::]     _MONITORHANDLER.at_update(self, fieldname)
> 2016-07-22T02:06:29+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/home/johnny/workspace/evennia/evennia/scripts/monitorhandler.py", line 91, in at_update
> 2016-07-22T02:06:29+0000 [AMPProtocol,0,127.0.0.1] [::]     if obj in self.monitors and fieldname in self.monitors[obj]:
> 2016-07-22T02:06:29+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/home/johnny/workspace/EV/local/lib/python2.7/site-packages/django/db/models/base.py", line 492, in __hash__
> 2016-07-22T02:06:29+0000 [AMPProtocol,0,127.0.0.1] [::]     raise TypeError("Model instances without primary key value are unhashable")
> 2016-07-22T02:06:29+0000 [AMPProtocol,0,127.0.0.1] [::] TypeError: Model instances without primary key value are unhashable

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Latest revision. So far only deleting and re-migrating the DB is a workaround but obviously there are significant downsides to that.

**Comment by strikaco** [comment]
I'm inclined to think there was a stray character or some bizarre Django quirk somewhere else in my code. I started over from scratch and manually re-coded my classes and cannot seem to replicate this issue anymore.
