### ISSUE TITLE
Bug: an untrapped error

### ISSUE THREAD

**Issue by passos** [evennia/evennia#1032]
#### Brief summary of issue / Description of requested feature:
an untrapped error occurred when input command "delcom"

#### Steps to reproduce the issue / Reasons for adding feature:

1. setup a new instance of evennia
2. build tutorial world and "begin"
3. input command "delcom wooden sign"

#### Error output / Expected result of feature
webclient output:
TypeError: 'NoneType' object has no attribute '__getitem__'
An untrapped error occurred. Please file a bug report detailing the steps to reproduce.
(Traceback was logged 2016-09-01 15:11:56-0000).

backend log:
$ 2016-09-01T15:14:03+0000 [AMPProtocol,0,127.0.0.1] [::] Traceback (most recent call last):
2016-09-01T15:14:03+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/Users/simon/workspace/hackday/evennia/evennia/commands/cmdhandler.py", line 464, in _run_command
2016-09-01T15:14:03+0000 [AMPProtocol,0,127.0.0.1] [::]     ret = yield cmd.func()
2016-09-01T15:14:03+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/Users/simon/workspace/hackday/evennia/evennia/commands/default/comms.py", line 174, in func
2016-09-01T15:14:03+0000 [AMPProtocol,0,127.0.0.1] [::]     channame = caller.nicks.get(key=ostring, category="channel")
2016-09-01T15:14:03+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/Users/simon/workspace/hackday/evennia/evennia/typeclasses/attributes.py", line 685, in get
2016-09-01T15:14:03+0000 [AMPProtocol,0,127.0.0.1] [::]     return retval[3] if isinstance(retval, tuple) else [tup[3] for tup in make_iter(retval)]
2016-09-01T15:14:03+0000 [AMPProtocol,0,127.0.0.1] [::] TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by Griatch** [comment]
No reason to make the tutorial world, the error popped up just by `delcom blalala´ (with an invalid argument). Fixed now, thanks for reporting!
