### ISSUE TITLE
@chardelete

### ISSUE THREAD

**Issue by aceamro** [evennia/evennia#1035]
#### Brief summary of issue / Description of requested feature:
The problem occurs when you delete a character.

I'm sorry, because lack explanation.
I do not have a fluent english skill, I'm korean
But, I really like evennia and respect developers of the evennia. :)

#### Steps to reproduce the issue / Reasons for adding feature:

1. @chardelete saby(connected username)
2. This will permanently destroy 'saby'. This cannot be undone. Continue yes/[no]? 
3. yes

#### Error output / Expected result of feature
@chardelete saby
This will permanently destroy 'saby'. This cannot be undone. Continue yes/[no]?
yes
TypeError: 'NoneType' object is not callable
An untrapped error occurred. Please file a bug report detailing the steps to reproduce.
(Traceback was logged 2016-09-03 11:51:21-0000).
ErrorReported
A command handler bug occurred. Please notify staff - they should
likely file a bug report with the Evennia project.
(Traceback was logged 2016-09-03 11:51:21-0000).
l
TypeError: 'NoneType' object is not callable
An untrapped error occurred. Please file a bug report detailing the steps to reproduce.
(Traceback was logged 2016-09-03 11:51:22-0000).

**Comment by Griatch** [comment]
@aceamro 

Please include the full traceback referenced here ("Traceback was logged 2016-09-03 11:51:22-0000"). You can find it in your server log or on the command line. That shows better what the actual error is.

**Comment by aceamro** [comment]
I could not find a log tried again.

2016-09-03T12:25:57+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/Users/amro/PycharmProjects/evenv/evennia/evennia/commands/cmdhandler.py", line 464, in _run_command
2016-09-03T12:25:57+0000 [AMPProtocol,0,127.0.0.1] [::]     ret = yield cmd.func()
2016-09-03T12:25:57+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/Users/amro/PycharmProjects/evenv/evennia/evennia/utils/evmenu.py", line 797, in func
2016-09-03T12:25:57+0000 [AMPProtocol,0,127.0.0.1] [::]     ok = not callback(caller, prompt, result)
2016-09-03T12:25:57+0000 [AMPProtocol,0,127.0.0.1] [::] TypeError: 'NoneType' object is not callable
2016-09-03T12:25:57+0000 [AMPProtocol,0,127.0.0.1] [::] Traceback (most recent call last):
2016-09-03T12:25:57+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/Users/amro/PycharmProjects/evenv/evennia/evennia/commands/cmdhandler.py", line 597, in cmdhandler
2016-09-03T12:25:57+0000 [AMPProtocol,0,127.0.0.1] [::]     ret = yield _run_command(syscmd, syscmd.key, sysarg)
2016-09-03T12:25:57+0000 [AMPProtocol,0,127.0.0.1] [::] ErrorReported

**Comment by aceamro** [comment]
Wow!!! incredibly fast... Thank you
