### ISSUE TITLE
AttributeError: 'Player' object has no attribute 'backend'

### ISSUE THREAD

**Issue by BlauFeuer** [evennia/evennia#1037]
#### Brief summary of issue / Description of requested feature:

Traceback occurs from time to time, and others have mentioned it occurring.

#### Steps to reproduce the issue / Reasons for adding feature:

Currently I do not know how to reproduce this.  It involves accessing the web interface in some way.

1.
2. 
3. 

#### Error output / Expected result of feature
```text
2016-09-04 17:29:08+0000 [HTTPChannelWithXForwardedFor,99,127.0.0.1] [::] Traceback (most recent call last):
2016-09-04 17:29:08+0000 [HTTPChannelWithXForwardedFor,99,127.0.0.1] [::]   File "/home/evennia/evennia/evennia/web/website/views.py", line 43, in _shared_login
2016-09-04 17:29:08+0000 [HTTPChannelWithXForwardedFor,99,127.0.0.1] [::]     login(request, player)
2016-09-04 17:29:08+0000 [HTTPChannelWithXForwardedFor,99,127.0.0.1] [::]   File "/home/evennia/pyenv/local/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 112, in login
2016-09-04 17:29:08+0000 [HTTPChannelWithXForwardedFor,99,127.0.0.1] [::]     request.session[BACKEND_SESSION_KEY] = user.backend
2016-09-04 17:29:08+0000 [HTTPChannelWithXForwardedFor,99,127.0.0.1] [::] AttributeError: 'Player' object has no attribute 'backend'
```

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Latest revision evennia repo, main branch.  Seen while using Ubuntu Linux OS.

**Comment by Griatch** [comment]
The error comes from the part of the engine handling automatic login between the website and webclient.

**Comment by Griatch** [comment]
Figured out how to reproduce this, writing it down so i don't forget:

1. Log out from the website
2. Log out from the webclient, if necessary
3. Log back in with the webclient (not the website)
4. `@reload` the server
5. Reload the webclient page so that you will auto-connect
6. Traceback now appears 

The cause of this is that the login mechanics that we borrow from Django requires that authenticate() is called on the Player object before calling login on it. The call of authenticate() apparently sets some properties on the Player, including the fabled `.backend` property. When auto-connecting with an existing website login this is not an issue (the login to the website uses authenticate on its own, presumably), and Evennia calls authenticate() when you first login so you are fine. Subsequent auto-logins *will not* call authenticate - since the Player is already authenticated - but since since the Player remains in the idmapper, subsequent connections will still work. But reloading the server will clear the cache and then the Player object misses that `.backend` property.
