### ISSUE TITLE
Bug: Creating character and immediately quitting causes traceback

### ISSUE THREAD

**Issue by aceamro** [evennia/evennia#1041]
#### Brief summary of issue / Description of requested feature:
An error occurs, when with the create character and Immediately quit

#### Steps to reproduce the issue / Reasons for adding feature:

1.  Edit setting.py : add MULTISESSION_MODE = 2
2. create new character (Do not @ic character) -> quit -> reconnect -> AssertionError

    AssertionError: Attribute object can't be deleted because its id attribute is set to None.
    An untrapped error occurred. Please file a bug report detailing the steps to reproduce.
    (Traceback was logged 2016-09-06 01:10:12+0900).

#### Error output / Expected result of feature

2016-09-06T01:10:12+0900 [AMPProtocol,0,127.0.0.1] [::] Traceback (most recent call last):
2016-09-06T01:10:12+0900 [AMPProtocol,0,127.0.0.1] [::]   File "/Users/amro/PycharmProjects/evenv/evennia/evennia/commands/cmdhandler.py", line 464, in _run_command
2016-09-06T01:10:12+0900 [AMPProtocol,0,127.0.0.1] [::]     ret = yield cmd.func()
2016-09-06T01:10:12+0900 [AMPProtocol,0,127.0.0.1] [::]   File "/Users/amro/PycharmProjects/evenv/evennia/evennia/commands/default/unloggedin.py", line 241, in func
2016-09-06T01:10:12+0900 [AMPProtocol,0,127.0.0.1] [::]     session.sessionhandler.login(session, player)
2016-09-06T01:10:12+0900 [AMPProtocol,0,127.0.0.1] [::]   File "/Users/amro/PycharmProjects/evenv/evennia/evennia/server/sessionhandler.py", line 403, in login
2016-09-06T01:10:12+0900 [AMPProtocol,0,127.0.0.1] [::]     del player.db.FIRST_LOGIN
2016-09-06T01:10:12+0900 [AMPProtocol,0,127.0.0.1] [::]   File "/Users/amro/PycharmProjects/evenv/evennia/evennia/typeclasses/models.py", line 133, in __delattr__
2016-09-06T01:10:12+0900 [AMPProtocol,0,127.0.0.1] [::]     _GA(self, _GA(self, 'name')).remove(attrname)
2016-09-06T01:10:12+0900 [AMPProtocol,0,127.0.0.1] [::]   File "/Users/amro/PycharmProjects/evenv/evennia/evennia/typeclasses/attributes.py", line 575, in remove
2016-09-06T01:10:12+0900 [AMPProtocol,0,127.0.0.1] [::]     attr_obj.delete()
2016-09-06T01:10:12+0900 [AMPProtocol,0,127.0.0.1] [::]   File "/Users/amro/PycharmProjects/evenv/evennia/evennia/utils/idmapper/models.py", line 351, in delete
2016-09-06T01:10:12+0900 [AMPProtocol,0,127.0.0.1] [::]     super(SharedMemoryModel, self).delete(*args, **kwargs)
2016-09-06T01:10:12+0900 [AMPProtocol,0,127.0.0.1] [::]   File "/Users/amro/PycharmProjects/evenv/lib/python2.7/site-packages/django/db/models/base.py", line 865, in delete
2016-09-06T01:10:12+0900 [AMPProtocol,0,127.0.0.1] [::]     (self._meta.object_name, self._meta.pk.attname)
2016-09-06T01:10:12+0900 [AMPProtocol,0,127.0.0.1] [::] AssertionError: Attribute object can't be deleted because its id attribute is set to None.

**Comment by Griatch** [comment]
This is confirmed but seems to be reproducible more generally than in `MULTISESSION_MODE=2`. See  duplicate issue #1049: 

> Confirmed with a test character. This appears to dump the player in OOC mode but from there on things work normally. Seems to also affect auto-login operations.
