### ISSUE TITLE
Error when logging in to demo (in some circumstances)

### ISSUE THREAD

**Issue by Griatch** [evennia/evennia#1049]
(forwarded from IRC user "Suterusu")

#### Brief summary of issue / Description of requested feature:

On login attempt char selection/application fails and traceback released. Can then `@ic` [login] to gain access to char.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Login to demo game (in some circumstances)

#### Error output / Expected result of feature

```
connected to horizondark.com.
Escape character is '^]'.
==============================================================
 Welcome to Evdemo, version 0.6.0 (rev 614a991)!

 If you have an existing account, connect to it by typing:
      connect <username> <password>
 If you need to create an account, type (without the <>'s):
      create <username> <password>

 If you have spaces in your username, enclose it in quotes.
 Enter help for more info. look will re-show this screen.
==============================================================
connect Eye+R [Redacted]
Traceback (most recent call last):
  File "/home/griatch/evennia/evennia/commands/cmdhandler.py", line 464, in _run_command
    ret = yield cmd.func()
  File "/home/griatch/evennia/evennia/commands/default/unloggedin.py", line 241, in func
    session.sessionhandler.login(session, player)
  File "/home/griatch/evennia/evennia/server/sessionhandler.py", line 403, in login
    del player.db.FIRST_LOGIN
  File "/home/griatch/evennia/evennia/typeclasses/models.py", line 133, in __delattr__
    _GA(self, _GA(self, 'name')).remove(attrname)
  File "/home/griatch/evennia/evennia/typeclasses/attributes.py", line 575, in remove
    attr_obj.delete()
  File "/home/griatch/evennia/evennia/utils/idmapper/models.py", line 351, in delete
    super(SharedMemoryModel, self).delete(*args, **kwargs)
  File "/home/griatch/vienv/lib/python2.7/site-packages/django/db/models/base.py", line 865, in delete
    (self._meta.object_name, self._meta.pk.attname)
AssertionError: Attribute object can't be deleted because its id attribute is set to None.

An untrapped error occurred.
(Traceback was logged 2016-09-07 21:32:53-0000).
l
You are out-of-character (OOC).
Use @ic to get back into the game.
```
```
connect tsunami REDACTED
Traceback (most recent call last):
  File "/home/griatch/evennia/evennia/commands/cmdhandler.py", line 464, in _run_command
    ret = yield cmd.func()
  File "/home/griatch/evennia/evennia/commands/default/unloggedin.py", line 241, in func
    session.sessionhandler.login(session, player)
  File "/home/griatch/evennia/evennia/server/sessionhandler.py", line 403, in login
    del player.db.FIRST_LOGIN
  File "/home/griatch/evennia/evennia/typeclasses/models.py", line 133, in __delattr__
    _GA(self, _GA(self, 'name')).remove(attrname)
  File "/home/griatch/evennia/evennia/typeclasses/attributes.py", line 575, in remove
    attr_obj.delete()
  File "/home/griatch/evennia/evennia/utils/idmapper/models.py", line 351, in delete
    super(SharedMemoryModel, self).delete(*args, **kwargs)
  File "/home/griatch/vienv/lib/python2.7/site-packages/django/db/models/base.py", line 865, in delete
    (self._meta.object_name, self._meta.pk.attname)
AssertionError: Attribute object can't be deleted because its id attribute is set to None.

An untrapped error occurred.
(Traceback was logged 2016-09-07 23:06:53-0000).
```

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

At a loose guess, I [Suterusu] 'd suggest it's attempting to process me with the sessionhandler.py, in login, and failing when hits `del player.db.FIRST_LOGIN` as this isn't actually my first login - and that's already been deleted. Unable to handle/unexpecting such an error(can't delete it, dipshit, it's not there) it throws an exception. Just a guess mind, not a particular educated one either.

Potentially caused by recycling charactor details in DB, of previously or inaccurately deleted charactors.

**Comment by Griatch** [comment]
Confirmed with a test character. This appears to dump the player in OOC mode but from there on things work normally. Seems to also affect auto-login operations.

**Comment by Griatch** [comment]
Closing as a duplicate of #1041.
.
Griatch
