### ISSUE TITLE
Fails to Launch.

### ISSUE THREAD

**Issue by justthedoctor** [evennia/evennia#1130]
#### Brief summary of issue
 The application does not start, it gives me some sort of error... 

#### Steps to reproduce the issue / Reasons for adding feature:

1.  evennia start

#### Error output / Expected result of feature

(vienv) jtdoc@vps:~/bwis$
Starting Evennia Server (output to stdout).

Starting Evennia Portal in Daemon mode (output to portal logfile).
Traceback (most recent call last):
  File "/home/jtdoc/vienv/bin/twistd", line 7, in <module>
    from twisted.scripts.twistd import run
  File "/home/jtdoc/vienv/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 13, in <module>
    from twisted.application import app
  File "/home/jtdoc/vienv/local/lib/python2.7/site-packages/twisted/application/app.py", line 17, in <module>
    from twisted import copyright, plugin, logger
  File "/home/jtdoc/vienv/local/lib/python2.7/site-packages/twisted/plugin.py", line 18, in <module>
    from zope.interface import Interface, providedBy
ImportError: No module named zope.interface
Traceback (most recent call last):
  File "/home/jtdoc/vienv/bin/twistd", line 7, in <module>
    from twisted.scripts.twistd import run
  File "/home/jtdoc/vienv/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 13, in <module>
    from twisted.application import app
  File "/home/jtdoc/vienv/local/lib/python2.7/site-packages/twisted/application/app.py", line 17, in <module>
    from twisted import copyright, plugin, logger
  File "/home/jtdoc/vienv/local/lib/python2.7/site-packages/twisted/plugin.py", line 18, in <module>
    from zope.interface import Interface, providedBy
ImportError: No module named zope.interface

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Evennia 0.6.0
OS: 
Linux vps 2.6.32-042stab116.1 #1 SMP Wed May 4 16:21:02 MSK 2016 x86_64 GNU/Linux
PRETTY_NAME="Debian GNU/Linux 7 (wheezy)"
NAME="Debian GNU/Linux"
VERSION_ID="7"
VERSION="7 (wheezy)"
ID=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support/"
BUG_REPORT_URL="http://bugs.debian.org/"

Followed the install guide to a T and this is where i ended up. dont know how to fix sorry if this is a repost of something solved previously...

**Comment by CloudKeeper1** [comment]
Some versions of Ubuntu 16 features an issue where you can't start the server but get an error saying "Twisted requires zope.interface 3.6.0 or later: no module named zope.interface.". This even though a much later version of zope.interface is clearly installed in the virtualenv (as verified with pip list). This appears to be due to a bug in the zope installer; it fails to install an empty __init__.py file. To fix this, issue the following command: touch pyenv/local/lib/python2.7/site-packages/zope/__init__.py. That creates the file and things should then work correctly.

As per: https://github.com/evennia/evennia/wiki/Getting-Started#linux-troubleshooting

**Comment by justthedoctor** [comment]
This is the in/output of doing what you recommended..

(vienv) jtdoc@vps:~/bwis$ touch pyenv/local/lib/python2.7/site-packages/zope/init.py
touch: cannot touch `pyenv/local/lib/python2.7/site-packages/zope/init.py': No such file or directory
(vienv) jtdoc@vps:~/bwis$ ev
eval     evennia
(vienv) jtdoc@vps:~/bwis$ ev
eval     evennia
(vienv) jtdoc@vps:~/bwis$ evennia start

0 static files copied to '/home/jtdoc/bwis/web/static', 72 unmodified.
(vienv) jtdoc@vps:~/bwis$
Starting Evennia Server (output to stdout).

Starting Evennia Portal in Daemon mode (output to portal logfile).
Traceback (most recent call last):
  File "/home/jtdoc/vienv/bin/twistd", line 7, in <module>
    from twisted.scripts.twistd import run
  File "/home/jtdoc/vienv/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 13, in <module>
    from twisted.application import app
  File "/home/jtdoc/vienv/local/lib/python2.7/site-packages/twisted/application/app.py", line 17, in <module>
    from twisted import copyright, plugin, logger
  File "/home/jtdoc/vienv/local/lib/python2.7/site-packages/twisted/plugin.py", line 18, in <module>
    from zope.interface import Interface, providedBy
ImportError: No module named zope.interface
Traceback (most recent call last):
  File "/home/jtdoc/vienv/bin/twistd", line 7, in <module>
    from twisted.scripts.twistd import run
  File "/home/jtdoc/vienv/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 13, in <module>
    from twisted.application import app
  File "/home/jtdoc/vienv/local/lib/python2.7/site-packages/twisted/application/app.py", line 17, in <module>
    from twisted import copyright, plugin, logger
  File "/home/jtdoc/vienv/local/lib/python2.7/site-packages/twisted/plugin.py", line 18, in <module>
    from zope.interface import Interface, providedBy
ImportError: No module named zope.interface

Instead of fighting this, can i ask what a perfect os would be to run?

**Comment by justthedoctor** [comment]
touch pyenv/local/lib/python2.7/site-packages/zope/init.py gives me touch: cannot touch `pyenv/local/lib/python2.7/site-packages/zope/init.py': No such file or directory
 rather then fight this anymore, what is the best Distro to use / version to make things work properly?

**Comment by Griatch** [comment]
Good this seems to have been resolved. To be clear, the markdown turns `__init__.py` into bold text unless putting it in verbatim. The command is `touch pyenv/local/lib/python2.7/site-packages/zope/__init__.py`.

**Comment by justthedoctor** [comment]
i did not figure out how to resolve the issue via the info i posted.. however i have some new idea's on how i could have.. i did  however resolve the issue after much struggle and fighting.. 

I Feel the issue was a lack of My mis-understanding and lack of reading the guide's given.. I'm sorry i did not read properly before posting.

**Comment by ryanaddams** [comment]
This was actually helpful, I had the same problem. I applied Griatch's solution and it worked.
