### ISSUE TITLE
CmdEvMenuNode missing session member.

### ISSUE THREAD

**Issue by Phayte** [evennia/evennia#1166]
#### Brief summary of issue / Description of requested feature:
After updating to the latest revision of the Evennia framework, I seem to be getting an error while trying to execute a "command" (aka CmdEvMenuNode). I've reverted back to a known working version and it appears to still occur. It seem as though the _menutree is somehow getting deleted.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Create simple command to call EvMenu and add to Default Cmd Set
```python
class CmdOOCLook(MuxPlayerLookCommand):
    key = "look"
    locks = "cmd:all()"
    help_category = "General"

    def func(self):
        EvMenu(
            self.session,
            menudata="menus.dummy",
            cmd_on_exit=None
        )
```
```python
class PlayerCmdSet(default_cmds.PlayerCmdSet):
    """
    This is the cmdset available to the Player at all times. It is
    combined with the `CharacterCmdSet` when the Player puppets a
    Character. It holds game-account-specific commands, channel
    commands, etc.
    """
    key = "DefaultPlayer"

    def at_cmdset_creation(self):
        super(PlayerCmdSet, self).at_cmdset_creation()
        self.add(CmdOOCLook())
```

2. Create sample Menu Nodes
```python
def start(caller):
    return "Test1", ({"desc":"node1","goto":"node2"},)
    
def node2(caller):
    return "Test2", ({"desc":"node2","goto":"node3"},)
```
3. Start Evennia, overriding the OOC log for the player should automatically bring up the menu. Just select node 1 option and error should appear.

#### Error output / Expected result of feature
```
________________________________

Test1
________________________________

1: node1  
Traceback (most recent call last):
  File "/home/ubuntu/workspace/evennia/evennia/commands/cmdhandler.py", line 493, in _run_command
    ret = yield cmd.func()
  File "/home/ubuntu/workspace/evennia/evennia/utils/evmenu.py", line 245, in func
    caller.ndb._menutree._session = self.session
AttributeError: 'NoneType' object has no attribute '_session'

An untrapped error occurred.
(Traceback was logged 2017-01-16 07:08:37-0000).
Traceback (most recent call last):
  File "/home/ubuntu/workspace/evennia/evennia/commands/cmdhandler.py", line 622, in cmdhandler
    ret = yield _run_command(syscmd, syscmd.key, sysarg)
ErrorReported

A command handler bug occurred. If this is not due to a local change,
please file a bug report with the Evennia project, including the
traceback and steps to reproduce.
(Traceback was logged 2017-01-16 07:08:37-0000).
```

**Comment by Phayte** [comment]
Originally thought this might've been an issue with Cloud9's environment not working with websockets. I tried on my locals window machine with the same test case and get the same error. In addition, I tried to do a clean mygame and still get the same error (though the Evennia clone was just a pull from upstream, not a clean clone).

**Comment by Phayte** [comment]
Nevermind, this likely a mistake on my part. I converted a command from player to session but didn't make all the changes necessary. Will reopen if I still have problems later.
