### ISSUE TITLE
Out-of-sync sessions produced max depth recursion error

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#1181]
#### Brief summary of issue / Description of requested feature:
A player seemed to have a stale session issue with her character. When trying to move, she produced the following traceback:
```
2017-01-29T05:40:13-0500 [AMPProtocol,0,127.0.0.1] [::] Traceback (most recent call last):
2017-01-29T05:40:13-0500 [AMPProtocol,0,127.0.0.1] [::]   File "/home/tehom/arx/evennia/evennia/objects/objects.py", line 688, in move_to
2017-01-29T05:40:13-0500 [AMPProtocol,0,127.0.0.1] [::]     self.announce_move_from(destination)
2017-01-29T05:40:13-0500 [AMPProtocol,0,127.0.0.1] [::]   File "/home/tehom/arx/arx/typeclasses/characters.py", line 737, in announce_move_from
2017-01-29T05:40:13-0500 [AMPProtocol,0,127.0.0.1] [::]     destination.get_display_name(obj)))
2017-01-29T05:40:13-0500 [AMPProtocol,0,127.0.0.1] [::]   File "/home/tehom/arx/arx/typeclasses/mixins.py", line 546, in msg
2017-01-29T05:40:13-0500 [AMPProtocol,0,127.0.0.1] [::]     super(MsgMixins, self).msg(text, from_obj, session, options, **kwargs)
2017-01-29T05:40:13-0500 [AMPProtocol,0,127.0.0.1] [::]   File "/home/tehom/arx/evennia/evennia/objects/objects.py", line 526, in msg
2017-01-29T05:40:13-0500 [AMPProtocol,0,127.0.0.1] [::]     sessions = make_iter(session) if session else self.sessions.all()
2017-01-29T05:40:13-0500 [AMPProtocol,0,127.0.0.1] [::]   File "/home/tehom/arx/evennia/evennia/objects/objects.py", line 101, in all
2017-01-29T05:40:13-0500 [AMPProtocol,0,127.0.0.1] [::]     return self.get()
2017-01-29T05:40:13-0500 [AMPProtocol,0,127.0.0.1] [::]   File "/home/tehom/arx/evennia/evennia/objects/objects.py", line 90, in get
2017-01-29T05:40:13-0500 [AMPProtocol,0,127.0.0.1] [::]     return self.get(sessid=sessid)
2017-01-29T05:40:13-0500 [AMPProtocol,0,127.0.0.1] [::]   File "/home/tehom/arx/evennia/evennia/objects/objects.py", line 90, in get
2017-01-29T05:40:13-0500 [AMPProtocol,0,127.0.0.1] [::]     return self.get(sessid=sessid)
2017-01-29T05:40:13-0500 [AMPProtocol,0,127.0.0.1] [::]   File "/home/tehom/arx/evennia/evennia/objects/objects.py", line 90, in get
2017-01-29T05:40:13-0500 [AMPProtocol,0,127.0.0.1] [::]     return self.get(sessid=sessid)
2017-01-29T05:40:13-0500 [AMPProtocol,0,127.0.0.1] [::]   File "/home/tehom/arx/evennia/evennia/objects/objects.py", line 90, in get
2017-01-29T05:40:13-0500 [AMPProtocol,0,127.0.0.1] [::]     return self.get(sessid=sessid)
... (rest snipped)
```
So for some reason, `_recache` didn't resolve the `None in sessions` check, resulting in exceeding max recursion depth.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Probably a result of my fiddling with the server lag issue, making things temporarily unresponsive earlier for her. I had since reverted back to the older commit that doesn't lag, but maybe she got out of sync that way.

#### Error output / Expected result of feature
Infinite recursion error when `_recache` fails to resolve the `None in sessions` condition.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
I apologize for not thinking to check what her `.db_sessid` field was before calling `sessions.clear()` on her and asking her to relog to fix the problem. I think it was None to produce the infinite recursion, but I can't be sure. Maybe automatically reassign a new session to a player if they somehow inexplicably lose theirs?

**Comment by Griatch** [comment]
@TehomCD The problem appears to be that the SessionHandler could end up getting `None` as a key, which meant the on-object session cache (which fetches the sessionhandler sessions onto itself) always ended up with a `None` session in itself over and over and thus kept trying to refresh. I closed this with a fix that makes the global SessionHandler not accept None-session keys and to clean itself up whenever it can. This should avoid this particular cache-sync issue since. Reopen or make a new issue if the problem appears again.
