### ISSUE TITLE
Portal error when using channel history

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#1299]
#### Brief summary of issue / Description of requested feature:
Some of my log files for channels had gotten rather large, so I added in the EvMore utility for viewing them. While I had no issue when them while testing them initially, the first time I tried to view a large history in production I immediately generated the following traceback:

```
2017-04-06T07:56:36-0400 [AMPProtocol,0,127.0.0.1] Unhandled Error
Traceback (most recent call last):
  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 208, in doRead
    return self._dataReceived(data)
  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 214, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/protocols/amp.py", line 2411, in dataReceived
    return Int16StringReceiver.dataReceived(self, data)
  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/protocols/basic.py", line 765, in dataReceived
    self.stringReceived(packet)
  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/protocols/basic.py", line 877, in stringReceived
    self.state = statehandler(string)
  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/protocols/amp.py", line 2464, in proto_key
    self.boxReceiver.ampBoxReceived(self._currentBox)
  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/protocols/amp.py", line 1063, in ampBoxReceived
    self._answerReceived(box)
  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/protocols/amp.py", line 989, in _answerReceived
    question = self._outstandingRequests.pop(box[ANSWER])
exceptions.KeyError: '185'

2017-04-06T07:56:37-0400 [evennia.server.amp.AmpServerFactory] AMPProtocol connection established (HOST:IPv4Address(TCP, '127.0.0.1', 5000) PEER:IPv4Address(TCP, '127.0.0.1', 49122))
```
The traceback caused me to see `... Portal lost connection to Server` followed by `... Server restarted` immediately after. Then I began to see players having no commandsets reported, such as:
```
2017-04-06T07:57:05-0400 [AMPProtocol,1,127.0.0.1] [EE] No cmdsets found: None@173.31.101.93
2017-04-06T07:57:10-0400 [AMPProtocol,1,127.0.0.1] [EE] No cmdsets found: None@173.31.101.93
```

#### Steps to reproduce the issue / Reasons for adding feature:

Since this didn't happen in my test environment with the same log files, I'm unsure if this
can be easily reproduced.

1.  Log files of around 2MB in length or so
2.  Using channel/history with a large number, may require EvMore used as well

#### Error output / Expected result of feature
The above traceback.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement: 
The result of the error seemed similar to #1160 but seems to have had an entirely different cause (accessing a log file vs having the port for the AMP bridge open and someone accessing it).

**Comment by Griatch** [comment]
The error originates in the AMP layer, maybe there is an issue with splitting the very long data string into chunks possible to send over the AMP connection? It's curious it would happen when using EvMore though, I'd think that would limit the flow of data, not make it worse...

**Comment by TehomCD** [comment]
I had it happen again, and the key mentioned by the key error was a little strange. I had been assuming that they were sessids due to being all integers, but this one had letters as well.

```
2017-04-23T02:21:15-0400 [AMPProtocol,0,127.0.0.1] Unhandled Error
Traceback (most recent call last):
  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 208, in doRead
    return self._dataReceived(data)
  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 214, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/protocols/amp.py", line 2411, in dataReceived
    return Int16StringReceiver.dataReceived(self, data)
  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/protocols/basic.py", line 765, in dataReceived
    self.stringReceived(packet)
  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/protocols/basic.py", line 877, in stringReceived
    self.state = statehandler(string)
  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/protocols/amp.py", line 2464, in proto_key
    self.boxReceiver.ampBoxReceived(self._currentBox)
  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/protocols/amp.py", line 1063, in ampBoxReceived
    self._answerReceived(box)
  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/protocols/amp.py", line 989, in _answerReceived
    question = self._outstandingRequests.pop(box[ANSWER])
exceptions.KeyError: '16aba'

2017-04-23T02:21:16-0400 [evennia.server.amp.AmpServerFactory] AMPProtocol connection established (HOST:IPv4Address(TCP, '127.0.0.1', 5000) PEER:IPv4Address(TCP, '127.0.0.1', 51788))
2017-04-23T02:21:16-0400 [AMPProtocol,1,127.0.0.1] [..] Logged in: Tikva 67.170.14.245 (1 session(s) total)
2017-04-23T02:21:17-0400 [AMPProtocol,1,127.0.0.1] [..] Logged in: Aureth 67.170.14.245 (1 session(s) total)
2017-04-23T02:21:20-0400 [AMPProtocol,1,127.0.0.1] [EE] No cmdsets found: None@50.66.196.115
2017-04-23T02:21:28-0400 [AMPProtocol,1,127.0.0.1] [EE] No cmdsets found: None@140.211.14.6
2017-04-23T02:21:31-0400 [AMPProtocol,1,127.0.0.1] [EE] No cmdsets found: None@140.211.14.6
2017-04-23T02:21:32-0400 [AMPProtocol,1,127.0.0.1] [EE] No cmdsets found: None@50.66.196.115
2017-04-23T02:21:35-0400 [AMPProtocol,1,127.0.0.1] [EE] No cmdsets found: None@140.211.14.6
```

Strangely, in this case, I didn't see `...Portal has lost connection to Server.` - the format of the AMP bridge reconnecting looked identical to a normal server restart except for omitting `Server restart initiated ...`.

**Comment by Griatch** [comment]
The keyerror is indeed not for a sessid but for an AMP hash block, I believe this is used internally by the AMP protocol to reference chunks of split data too large to fit in a single AMP call. Not sure why that would fail at this point though.

**Comment by TehomCD** [comment]
This is looking like a duplicate of #1305 .
