### ISSUE TITLE
Importing commands in a view causes `evennia check` to fail

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#1372]
#### Brief summary of issue / Description of requested feature:
Doing `evennia check` will go through all views, and if any of the views have imports that are typeclasses that use the flat API, or any commands, it will raise a metaclass error. I believe this is due to the flat API initially setting the values to None before it initializes them, but for some reason `evennia check` will get them before they're properly assigned, which causes an error.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Have a view import a typeclass or command that uses the flat API for its bases.
2. use `evennia check`

#### Error output / Expected result of feature
Something like the following:
```
(arx) c:\arx\arx>evennia check
Traceback (most recent call last):
  File "c:\arx\Scripts\evennia_launcher.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "C:\arx\evennia\bin\windows\evennia_launcher.py", line 16, in <module>
    main()
  File "c:\arx\evennia\evennia\server\evennia_launcher.py", line 1333, in main
    django.core.management.call_command(*args, **kwargs)
  File "c:\arx\Lib\site-packages\django\core\management\__init__.py", line 119, in call_command
    return command.execute(*args, **defaults)
  File "c:\arx\Lib\site-packages\django\core\management\base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "c:\arx\Lib\site-packages\django\core\management\commands\check.py", line 51, in handle
    include_deployment_checks=include_deployment_checks,
  File "c:\arx\Lib\site-packages\django\core\management\base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File "c:\arx\Lib\site-packages\django\core\checks\registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "c:\arx\Lib\site-packages\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "c:\arx\Lib\site-packages\django\core\checks\urls.py", line 23, in check_resolver
    for pattern in resolver.url_patterns:
  File "c:\arx\Lib\site-packages\django\utils\functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "c:\arx\Lib\site-packages\django\core\urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "c:\arx\Lib\site-packages\django\utils\functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "c:\arx\Lib\site-packages\django\core\urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Python27\Lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\arx\arx\web\urls.py", line 43, in <module>
    namespace='help_topics', app_name='help_topics')),
  File "c:\arx\Lib\site-packages\django\conf\urls\__init__.py", line 52, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Python27\Lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\arx\arx\web\help_topics\urls.py", line 10, in <module>
    from .views import (topic, list_commands, list_topics, list_recipes,
  File "c:\arx\arx\web\help_topics\views.py", line 8, in <module>
    from commands.default_cmdsets import PlayerCmdSet, CharacterCmdSet
  File "c:\arx\arx\commands\default_cmdsets.py", line 17, in <module>
    from evennia.commands.default import cmdset_character, cmdset_player, cmdset_session, cmdset_unloggedin
  File "c:\arx\evennia\evennia\commands\default\cmdset_character.py", line 8, in <module>
    from evennia.commands.default import general, help, admin, system
  File "c:\arx\evennia\evennia\commands\default\help.py", line 14, in <module>
    from evennia.utils import create, evmore
  File "c:\arx\evennia\evennia\utils\evmore.py", line 51, in <module>
    class CmdMore(Command):
TypeError: Error when calling the metaclass bases
    cannot create 'NoneType' instances
```

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
This seems like a really minor issue, but I just wanted to mention it in case if anything else django checks or does might cause some similar issue in the future, since it took me a little bit to realize what was going on. A workaround is just not directly importing commands/cmdsets at the top level of views and just putting them as local imports in the individual views/classes. It might be resolved completely if things like `evmore` remove use of the flat API, but I'm not sure if that's worthwhile/desirable.

**Comment by Griatch** [comment]
For the flat API to be initialized, `evennia.init()` must be called, so it's not too surprising that `check` does not do this. The solution to this is to have the `evennia/server/evennia_launcher.py` (which is what runs when using the `evennia` command), initialize Evennia before passing onto the django command. A possible caveat with this is what happens with things like `evennia migrate`, which are called before the database is created; not sure if this would mess with `evennia.init()` or not.

**Comment by Griatch** [comment]
Implemented in `devel`. Will close when `devel` merges.
