### ISSUE TITLE
Broken building commands for creation

### ISSUE THREAD

**Issue by vlegoff** [evennia/evennia#1409]
#### Brief summary of issue / Description of requested feature:

Running on devel, I cannot use the default commands (like @tunnel@, @dig@, @create@...).  The same error occurs (see below).

#### Steps to reproduce the issue / Reasons for adding feature:

1. In a fresh install (at least in my game, I haven't tried a really fresh install yet).
2. Login with superuser.
3. Enter @tunnel n@.

#### Error output / Expected result of feature

For @tunnel@ (mostly same traceback for other commands):

```
Traceback (most recent call last):
  File "c:\users\vincent\evennia\evennia\commands\cmdhandler.py", line 591, in _run_command
    ret = cmd.func()
  File "c:\users\vincent\evennia\evennia\commands\default\building.py", line 782, in func
    report_to=caller)
  File "c:\users\vincent\evennia\evennia\utils\create.py", line 129, in create_object
    new_object.save()
  File "c:\users\vincent\evennia\evennia\utils\idmapper\models.py", line 393, in save
    super(SharedMemoryModel, self).save(*args, **kwargs)
  File "c:\users\vincent\pyenv\Lib\site-packages\django\db\models\base.py", line 807, in save
    force_update=force_update, update_fields=update_fields)
  File "c:\users\vincent\pyenv\Lib\site-packages\django\db\models\base.py", line 847, in save_base
    update_fields=update_fields, raw=raw, using=using,
  File "c:\users\vincent\pyenv\Lib\site-packages\django\dispatch\dispatcher.py", line 193, in send
    for receiver in self._live_receivers(sender)
  File "c:\users\vincent\evennia\evennia\typeclasses\signals.py", line 9, in post_save
    instance.at_first_save()
  File "c:\users\vincent\evennia\evennia\objects\objects.py", line 953, in at_first_save
    self.locks.add(cdict["locks"])
  File "c:\users\vincent\evennia\evennia\locks\lockhandler.py", line 305, in add
    for lockdef in lockstring.split(';'):
AttributeError: 'list' object has no attribute 'split'
```

**Comment by vlegoff** [comment]
Indeed it happens with a very fresh install of Evennia running in devel.

**Comment by Griatch** [comment]
This was now fixed on devel, it was due to the lockhandler not correctly handling locks added in lists. Closing.
