### ISSUE TITLE
'No such column' error after migrations finished

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#1440]
#### Brief summary of issue / Description of requested feature:
In testing out the devel branch, I have things into a running state, but then tried to run a weekly 'cleanup' script that gets rid of old objects, and hit a problem. One of my models is a 'Ticket' model that has a ManyToMany relationship with `settings.AUTH_USER_ACCOUNT` - what was players before, and is now accounts. When trying to run `.delete()` on a queryset of expired tickets, I get an `OperationalError` that the column isn't found, as if I hadn't run migrations to change from `playerdb` to `accountdb`.

```
2017-09-21T03:10:17-0400 [stderr#error] Traceback (most recent call last):
2017-09-21T03:10:17-0400 [stderr#error]   File "c:\fresh_evennia\testarx\typeclasses\scripts\weekly_events.py", line 199, in do_cleanup
2017-09-21T03:10:17-0400 [stderr#error]     qs.delete()
2017-09-21T03:10:17-0400 [stderr#error]   File "c:\fresh_evennia\Lib\site-packages\django\db\models\query.py", line 616, in delete
2017-09-21T03:10:17-0400 [stderr#error]     collector.collect(del_query)
2017-09-21T03:10:17-0400 [stderr#error]   File "c:\fresh_evennia\Lib\site-packages\django\db\models\deletion.py", line 222, in collect
2017-09-21T03:10:17-0400 [stderr#error]     elif sub_objs:
2017-09-21T03:10:17-0400 [stderr#error]   File "c:\fresh_evennia\Lib\site-packages\django\db\models\query.py", line 258, in __nonzero__
2017-09-21T03:10:17-0400 [stderr#error]     return type(self).__bool__(self)
2017-09-21T03:10:17-0400 [stderr#error]   File "c:\fresh_evennia\Lib\site-packages\django\db\models\query.py", line 254, in __bool__
2017-09-21T03:10:17-0400 [stderr#error]     self._fetch_all()
2017-09-21T03:10:17-0400 [stderr#error]   File "c:\fresh_evennia\Lib\sitepackages\django\db\models\query.py", line 1118, in _fetch_all
2017-09-21T03:10:17-0400 [stderr#error]     self._result_cache = list(self._iterable_class(self))
2017-09-21T03:10:17-0400 [stderr#error]   File "c:\fresh_evennia\Lib\site-packages\django\db\models\query.py", line 53,
in __iter__
2017-09-21T03:10:17-0400 [stderr#error]     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
2017-09-21T03:10:17-0400 [stderr#error]   File "c:\fresh_evennia\Lib\site-packages\django\db\models\sql\compiler.py", li
ne 894, in execute_sql
2017-09-21T03:10:17-0400 [stderr#error]     raise original_exception
2017-09-21T03:10:17-0400 [stderr#error] OperationalError: no such column: helpdesk_ticket_participants.accountdb_id
2017-09-21T03:10:17-0400 [stdout#info] Error in cleaning tickets: no such column: helpdesk_ticket_participants.accountdb_id
```

#### Steps to reproduce the issue / Reasons for adding feature:

1. Ran my weekly cleanup script

#### Error output / Expected result of feature
Above traceback

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
This is after the migration steps listed for the devel branch. Most things seem to work fine, this is the first major hurdle I've hit so far.

I'll try redoing the whole migration process and see if it was a fluke. It's the only instance of a `ManyToMany` to `AUTH_USER_MODEL`, so that might be why I'm seeing it - though I'd have no idea why the ManyToManys in Msg work fine while this failed.

**Comment by Griatch** [comment]
This looks like something you need to handle manually. The migration does not know anything about your custom table after all. My guess is that your `Ticket` model  still has a M2M intermediary table that links to player rather than account but you have renamed to "account" on the Python side (with the help of the rename program). 

Since I know you use sqlite3, go into `evennia dbshell` and use `.tables`. Look for something like `helpdesk_ticket_players` (might not be the exact name, but it will end in `players`). That would be the left-over m2m intermediary for an app `helpdesk` with a model `ticket` linking to `player` You need to rename this to what django now expects. Try something like
```sql
ALTER TABLE helpdesk_ticket_players RENAME TO helpdesk_ticket_accounts;
```

As usual, test first on a devel database etc, just to be safe. :)

**Comment by TehomCD** [comment]
Thanks! I had been kind of meaning to rework some of these models that had the ManyToMany relationships to PlayerDB anyway, so I'll probably wind up creating different explicit intermediary/through tables and see if those handle the migration properly. I'm guessing they should, since everything that just had a normal ForeignKey to PlayerDB worked fine.

**Comment by Griatch** [comment]
Let me know if there are any other issues. Closing this for now.
