### ISSUE TITLE
Evmenu: Nodes cannot be used for dynamic exec or dynamic goto

### ISSUE THREAD

**Issue by CloudKeeper1** [evennia/evennia#1457]
#### Brief summary of issue / Description of requested feature:
EvMenu currently allows for a function given as an exec or goto argument to return a string which will take precedence over an existing goto. [EvMenu appears to expect that nodes will also be able to return a string that can be used in the same way](https://github.com/evennia/evennia/blob/master/evennia/utils/evmenu.py#L622), however due to the way [_execute_node()](https://github.com/evennia/evennia/blob/master/evennia/utils/evmenu.py#L523) is set out this cannot happen.

#### Steps to reproduce the issue / Reasons for adding feature:
1. Create a node (function not starting with an underscore) in line with [this example.](https://github.com/evennia/evennia/wiki/EvMenu#example-dynamic-goto)
2. Provide that node as a goto or exec as a string. This will use the _execute_node() method rather than calling the node directly.
3. Receive error.

#### Error output / Expected result of feature
Error in menu node 'check_choice'.
Traceback (most recent call last):
  File "c:\users\user\my documents\python\evennia\evennia\commands\cmdhandler.py", line 509, in _run_command
    ret = yield cmd.func()
  File "c:\users\user\my documents\python\evennia\evennia\utils\evmenu.py", line 266, in func
    menu._input_parser(menu, self.raw_string, caller)
  File "c:\users\user\my documents\python\evennia\evennia\utils\evmenu.py", line 404, in evtable_parse_input
    menuobject.callback_goto(callback, goto, raw_string)
  File "c:\users\user\my documents\python\evennia\evennia\utils\evmenu.py", line 733, in callback_goto
    self.goto(goto, raw_string)
  File "c:\users\user\my documents\python\evennia\evennia\utils\evmenu.py", line 806, in goto
    nodetext, options = self._execute_node(nodename, raw_string)
  File "c:\users\user\my documents\python\evennia\evennia\utils\evmenu.py", line 698, in _execute_node
    nodetext, options = node(self.caller, raw_string)
ValueError: too many values to unpack

An untrapped error occurred.
(Traceback was logged 2017-10-01 19:14:38+1100).
Traceback (most recent call last):
  File "c:\users\user\my documents\python\evennia\evennia\commands\cmdhandler.py", line 653, in cmdhandler
    unformatted_raw_string, cmdset, session, player)
ErrorReported: 1

**Comment by RyanStein** [comment]
Looks similar to what I encountered in #1429.

**Comment by Griatch** [comment]
@RyanStein Looking at it more, you are correct, it looks like it's the same thing except the traceback is included. I'm closing this one and linking it to #1429.
