### ISSUE TITLE
Preparing Evennia for Pypy

### ISSUE THREAD

**Issue by RyanStein** [evennia/evennia#1472]
There seems to be two separate issues keeping Evennia from running on Pypy, one of which is the `cStringIO` module apparently being overshadowed by Pypy's default `cStringIO.py` module which returns `StringIO`, with `evennia_launcher.py` setting the `PYTHONPATH` environment variable for use by a `Popen`ed instance of `evennia_runner.py` which then `Popen`s `twistd`:

```
Traceback (most recent call last):                                                                                      
  File "pyenv-pypy/bin/twistd", line 11, in <module>                                            
    sys.exit(run())                                                                                                     
  File "pyenv-pypy/site-packages/twisted/scripts/twistd.py", line 29, in run                    
    app.run(runApp, ServerOptions)                                                                                      
  File "pyenv-pypy/site-packages/twisted/application/app.py", line 662, in run                  
    runApp(config)                                                                                                      
  File "pyenv-pypy/site-packages/twisted/scripts/twistd.py", line 25, in runApp                 
    _SomeApplicationRunner(config).run()                                                                                
  File "pyenv-pypy/site-packages/twisted/application/app.py", line 382, in run                  
    self.logger.start(self.application)                                                                                 
  File "pyenv-pypy/site-packages/twisted/application/app.py", line 191, in start                
    observer = self._getLogObserver()                                                                                   
  File "pyenv-pypy/site-packages/twisted/scripts/_twistd_unix.py", line 172, in _getLogObserver 
    return logger.textFileLogObserver(logFile)                                                                          
  File "pyenv-pypy/site-packages/twisted/logger/_file.py", line 86, in textFileLogObserver      
    return FileLogObserver(outFile, formatEvent)                                                                        
  File "pyenv-pypy/site-packages/twisted/logger/_file.py", line 34, in __init__                 
    if ioType(outFile) is not unicode:                                                                                  
  File "pyenv-pypy/site-packages/twisted/python/compat.py", line 395, in ioType                 
    from cStringIO import InputType, OutputType                                                                         
ImportError: cannot import name 'InputType'
```

Commenting out [this line](https://github.com/evennia/evennia/blob/a994fd3c63bd0120f5c8745fad97fedb0d849ee3/evennia/server/evennia_launcher.py#L662) seems to resolve this issue, but I'm wondering if there's maybe a cleaner way to handle this? That is, if having the `PYTHONPATH` environment variable set is really useful at all for this project. At the very least, we can check if the user is running Pypy and not copy `sys.path` into there.

I haven't been able to reproduce this bug outside of Evennia using minimal test cases which use `PYTHONPATH` to overshadow `cStringIO` through a `Popen`ed subprocess of Pypy, so I'm not sure if it originates from somewhere within Evennia itself, Pypy, or even Twistd or Django. Tracking down its source has been difficult.

The next problem keeping Evennia from booting in Pypy is much simpler.

```
Traceback (most recent call last):
  File "pyenv-pypy/site-packages/twisted/application/app.py", line 662, in run
    runApp(config)
  File "pyenv-pypy/site-packages/twisted/scripts/twistd.py", line 25, in runApp
    _SomeApplicationRunner(config).run()
  File "pyenv-pypy/site-packages/twisted/application/app.py", line 380, in run
    self.application = self.createOrGetApplication()
  File "pyenv-pypy/site-packages/twisted/application/app.py", line 445, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "pyenv-pypy/site-packages/twisted/application/app.py", line 456, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "pyenv-pypy/site-packages/twisted/application/service.py", line 412, in loadApplication
    application = sob.loadValueFromFile(filename, 'application')
  File "pyenv-pypy/site-packages/twisted/persisted/sob.py", line 177, in loadValueFromFile
    eval(codeObj, d, d)
  File "evennia-dev/evennia/server/server.py", line 535, in <module>
    EVENNIA = Evennia(application)
  File "evennia-dev/evennia/server/server.py", line 186, in __init__
    channelhandler.CHANNELHANDLER.update()
  File "evennia-dev/evennia/comms/channelhandler.py", line 258, in update
    self.add(channel)
  File "evennia-dev/evennia/comms/channelhandler.py", line 218, in add
    locks="cmd:all();%s" % channel.locks,
  File "evennia-dev/evennia/utils/utils.py", line 1679, in __get__
    value = self.func(obj)
  File "evennia-dev/evennia/typeclasses/models.py", line 269, in locks
    return LockHandler(self)
  File "evennia-dev/evennia/locks/lockhandler.py", line 184, in __init__
    self.reset()
  File "evennia-dev/evennia/locks/lockhandler.py", line 421, in reset
    self._cache_locks(self.obj.lock_storage)
  File "evennia-dev/evennia/utils/idmapper/models.py", line 175, in fget
    def fget(cls): return _get(cls, fieldname)
  File "evennia-dev/evennia/utils/idmapper/models.py", line 116, in _get
    if _GA(cls, "_is_deleted"):
exceptions.TypeError: unbound method __getattribute__() must be called with newobject instance as first argument (got Channel instance instead)
```

Pypy doesn't seem to like the use of `object.__getattribute__` on instances which are not `object`, which appears to be a simple enough fix. Changing [this line](https://github.com/evennia/evennia/blob/a994fd3c63bd0120f5c8745fad97fedb0d849ee3/evennia/utils/idmapper/models.py#L30) from:

```python
_GA = object.__getattribute__
```

..to..

```python
def _GA(obj, key):
    return object.__getattribute__.__get__(obj)(key)
```

..appears to resolve these sort of issues. There are several instances in different files where `_GA` appears, and they would all have to be made compatible, likely `_SA` and `_DA` as well, as they follow suit in using `object` methods on non-object instances.

These are the initial blockers at least, to getting Evennia up and running with Pypy. There may be more issues, but this is what I've discovered so far in my research. If anyone more experienced with Python can offer suggestions, I'd appreciate it.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

ArchLinux, Linux 4.12.13-1-ARCH x86_64
pypy 5.9.0-1, using python-virtualenv 15.1.0-1
Evennia 0.7.0 (rev a994fd3c)

**Comment by Griatch** [comment]
Interesting observations, thanks for your work on this so far!
- The `PYTHONPATH` is generally necessary to allow imports across the library on different platforms. If it is necessary at that particular point or if it could be handled differently is certainly possible though. 
- The `_GA` change is weird, but not hard to change.

**Comment by Griatch** [comment]
The checks done here are superseded by one big point - PyPy currently (Sept 2019) is only compatible with CPython 3.6. So this is put on hold for now.

**Comment by aogier** [comment]
FYI I've just tested develop branch against pypy3.9 7.3.9 and the two reported issues seems to be ironed out by natural evolution of codebase and its deps: in fact, I can now install and run evennia to the point I'm logged in and everything seems to work as usual yay ! :tada: 

I'm having trouble to test in CI tho, getting failures about a missing `cgi` (builtin) module which seems to be present, ie. `python -c 'import cgi'` does not error, could somebody please help me on that? A failing check [is here](https://github.com/evennia/evennia/runs/7473926544?check_suite_focus=true), PR [is here](https://github.com/evennia/evennia/pull/2810)

**Comment by aogier** [comment]
PR is now working it seems, yay! Maybe we will soon welcome pypy
