### ISSUE TITLE
postgreSQL is not working after manage.py migrate

### ISSUE THREAD

**Issue by Griatch** [evennia/evennia#151]
_From [mar...@heavy.ch](https://code.google.com/u/108070488478849164028/) on March 23, 2011 22:50:44_

A) What steps will reproduce the problem? 1. install evennia and also postgresql and psycopg2
2. creating some user and database for evnnia
3. configure the settings.py with something like: django.db.backends.postgresql_psycopg2
4. run manage.py syncdb, see how some tables are created on the database
5. after this manage.py migrate for south
5. and see the error message like "django.db.utils.DatabaseError: FEHLER:  Relation »objects_objectdb« existiert nicht" B) What is the expected output? What do you see instead (tracebacks, error messages)? my settings.py

> > > SNIP>>>
> > > DATABASES = {
> > >     'default':{
> > >         'ENGINE':'django.db.backends.postgresql_psycopg2',
> > >         'NAME':'evennia',
> > >         'USER':'evennia',
> > >         'PASSWORD':'asdfxyvysdf',
> > >         'HOST':'localhost',
> > >         'PORT':'5432'
> > >         }}

DATABASE_ENGINE = 'postgresql_psycopg2'
DATABASE_NAME = 'evennia'
DATABASE_USER = 'evennia'
DATABASE_PASSWORD = 'asdfxyvysdf'
DATABASE_HOST = 'localhost'
DATABASE_PORT = '5432'
<<<SNAP<<<

"manage.py syncdb" worked (and around ~20 tables are created), but after I input "manage.py migrate" i received the following error:

> > > SNIP>>>
> > >   File "/home/lestat/Development/mud/lib/python2.6/site-packages/south/migration/**init**.py", line 191, in migrate_app
> > >     success = migrator.migrate_many(target, workplan, database)
> > >   File "/home/lestat/Development/mud/lib/python2.6/site-packages/south/migration/migrators.py", line 221, in migrate_many
> > >     result = migrator.**class**.migrate_many(migrator, target, migrations, database)
> > >   File "/home/lestat/Development/mud/lib/python2.6/site-packages/south/migration/migrators.py", line 292, in migrate_many
> > >     result = self.migrate(migration, database)
> > >   File "/home/lestat/Development/mud/lib/python2.6/site-packages/south/migration/migrators.py", line 125, in migrate
> > >     result = self.run(migration)
> > >   File "/home/lestat/Development/mud/lib/python2.6/site-packages/south/migration/migrators.py", line 99, in run
> > >     return self.run_migration(migration)
> > >   File "/home/lestat/Development/mud/lib/python2.6/site-packages/south/migration/migrators.py", line 82, in run_migration
> > >     south.db.db.execute_deferred_sql()
> > >   File "/home/lestat/Development/mud/lib/python2.6/site-packages/south/db/generic.py", line 184, in execute_deferred_sql
> > >     self.execute(sql)
> > >   File "/home/lestat/Development/mud/lib/python2.6/site-packages/south/db/generic.py", line 150, in execute
> > >     cursor.execute(sql, params)
> > >   File "/home/lestat/Development/mud/lib/python2.6/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 44, in execute
> > >     return self.cursor.execute(query, args)
> > > django.db.utils.DatabaseError: FEHLER:  Relation »objects_objectdb« existiert nicht
> > > <<<SNAP<<<

In my postgresql I see some table "south_migrationhistory" for example but sure "evennia.py -i start" don't work:

> > > SNIP>>>
> > > eObj in d, d
> > >   File "/home/lestat/Development/mud/evennia/src/server/server.py", line 183, in <module>
> > >     EVENNIA = Evennia(application)
> > >   File "/home/lestat/Development/mud/evennia/src/server/server.py", line 77, in **init**
> > >     self.run_initial_setup()
> > >   File "/home/lestat/Development/mud/evennia/src/server/server.py", line 131, in run_initial_setup
> > >     initial_setup.handle_setup(0)
> > >   File "/home/lestat/Development/mud/evennia/src/server/initial_setup.py", line 235, in handle_setup
> > >     for obj in ObjectDB.objects.all():
> > >   File "/home/lestat/Development/mud/lib/python2.6/site-packages/django/db/models/query.py", line 105, in _result_iter
> > >     self._fill_cache()
> > >   File "/home/lestat/Development/mud/lib/python2.6/site-packages/django/db/models/query.py", line 783, in _fill_cache
> > >     self._result_cache.append(self._iter.next())
> > >   File "/home/lestat/Development/mud/lib/python2.6/site-packages/django/db/models/query.py", line 271, in iterator
> > >     for row in compiler.results_iter():
> > >   File "/home/lestat/Development/mud/lib/python2.6/site-packages/django/db/models/sql/compiler.py", line 677, in results_iter
> > >     for rows in self.execute_sql(MULTI):
> > >   File "/home/lestat/Development/mud/lib/python2.6/site-packages/django/db/models/sql/compiler.py", line 732, in execute_sql
> > >     cursor.execute(sql, params)
> > >   File "/home/lestat/Development/mud/lib/python2.6/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 44, in execute
> > >     return self.cursor.execute(query, args)
> > > django.db.utils.DatabaseError: FEHLER:  aktuelle Transaktion wurde abgebrochen, Befehle werden bis zum Ende der Transaktion ignoriert

Failed to load application: FEHLER:  aktuelle Transaktion wurde abgebrochen, Befehle werden bis zum Ende der Transaktion ignoriert
<<<SNIP<<<

If I doing now again "migrate.py syncdb" I receive this output:

> > > SNIP>>>
> > > (mud)lestat@lestat:~/Development/mud/evennia/game$ ./manage.py syncdb
> > > Syncing...
> > > No fixtures found.

Synced:

> django.contrib.auth
> django.contrib.sites
> django.contrib.contenttypes
> django.contrib.sessions
> django.contrib.admin
> django.contrib.admindocs
> django.contrib.flatpages
> src.imc2
> src.irc
> src.web.news
> src.web.website
> south

Not synced (use migrations):
- src.config
- src.players
- src.objects
- src.comms
- src.help
- src.scripts
  (use ./manage.py migrate to migrate these)
  <<<SNAP<<<

but sure manage.py migrate leads to the error :-( C) What version/svn revision of Evennia are you using? On what operating system? Give as much information as possible to make it easier for developers to recreate the problem. \* Revision 1394 . D) Please provide any additional information/suggestions below. PostgreSQL 8.4.7

My Install-Documentation can be found here: http://lotek.heavy.ch/evennia#Database bye
Marcel

_Original issue: http://code.google.com/p/evennia/issues/detail?id=151_

**Comment by Mangiang** [comment]
Unfortunately not, I get the same error : 
2015-08-19 12:59:00+0200 [-] Log opened.
2015-08-19 12:59:00+0200 [-] twistd 15.3.0 (C:\Python27\pyenv\Scripts\python.exe 2.7.9) starting up.
2015-08-19 12:59:00+0200 [-] reactor class: twisted.internet.selectreactor.SelectReactor.
2015-08-19 12:59:00+0200 [-] Traceback (most recent call last):
2015-08-19 12:59:00+0200 [-]   File "C:\Python27\pyenv\scripts\twistd.py", line 14, in <module>
2015-08-19 12:59:00+0200 [-]     run()
2015-08-19 12:59:00+0200 [-]   File "C:\Python27\pyenv\Lib\site-packages\twisted\scripts\twistd.py", line 29, in run
2015-08-19 12:59:00+0200 [-]     app.run(runApp, ServerOptions)
2015-08-19 12:59:00+0200 [-]   File "C:\Python27\pyenv\Lib\site-packages\twisted\application\app.py", line 617, in run
2015-08-19 12:59:00+0200 [-]     runApp(config)
2015-08-19 12:59:00+0200 [-]   File "C:\Python27\pyenv\Lib\site-packages\twisted\scripts\twistd.py", line 25, in runApp
2015-08-19 12:59:00+0200 [-]     _SomeApplicationRunner(config).run()
2015-08-19 12:59:00+0200 [-]   File "C:\Python27\pyenv\Lib\site-packages\twisted\application\app.py", line 352, in run
2015-08-19 12:59:00+0200 [-]     self.postApplication()
2015-08-19 12:59:00+0200 [-]   File "C:\Python27\pyenv\Lib\site-packages\twisted\scripts\_twistw.py", line 46, in postApplication
2015-08-19 12:59:00+0200 [-]     service.IService(self.application).privilegedStartService()
2015-08-19 12:59:00+0200 [-]   File "C:\Python27\pyenv\Lib\site-packages\twisted\application\service.py", line 278, in privilegedStartService
2015-08-19 12:59:00+0200 [-]     service.privilegedStartService()
2015-08-19 12:59:00+0200 [-]   File "C:\Python27\pyenv\Lib\site-packages\twisted\application\internet.py", line 106, in privilegedStartService
2015-08-19 12:59:00+0200 [-]     self._port = self._getPort()
2015-08-19 12:59:00+0200 [-]   File "C:\Python27\pyenv\Lib\site-packages\twisted\application\internet.py", line 134, in _getPort
2015-08-19 12:59:00+0200 [-]     'listen%s' % (self.method,))(*self.args, **self.kwargs)
2015-08-19 12:59:00+0200 [-]   File "C:\Python27\pyenv\Lib\site-packages\twisted\internet\posixbase.py", line 478, in listenTCP
2015-08-19 12:59:00+0200 [-]     p.startListening()
2015-08-19 12:59:00+0200 [-]   File "C:\Python27\pyenv\Lib\site-packages\twisted\internet\tcp.py", line 984, in startListening
2015-08-19 12:59:00+0200 [-]     raise CannotListenError(self.interface, self.port, le)
2015-08-19 12:59:00+0200 [-] twisted.internet.error.CannotListenError: Couldn't listen on 95.58.249.113:4000: [Errno 10049] LÆadresse demandÚe nÆest pas valide dans son contexte.
