### ISSUE TITLE
Connected player spontaneously gained Unloggedin Cmdset

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#1564]
#### Brief summary of issue / Description of requested feature:
I can't reproduce this at all, but a character who was already connected acquired the Unloggedin cmdset after a `@reload`. They could still move around and use any existing command from their other cmdsets, but `look` was replaced by UnconnectedLook which displayed the login screen, and they had the connect command.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Reloaded the server.
2. The affected character hit look and saw the connection screen.
3. They then thought they had been disconnected and tried to connect.

#### Error output / Expected result of feature
```
2018-02-05 00:44:31-0500 [AMPProtocol,0,127.0.0.1] [::] Traceback (most recent call last):
2018-02-05 00:44:31-0500 [AMPProtocol,0,127.0.0.1] [::]   File "/home/tehom/arx/evennia/evennia/commands/cmdhandler.py", line 591, in _run_command
2018-02-05 00:44:31-0500 [AMPProtocol,0,127.0.0.1] [::]     ret = cmd.func()
2018-02-05 00:44:31-0500 [AMPProtocol,0,127.0.0.1] [::]   File "/home/tehom/arx/evennia/evennia/commands/default/unloggedin.py", line 212, in func
2018-02-05 00:44:31-0500 [AMPProtocol,0,127.0.0.1] [::]     if _throttle(session, maxlim=5, timeout=5 * 60, storage=_LATEST_FAILED_LOGINS):
2018-02-05 00:44:31-0500 [AMPProtocol,0,127.0.0.1] [::]   File "/home/tehom/arx/evennia/evennia/commands/default/unloggedin.py", line 56, in _throttle
2018-02-05 00:44:31-0500 [AMPProtocol,0,127.0.0.1] [::]     address = session.address
2018-02-05 00:44:31-0500 [AMPProtocol,0,127.0.0.1] [::] AttributeError: 'Character' object has no attribute 'address'
```

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
This was so utterly bizarre, but I thought it might in some way be related to other bugs that involve loss of cmdsets when the portal has some error. Hopefully resolved by new develop branch changes.

**Comment by Griatch** [comment]
@TehomCD This is indeed very strange. Was this with the webclient?

**Comment by TehomCD** [comment]
I don't believe so, but I didn't think to ask the player what telnet client he was using, apologies. It's definitely the only instance I've ever seen of the error, and there wasn't anything that seemed to lead up to it - no weird AMP errors or portal errors or anything.

**Comment by Griatch** [comment]
@TehomCD Any followup on this?

**Comment by TehomCD** [comment]
Never had this happen again, and it was a big enough deal that I think people would have mentioned if it ever happened. So hopefully just some freak one-off occurrence.

**Comment by Griatch** [comment]
Ok, closing for this for now then.
