### ISSUE TITLE
Compile/Run error when loading cmdset

### ISSUE THREAD

**Issue by taladan** [evennia/evennia#1622]
#### Brief summary of issue / Description of requested feature:
Getting a Compile/Run error when loading cmdset 'commands.pegasus_cmdsets.TableTestCmd'.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Command File (jobtest) contains:

```
#!/usr/bin/python
# -*- coding: utf-8 -*-

from evennia import default_cmds
from evennia.utils.evtable import EvTable, EvCell, EvColumn


class TableTestCmd(default_cmds.MuxCommand):
   
    key = "+jtest"

    def func(self):

        self.caller.msg("Foo")
``` 
2. CommandSet File (pegasus_cmdsets) contains:
```
from evennia import CmdSet
from world.bitbucket.jobtest import TableTestCmd


class TableCmdSet(CmdSet):

    def at_cmdset_creation(self):
        self.add(TableTestCmd)
```
3. Per [the wiki](https://github.com/evennia/evennia/wiki/Adding-Command-Tutorial#adding-the-command-to-specific-object-types) I type:
```
@py self.cmdset.add("pegasus_cmdsets.TableTestCmd")
```
Then it errors.

#### Error output / Expected result of feature

```
>>> self.cmdset.add("TableTestCmd")
  File "/home/swift/muddev/evennia/evennia/commands/cmdsethandler.py", line 433, in add
    cmdset = self._import_cmdset(cmdset)
  File "/home/swift/muddev/evennia/evennia/commands/cmdsethandler.py", line 345, in _import_cmdset
    return import_cmdset(cmdset_path, self.obj, emit_to_obj)
  File "/home/swift/muddev/evennia/evennia/commands/cmdsethandler.py", line 166, in import_cmdset
    raise ImportError("The path '%s' is not on the form modulepath.ClassName" % path)
ImportError: The path 'TableTestCmd' is not on the form modulepath.ClassName
>>> self.cmdset.add("pegasus_cmdsets.TableTestCmd")
(Unsuccessfully tried 'pegasus_cmdsets.TableTestCmd').Traceback (most recent call last):
  File "/home/swift/muddev/evennia/evennia/commands/cmdsethandler.py", line 198, in import_cmdset
    cmdsetclass = cmdsetclass(cmdsetobj)
TypeError: __init__() takes exactly 1 argument (2 given)
```
#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Version output:
```
Evennia 0.7.0 (rev 5335f217)
         MU* development system

         Licence https://opensource.org/licenses/BSD-3-Clause
         Web http://www.evennia.com
         Irc #evennia on irc.freenode.net:6667
         Forum http://www.evennia.com/discussions
         Maintainer (2010-)   Griatch (griatch AT gmail DOT com)
         Maintainer (2006-10) Greg Taylor

         OS posix
         Python 2.7.14
         Twisted 16.0.0
         Django 1.11.10
```

OS Info:
```
Distributor ID: Ubuntu
Description:    Ubuntu 17.10
Release:        17.10
Codename:       artful
```

**Comment by Griatch** [comment]
As Tehom (and the wiki) says, you should a cmdset, not a Command. Closing.

**Comment by taladan** [comment]
Ah!  that makes sense.  Sorry for the false alarm, thought I'd found a bug.  thanks Tehom & Griatch
