### ISSUE TITLE
SharedMemoryModel.cache_instance causes infinite recursion in absurdly specific circumstances

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#1643]
#### Brief summary of issue / Description of requested feature:
So when playing around with `__getattr__` I found an incredibly rare and niche edge case that can cause infinite recursion with the `SharedMemoryModel.cache_instance`. Confused? I was too! The deal here is if you have a `SharedMemoryModel` object that has a foreignkey to an `AccountDB` object, and then have a `__getattr__` call that happens to use that foreignkey, the `tearDown` method of unit tests where the account is deleted will cause an infinite recursion loop. How? Apparently in the process of the account's delete method it'll check through all related objects to determine if any of them need cascade deletion. This will cause the instances to be added to the instance cache. When added to the instance cache, SharedMemoryModel attempts to call `at_init` on them and catches the AttributeError. This will call any `__getattr__` method defined on them. That would all be fine, except that if they try to access their foreignkey to the Account object, it tries to access the `related_descriptor` for the field, and does a `getattr(instance, self.cache_name)` for the descriptor. Which then calls `__getattr__` in the instance. Which then calls the descriptor... and so on, and so forth.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Define `__getattr__` in a model that has a foreignkey to Account (Character, say) and do something with that field.
2. Delete the Account.

#### Error output / Expected result of feature
A traceback like this one:
```
Traceback (most recent call last):
  File "c:\arx\evennia\evennia\utils\test_resources.py", line 66, in tearDown
    self.account.delete()
  File "c:\arx\evennia\evennia\accounts\accounts.py", line 384, in delete
    super(DefaultAccount, self).delete(*args, **kwargs)
  File "c:\arx\evennia\evennia\typeclasses\models.py", line 607, in delete
    super(TypedObject, self).delete()
  File "c:\arx\evennia\evennia\utils\idmapper\models.py", line 367, in delete
    super(SharedMemoryModel, self).delete(*args, **kwargs)
  File "c:\arx\Lib\site-packages\django\db\models\base.py", line 973, in delete
    collector.collect([self], keep_parents=keep_parents)
  File "c:\arx\Lib\site-packages\django\db\models\deletion.py", line 223, in collect
    field.remote_field.on_delete(self, field, sub_objs, self.using)
  File "c:\arx\Lib\site-packages\django\db\models\deletion.py", line 17, in CASCADE
    source_attr=field.name, nullable=field.null)
  File "c:\arx\Lib\site-packages\django\db\models\deletion.py", line 222, in collect
    elif sub_objs:
  File "c:\arx\Lib\site-packages\django\db\models\query.py", line 258, in __nonzero__
    return type(self).__bool__(self)
  File "c:\arx\Lib\site-packages\django\db\models\query.py", line 254, in __bool__
    self._fetch_all()
  File "c:\arx\Lib\site-packages\django\db\models\query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "c:\arx\Lib\site-packages\django\db\models\query.py", line 63, in __iter__
    obj = model_cls.from_db(db, init_list, row[model_fields_start:model_fields_end])
  File "c:\arx\Lib\site-packages\django\db\models\base.py", line 583, in from_db
    new = cls(*values)
  File "c:\arx\evennia\evennia\utils\idmapper\models.py", line 73, in __call__
    cls.cache_instance(cached_instance, new=True)
  File "c:\arx\evennia\evennia\utils\idmapper\models.py", line 281, in cache_instance
    instance.at_init()
  File "c:\arx\arx\world\dominion\models.py", line 4708, in __getattr__
    elif not self.player:
  File "c:\arx\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 178, in __get__
    rel_obj = getattr(instance, self.cache_name)
  File "c:\arx\arx\world\dominion\models.py", line 4708, in __getattr__
    elif not self.player:
  File "c:\arx\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 178, in __get__
    rel_obj = getattr(instance, self.cache_name)
```

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Probably change the at_init check to have a hasattr() check instead.

**Comment by TehomCD** [comment]
After looking more at it, I think this is a django bug, not an evennia one, and looks like it's fixed in the current version of django. Seems really unlikely anyone else will run into something like this in the meantime.
