### ISSUE TITLE
Operational Error while running tutorial

### ISSUE THREAD

**Issue by vishakhpk** [evennia/evennia#1772]
#### Brief summary of issue / Description of requested feature:
Trying to set up Evennia but I run into an issue which I think is related to the permissions of the database 
for the games. Actual error line:
OperationalError: attempt to write a readonly database 

#### Steps to reproduce the issue / Reasons for adding feature:

1. Install evennia from source, django 1.8.19 as set by requirements
2. ./start.sh 2 - server begins to run but following error log appears before you set the superuser name and password:
Traceback (most recent call last):
  File "/usr/local/bin/evennia", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/.../text-world/bin/unix/evennia", line 10, in <module>
    main()
  File "/.../text-world/evennia/server/evennia_launcher.py", line 1036, in main
    init_game_directory(CURRENT_DIR, check_db=True)
  File "/.../text-world/evennia/server/evennia_launcher.py", line 715, in init_game_directory
    check_database()
  File "/.../text-world/evennia/server/evennia_launcher.py", line 492, in check_database
    if not isinstance(tables[0], basestring): # django 1.8+
IndexError: list index out of range
3. Try to connect to port through TelNet and run into the following error log when trying to login with said created superuser

#### Error output / Expected result of feature
Traceback (most recent call last):
  File "/.../text-world/evennia/commands/cmdhandler.py", line 386, in _run_command
    ret = yield cmd.func()
  File "/.../text-world/evennia/commands/default/unloggedin.py", line 189, in func
    session.sessionhandler.login(session, player)
  File "/.../text-world/evennia/server/sessionhandler.py", line 264, in login
    player.is_connected = True
  File "/.../text-world/evennia/utils/idmapper/models.py", line 175, in <lambda>
    fset = lambda cls, val: _set(cls, fieldname, val)
  File "/.../text-world/evennia/utils/idmapper/models.py", line 130, in _set
    _GA(cls, "save")(update_fields=update_fields)
  File "/.../text-world/evennia/utils/idmapper/models.py", line 369, in save
    super(SharedMemoryModel, self).save(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 710, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 738, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 803, in _save_table
    forced_update)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 853, in _do_update
    return filtered._update(values) > 0
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 580, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 1048, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 829, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: attempt to write a readonly database

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Master branch only, I think there's a simple fix and this is just a brain fade somewhere

**Comment by Griatch** [comment]
@vishakhpk This is likely because your database is in a superuser directory. Maybe you installed using sudo? Check which permission the file gamedir/server/evennia.db3 has - it should be owned/readable by you and not owned by root. 
If you did install as root, it's probably easier to wipe that which you installed that way and start over in the GettingStarted instructions. You don't need to be root (or use sudo) beyond installing the dependencies (e.g. with `apt`). 

I don't know what `/start.sh 2 ` is, some custom script of yours?

**Comment by vishakhpk** [comment]
The permissions of evennia.db3 in text-world/game1/game1/server are set to 644 so I should be able to read it right. To clarify, you meant whether I installed evennia as root or sqlite, so that I can try this for the fix? And start.sh is not my script, it's the one in /text-world/evennia to launch an instance.

**Comment by Griatch** [comment]
@vishakhpk You should not install evennia as root (that is, when you do `pip install -e evennia` inside your virtualenv). Sqlite3 is installed automatically and the `evennia.db3` file is created when you do the `evennia migrate` action from your game dir. Your file permission `644` means the owner of the file can read-write but everyone else can only read - check who is the owner of the file and make sure it's not `root`. 
And again, I don't know where `start.sh` comes from, there is no file named `start.sh` in the evennia distribution, certainly not one to start an instance - so not sure where you got it from. You start evennia with `evennia start` from your game dir (see [the documentation here](https://github.com/evennia/evennia/wiki/Start-Stop-Reload)
