### ISSUE TITLE
[Bug] Combination of rm attribute with capitalization causes error

### ISSUE THREAD

**Issue by Griatch** [evennia/evennia#1776]
#### Brief summary of issue / Description of requested feature:

User QBFreak reported through IRC that a particular sequence of attribute creation, deletion and creation causes a traceback.

#### Steps to reproduce the issue / Reasons for adding feature:

1. `@create tablet`
2. `@set tablet/MyAttr="test"`
3. `@py del self.contents[0].db.MyAttr`
4.  `@set tablet/MyAttr="test"`

#### Error output / Expected result of feature
```Traceback (most recent call last):
  File "/data/chiana/Projects/evennia/evennia/commands/cmdhandler.py", line 591, in _run_command
    ret = cmd.func()
  File "/data/chiana/Projects/evennia/evennia/commands/default/building.py", line 1688, in func
    result.append(self.set_attr(obj, attr, value))
  File "/data/chiana/Projects/evennia/evennia/commands/default/building.py", line 1564, in set_attr
    obj.attributes.add(attr, value)
  File "/data/chiana/Projects/evennia/evennia/typeclasses/attributes.py", line 513, in add
    attr_obj.value = value
  File "/data/chiana/Projects/evennia/evennia/typeclasses/attributes.py", line 153, in __value_set
    self.save(update_fields=["db_value"])
  File "/data/chiana/Projects/evennia/evennia/utils/idmapper/models.py", line 393, in save
    super(SharedMemoryModel, self).save(*args, **kwargs)
  File "/data/chiana/Projects/evennia/venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/data/chiana/Projects/evennia/venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/data/chiana/Projects/evennia/venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 896, in _save_table
    raise ValueError("Cannot force an update in save() with no primary key.")
ValueError: Cannot force an update in save() with no primary key.

```

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

This appears to be a special case when the attribute contains capital letters, the user didn't report a problem when using lower-case name for the Attribute.

**Comment by QBFreak** [comment]
> This appears to be a special case when the attribute contains capital letters, the user didn't report a problem when using lower-case name for the Attribute.

That is correct. If the attribute name passed to `del` was lowercase, there was no issue, even if it had originally been created with mixed case.

Here's a little more detail on Evennia and my system.

```
$ evennia --version

    Evennia 0.8.0 (rev dc904435) (rev dc904435)
    OS: posix
    Python: 2.7.15rc1
    Twisted: 18.9.0
    Django: 1.11.17
```
```
$ uname -a
Linux Chiana 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -d
Description:    Linux Mint 19 Tara
```
