### ISSUE TITLE
"add a wiki" issue

### ISSUE THREAD

**Issue by MarcoSteffens** [evennia/evennia#1795]
I have tried to add a wiki as described in the dokumentation. After the final "evennia migrate" i get the following error:
```
evennia|docker /usr/src/game/MyMUD $ evennia migrate
Traceback (most recent call last):
  File "/usr/bin/evennia", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/usr/src/evennia/bin/unix/evennia", line 10, in <module>
    main()
  File "/usr/src/evennia/evennia/server/evennia_launcher.py", line 2129, in main
    init_game_directory(CURRENT_DIR, check_db=check_db, need_gamedir=need_gamedir)
  File "/usr/src/evennia/evennia/server/evennia_launcher.py", line 1690, in init_game_directory
    django.setup()
  File "/usr/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/usr/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/wiki/models/__init__.py", line 5, in <module>
    from .article import *  # noqa
  File "/usr/lib/python2.7/site-packages/wiki/models/article.py", line 91
    yield from obj.content_object.get_ancestors()
             ^
SyntaxError: invalid syntax
```
(With the latest official docker image.)

**Comment by vincent-lg** [comment]
It seems you get a syntax error due to wrong Python version.  I assume the latest Docker image is still in Python 2.7.  It is quite possible than django-wiki has discontinued their Python 2.x maintenance, as the `yield from` syntax is new in Python 3.3.  In other words, if this is a problem due to maintenance of django-wiki, this will work once Evennia 0.9 (on Python 3.5+) is ready.

**Comment by Griatch** [comment]
Yes, this looks to be a python versioning issue. Closing this for now, we can reopen if some other cause shows up (if so, just reply in this thread).
