### ISSUE TITLE
Test Error from Twisted

### ISSUE THREAD

**Issue by chason** [evennia/evennia#1830]
#### Brief summary of issue / Description of requested feature:
When running Evennia's tests, an error is raised by Twisted. I first noticed it when running `evennia test evennia.contrib` but a similar issue occurs in `evennia test evennia` although it doesn't raise an Error

#### Steps to reproduce the issue / Reasons for adding feature:

1. Run `evennia test evennia.contrib` or `evennia test evennia` I've included the output for both below

#### Error output / Expected result of feature

```
(venv3) [chason@正宗:~/projects/evennia/mygame] [develop]$ evennia test evennia

    TESTING: Using Evennia's default settings file (evennia.settings_default).
    (use 'evennia test --settings settings.py .' to run only your custom game tests)
    
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.......................................................................................................................................................................................................................................................................................................................................................................................................................................................
149 static files copied to '/Users/chason/projects/evennia/mygame/web/static', 1 unmodified.
.................................
----------------------------------------------------------------------
Ran 472 tests in 177.256s

OK
Destroying test database for alias 'default'...
Unhandled error in Deferred:

Traceback (most recent call last):
Failure: twisted.internet.defer.CancelledError: 

(venv3) [chason@正宗:~/projects/evennia/mygame] [develop]$ evennia test evennia.contrib

    TESTING: Using Evennia's default settings file (evennia.settings_default).
    (use 'evennia test --settings settings.py .' to run only your custom game tests)
    
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.........................................................................................................................E
======================================================================
ERROR: runTest (twisted.trial._asynctest.TestCase)
runTest
----------------------------------------------------------------------
twisted.trial.util.DirtyReactorAggregateError: Reactor was unclean.
DelayedCalls: (set twisted.internet.base.DelayedCall.debug = True to debug)
<DelayedCall 0x10d573198 [1.4647390842437744s] called=0 cancelled=0 restart_scripts_after_flush()

traceback at creation: 

  File "/Users/chason/projects/evennia/venv3/bin/evennia", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
      File "/Users/chason/projects/evennia/bin/unix/evennia", line 10, in <module>
    main()
      File "/Users/chason/projects/evennia/evennia/server/evennia_launcher.py", line 2151, in main
    sys.exit(execute_from_command_line())
      File "/Users/chason/projects/evennia/venv3/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
      File "/Users/chason/projects/evennia/venv3/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/Users/chason/projects/evennia/venv3/lib/python3.7/site-packages/django/core/management/commands/test.py", line 26, in run_from_argv
    super().run_from_argv(argv)
      File "/Users/chason/projects/evennia/venv3/lib/python3.7/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
      File "/Users/chason/projects/evennia/venv3/lib/python3.7/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
      File "/Users/chason/projects/evennia/venv3/lib/python3.7/site-packages/django/core/management/commands/test.py", line 56, in handle
    failures = test_runner.run_tests(test_labels)
      File "/Users/chason/projects/evennia/venv3/lib/python3.7/site-packages/django/test/runner.py", line 606, in run_tests
    result = self.run_suite(suite)
      File "/Users/chason/projects/evennia/venv3/lib/python3.7/site-packages/django/test/runner.py", line 572, in run_suite
    return runner.run(suite)
      File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/runner.py", line 176, in run
    test(result)
      File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
      File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/suite.py", line 122, in run
    test(result)
      File "/Users/chason/projects/evennia/venv3/lib/python3.7/site-packages/django/test/testcases.py", line 206, in __call__
    super().__call__(result)
      File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 663, in __call__
    return self.run(*args, **kwds)
      File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 618, in run
    self.tearDown()
      File "/Users/chason/projects/evennia/evennia/contrib/tutorial_examples/tests.py", line 16, in tearDown
    super(TestBodyFunctions, self).tearDown()
      File "/Users/chason/projects/evennia/evennia/utils/test_resources.py", line 123, in tearDown
    flush_cache()
      File "/Users/chason/projects/evennia/evennia/utils/idmapper/models.py", line 482, in flush_cache
    cls.flush_instance_cache()
      File "/Users/chason/projects/evennia/evennia/utils/idmapper/models.py", line 333, in flush_instance_cache
    cls.__dbclass__.__instance_cache__ = dict((key, obj) for key, obj in cls.__dbclass__.__instance_cache__.items()
      File "/Users/chason/projects/evennia/evennia/utils/idmapper/models.py", line 334, in <genexpr>
    if not obj.at_idmapper_flush())
      File "/Users/chason/projects/evennia/evennia/scripts/scripts.py", line 422, in at_idmapper_flush
    reactor.callLater(2, restart_scripts_after_flush)
>

----------------------------------------------------------------------
Ran 122 tests in 64.720s

FAILED (errors=1)
Destroying test database for alias 'default'...
```

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
This occurs for me on both the `master` and `develop` branches (under py2 and py3 respectively).
OS is Mac OS X 10.14
both Python 2 and Python 3 are from fresh virtualenvs

**Comment by chason** [comment]
Funnily enough, I was able to stop the error from occurring by putting `time.sleep(1)` after the `self.script.stop()` in the [tests for the tutorial examples](https://github.com/evennia/evennia/blob/master/evennia/contrib/tutorial_examples/tests.py#L17), whose comment says that running it will stop the error I'm seeing above. It actually seems like that `self.script.stop()` method call isn't preventing the call at all. If I remove it entirely but keep the `time.sleep(1)` then the error still does not occur.
However, I'm not familiar enough with the Twisted framework to understand if this is a good solution, or whether its obscuring a deeper issue.

**Comment by Griatch** [comment]
Generally, adding `sleep(1)` is not recommended for any asynchrnonous framework; rather one should add an async equivalent if that's the case.

**Comment by Griatch** [comment]
Can't see this error in `develop` branch.

**Comment by Griatch** [comment]
Closing after merge into master.
