### ISSUE TITLE
Py3/develop - makemigrations failure, NoneType takes no arguments

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#1839]
#### Brief summary of issue / Description of requested feature:
Trying to create some custom models in either the "web" app or a new app altogether, but it seems to be impossible to complete making of migrations.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Create models.py in 'web', define some model (or create new app, define model in models.py)
2. `evennia makemigrations web` or `evennia makemigrations yournewapp`
3. Fail

#### Error output / Expected result of feature
```
Traceback (most recent call last):
  File "/home/ubuntu/workspace/EV3/bin/evennia", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/ubuntu/workspace/evennia/bin/unix/evennia", line 10, in <module>
    main()
  File "/home/ubuntu/workspace/evennia/evennia/server/evennia_launcher.py", line 2151, in main
    sys.exit(execute_from_command_line())
  File "/home/ubuntu/workspace/EV3/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/workspace/EV3/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/workspace/EV3/lib/python3.7/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/workspace/EV3/lib/python3.7/site-packages/django/core/management/base.py", line 350, in execute
    self.check()
  File "/home/ubuntu/workspace/EV3/lib/python3.7/site-packages/django/core/management/base.py", line 379, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/ubuntu/workspace/EV3/lib/python3.7/site-packages/django/core/management/base.py", line 366, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/ubuntu/workspace/EV3/lib/python3.7/site-packages/django/core/checks/registry.py", line 71, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/ubuntu/workspace/EV3/lib/python3.7/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/home/ubuntu/workspace/EV3/lib/python3.7/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/home/ubuntu/workspace/EV3/lib/python3.7/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ubuntu/workspace/EV3/lib/python3.7/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/ubuntu/workspace/EV3/lib/python3.7/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ubuntu/workspace/EV3/lib/python3.7/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/ubuntu/workspace/EV3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/workspace/monarch/web/urls.py", line 10, in <module>
    from evennia.web.urls import urlpatterns
  File "/home/ubuntu/workspace/evennia/evennia/web/urls.py", line 17, in <module>
    url(r'^', include('evennia.web.website.urls')),  # , namespace='website', app_name='website')),
  File "/home/ubuntu/workspace/EV3/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/ubuntu/workspace/EV3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/ubuntu/workspace/evennia/evennia/web/website/urls.py", line 9, in <module>
    from evennia.web.website import views as website_views
  File "/home/ubuntu/workspace/evennia/evennia/web/website/views.py", line 29, in <module>
    from evennia.web.website import forms as website_forms
  File "/home/ubuntu/workspace/evennia/evennia/web/website/forms.py", line 35, in <module>
    class AccountForm(UserCreationForm):
  File "/home/ubuntu/workspace/evennia/evennia/web/website/forms.py", line 43, in AccountForm
    class Meta:
  File "/home/ubuntu/workspace/evennia/evennia/web/website/forms.py", line 50, in Meta
    model = class_from_module(settings.BASE_ACCOUNT_TYPECLASS)
  File "/home/ubuntu/workspace/evennia/evennia/utils/utils.py", line 1460, in class_from_module
    mod = import_module(testpath, package='evennia')
  File "/home/ubuntu/workspace/EV3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/ubuntu/workspace/monarch/typeclasses/accounts.py", line 28, in <module>
    class Account(DefaultAccount):
TypeError: NoneType takes no arguments
```

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
```
Python 3.7.3 (default, Mar 26 2019, 01:59:45) 
[GCC 5.4.0 20160609] on linux
>>> import django
>>> django.get_version()
'2.1.8'

--------------------------- Evennia ---
monarch Portal 0.9.0-dev (rev 47e06be)
    external ports:
        telnet: 4000
        webserver-proxy: 4001
        webclient-websocket: 4002
    internal_ports (to Server):
        webserver: 4005
        amp: 4006

monarch Server 0.9.0-dev (rev 47e06be)
    internal ports (to Portal):
        webserver: 4005
        amp : 4006
```

I've taken a few shots at this but have no idea where the problem lies.

Thought I saw someone somewhere saying *not* to run makemigrations on the current dev branch but wasn't sure to what scope that applied (and can't find that warning again to verify).

**Comment by Griatch** [comment]
There were some changes to the launcher in develop to make more django-commands and their args pass through unaffected. Without having investigated, it could be that the launcher simply does not know to specifically initialize evennia when seeing the `makemigration` django command.

**Comment by strikaco** [comment]
@Griatch Good to know, thanks. 

This problem also seems to impact custom management commands.

**Comment by Griatch** [comment]
Resolved in develop now. Closing.
