### ISSUE TITLE
"AttributeError: 'RetDefault' object has no attribute 'access'" on empty attribute sets

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#1866]
#### Brief summary of issue / Description of requested feature:
When no attributes are defined on an object, an AttributeError will be raised when a `get()` request for all attributes accessible by a caller is made.

#### Steps to reproduce the issue / Reasons for adding feature:

````
from evennia.utils.test_resources import EvenniaTest

class AttributesTest(EvenniaTest):
    
    def test_get_all_when_unset(self):
        # Get all attributes of char2 visible by char1 as list (none are set)
        result = self.char2.attributes.get(accessing_obj=self.char1, return_list=True)
        # This will raise an exception instead of returning a list
        self.assertEqual(result, [])
        
        # Get all attributes of char2 visible by char1 (none are set)
        result = self.char2.attributes.get(accessing_obj=self.char1)
        
        # This will raise an exception instead of returning None
        self.assertEqual(result, None)
        
    def test_get_all_when_set(self):
        # Add a visible attr to char2
        self.char2.attributes.add('name', 'bob', lockstring='attrread:all()')
        
        # Get all attributes of char2 visible by char1 (one is set)
        result = self.char2.attributes.get(accessing_obj=self.char1)
        self.assertEqual(result, 'bob')
        
        result = self.char2.attributes.get(accessing_obj=self.char1, return_list=True)
        self.assertEqual(result, ['bob'])
````

#### Error output / Expected result of feature
````
======================================================================
ERROR: test_get_all_when_unset (typeclasses.tests.AttributesTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/workspace/demogame/typeclasses/tests.py", line 7, in test_get_all_when_unset
    result = self.char2.attributes.get(accessing_obj=self.char1, return_list=True)
  File "/home/ubuntu/workspace/evennia/evennia/typeclasses/attributes.py", line 458, in get
    ret = [attr for attr in ret if attr.access(accessing_obj,
  File "/home/ubuntu/workspace/evennia/evennia/typeclasses/attributes.py", line 458, in <listcomp>
    ret = [attr for attr in ret if attr.access(accessing_obj,
AttributeError: 'RetDefault' object has no attribute 'access'

----------------------------------------------------------------------
````

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
This can be worked around by calling `all()` instead, but any category filtering needs to be done manually then.

**Comment by Griatch** [comment]
Fixed. I also refactored so that when using `return_list=True` on an object with no Attributes, the return is `[]` rather than `[None]`. For now I'll won't do any more API changes to this, but for `develop` branch later, this and other similar handlers should change to always return lists.
