### ISSUE TITLE
Add support for shell_plus --notebook in evennia when django_extensions is installed

### ISSUE THREAD

**Issue by bubthegreat** [evennia/evennia#1874]
#### Brief summary of issue / Description of requested feature:
I saw that we have evennia shell capability, but I've found it significantly easier to develop in ipython notebooks (jupyter) via django shell_plus?

#### Steps to reproduce the issue / Reasons for adding feature:

1. Try and run a shell_plus --notebook through evennia passthrough
2. Error raised

#### Error output / Expected result of feature

```
(evenv) PS C:\Users\mtaylor\Development\kbk> evennia shell_plus --notebook
Traceback (most recent call last):
  File "c:\users\mtaylor\development\evennia\evenv\Scripts\evennia_launcher.py", line 17, in <module>
    main()
  File "c:\users\mtaylor\development\evennia\evenv\Lib\site-packages\evennia\server\evennia_launcher.py", line 2172, in main
    sys.exit(execute_from_command_line())
  File "c:\users\mtaylor\development\evennia\evenv\Lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "c:\users\mtaylor\development\evennia\evenv\Lib\site-packages\django\core\management\__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "c:\users\mtaylor\development\evennia\evenv\Lib\site-packages\django_extensions\management\commands\shell_plus.py", line 117, in run_from_argv
    return super(Command, self).run_from_argv(argv)
  File "c:\users\mtaylor\development\evennia\evenv\Lib\site-packages\django\core\management\base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "c:\users\mtaylor\development\evennia\evenv\Lib\site-packages\django\core\management\base.py", line 350, in execute
    self.check()
  File "c:\users\mtaylor\development\evennia\evenv\Lib\site-packages\django\core\management\base.py", line 379, in check
    include_deployment_checks=include_deployment_checks,
  File "c:\users\mtaylor\development\evennia\evenv\Lib\site-packages\django\core\management\base.py", line 366, in _run_checks
    return checks.run_checks(**kwargs)
  File "c:\users\mtaylor\development\evennia\evenv\Lib\site-packages\django\core\checks\registry.py", line 71, in run_checks
    new_errors = check(app_configs=app_configs)
  File "c:\users\mtaylor\development\evennia\evenv\Lib\site-packages\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "c:\users\mtaylor\development\evennia\evenv\Lib\site-packages\django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "c:\users\mtaylor\development\evennia\evenv\Lib\site-packages\django\urls\resolvers.py", line 396, in check
    for pattern in self.url_patterns:
  File "c:\users\mtaylor\development\evennia\evenv\Lib\site-packages\django\utils\functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "c:\users\mtaylor\development\evennia\evenv\Lib\site-packages\django\urls\resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "c:\users\mtaylor\development\evennia\evenv\Lib\site-packages\django\utils\functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "c:\users\mtaylor\development\evennia\evenv\Lib\site-packages\django\urls\resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Program Files\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\mtaylor\Development\kbk\web\urls.py", line 10, in <module>
    from evennia.web.urls import urlpatterns
  File "c:\users\mtaylor\development\evennia\evenv\Lib\site-packages\evennia\web\urls.py", line 17, in <module>
    url(r'^', include('evennia.web.website.urls')),  # , namespace='website', app_name='website')),
  File "c:\users\mtaylor\development\evennia\evenv\Lib\site-packages\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Program Files\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\users\mtaylor\development\evennia\evenv\Lib\site-packages\evennia\web\website\urls.py", line 9, in <module>
    from evennia.web.website import views as website_views
  File "c:\users\mtaylor\development\evennia\evenv\Lib\site-packages\evennia\web\website\views.py", line 29, in <module>
    from evennia.web.website import forms as website_forms
  File "c:\users\mtaylor\development\evennia\evenv\Lib\site-packages\evennia\web\website\forms.py", line 35, in <module>
    class AccountForm(UserCreationForm):
  File "c:\users\mtaylor\development\evennia\evenv\Lib\site-packages\evennia\web\website\forms.py", line 43, in AccountForm
    class Meta:
  File "c:\users\mtaylor\development\evennia\evenv\Lib\site-packages\evennia\web\website\forms.py", line 50, in Meta
    model = class_from_module(settings.BASE_ACCOUNT_TYPECLASS)
  File "c:\users\mtaylor\development\evennia\evenv\Lib\site-packages\evennia\utils\utils.py", line 1474, in class_from_module
    mod = import_module(testpath, package='evennia')
  File "C:\Program Files\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\mtaylor\Development\kbk\typeclasses\accounts.py", line 28, in <module>
    class Account(DefaultAccount):
TypeError: NoneType takes no arguments```

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
It looks like we're overriding some things to pass them through to the shell (Likely preloading some of the django settings customized for evennia) but the things we override are expecting no arguments, and error because we pass the --notebook argument into whatever is doing that loading.

**Comment by bubthegreat** [comment]
I managed to get a bit farther by modifying the evennia_launcher a little bit:

1. I added django_extensions to my virtualenv so it would be available
2. I added the 'shell_plus' command to the list of inputs that sets check_db to True

I'm still getting stuck - when I try and import any of the typeclasses, it throws an error that a NoneType is not callable - I'm hazarding a guess that somewhere the caller object gets passed in - but I don't see an obvious entrypoint that I can use to either:

1. Create a caller that would let me import the objects in the notebook
2. Pass the caller to the notebook the way it seems to be passed with the shell command

Alternatively, I could be completely off base in that guess, and it's something completely different.  Is there somewhere I can look for how to mimic a caller, or something I'm not understanding about how the launcher passes it's state to the ipython shell that I can look at to get this working?

**Comment by Griatch** [comment]
n error of `NoneType is not callable` is usually because some resource is accessed before the `evennia.__init__.init()` call has been made so as to populate the api wrapper. Before that happens, all shortcuts in the package are `None`.

**Comment by Griatch** [comment]
@bubthegreat I don't know if you are still working on this; but I'm a but unsure what more info you need ... If you examine the evennia_launcher you will see the points where Evennia itself (or rather the flat API) is initialized - you see that `None` error because you are trying to run things before that initialization has happened. 

    import evennia
    evennia._init() 

will initialize the flat API, but I'm not 100% sure it will fix your issue - I don't use jupyter notebooks.

**Comment by TehomCD** [comment]
Maybe try `SHELL_PLUS_PRE_IMPORTS` on a file that has the evennia setup called?

**Comment by Griatch** [comment]
This seems well and good dead by now. Closing. Feel free to comment and I can re-open if this is still being worked on.
