### ISSUE TITLE
Launcher suppressing make/migration errors, returning misleading tracebacks

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#1941]
#### Brief summary of issue / Description of requested feature:
I'm creating a custom app and forgot to assign a `max_length` to a `CharField`. 

Evennia let `makemigrations` pass with this invalid instruction (possibly swallowing errors here too), and when I go to perform the migration itself I get a complex traceback that does not draw attention to the actual issue.

#### Error output / Expected result of feature
```
(MON) ubuntu@ip-172-31-18-199:~/workspace/monarch$ evennia migrate parsing

    NOTE: Django 2.2.5 found. This is newer than Evennia's
    recommended version (2.2.4). It might work, but may be new
    enough to not be fully tested yet. Report any issues.
    
Operations to perform:
  Apply all migrations: parsing
Running migrations:
  Applying parsing.0001_initial...Traceback (most recent call last):
  File "/home/ubuntu/workspace/MON/lib/python3.7/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/home/ubuntu/workspace/MON/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 381, in execute
    return Database.Cursor.execute(self, query)
sqlite3.OperationalError: near "None": syntax error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/workspace/MON/bin/evennia", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/ubuntu/workspace/evennia/bin/unix/evennia", line 10, in <module>
    main()
  File "/home/ubuntu/workspace/evennia/evennia/server/evennia_launcher.py", line 2174, in main
    django.core.management.call_command(*([option] + unknown_args))
  File "/home/ubuntu/workspace/MON/lib/python3.7/site-packages/django/core/management/__init__.py", line 148, in call_command
    return command.execute(*args, **defaults)
  File "/home/ubuntu/workspace/MON/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/workspace/MON/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/ubuntu/workspace/MON/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/home/ubuntu/workspace/MON/lib/python3.7/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/ubuntu/workspace/MON/lib/python3.7/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/ubuntu/workspace/MON/lib/python3.7/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/ubuntu/workspace/MON/lib/python3.7/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/ubuntu/workspace/MON/lib/python3.7/site-packages/django/db/migrations/operations/models.py", line 92, in database_forwards
    schema_editor.create_model(model)
  File "/home/ubuntu/workspace/MON/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 307, in create_model
    self.execute(sql, params or None)
  File "/home/ubuntu/workspace/MON/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 137, in execute
    cursor.execute(sql, params)
  File "/home/ubuntu/workspace/MON/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/home/ubuntu/workspace/MON/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/ubuntu/workspace/MON/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/ubuntu/workspace/MON/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ubuntu/workspace/MON/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ubuntu/workspace/MON/lib/python3.7/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/home/ubuntu/workspace/MON/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 381, in execute
    return Database.Cursor.execute(self, query)
django.db.utils.OperationalError: near "None": syntax error
```

...whereas a normal Django project returns:

```
(MON) ubuntu@ip-172-31-18-199:~/workspace/demodj$ python manage.py makemigrations
SystemCheckError: System check identified some issues:

ERRORS:
parsing.Application.value: (fields.E120) CharFields must define a 'max_length' attribute.
```

**Comment by Griatch** [comment]
All the `evennia_launcher` does differently is that it sends `migrate` and `makemigration` into the `django.core.management.call_command` explicitly, which is supposedly what vanilla Django does too. Maybe the default uses some other default argument or runs some sort of validator before continuing?

**Comment by Griatch** [comment]
It seems the `call_command` makes assumptions about whether to run migration checks or not. This was not visible until actually reading the Django command management code. I changed the way the launcher pass-throughs the `migrate` and `makemigrate`, so this should use the full checks now, except for the initial migration (when the db is first created) - this case is special since Evennia itself must initialize to run checks and this it  cannot do until the database is in place.
