### ISSUE TITLE
[BUG] TagHandler - AttributeError: `'int' object has no attribute 'strip'`

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#1949]
#### Describe the bug
There is some inconsistency with the way the TagHandler manages integer-ish values. 

Sometimes it works, sometimes it doesn't, it appears to depend on the specific method used and the pre-casting of the integer in question.

#### To Reproduce
```
from evennia.prototypes.spawner import spawn        

class SpawnerAttributesTest(EvenniaTest):
    
    def setUp(self):
        super().setUp()
        
        # Generic example object
        # Extraneous attributes related to other tests; please ignore
        self.prototype = {
            'key': 'bob',
            'age': 56,
            'attrs': (
                ('favorite_flavor', ['vanilla', 'swirl'], 'ice_cream_prefs', None),
            ),
            'tags': [
                ('happy', 'mood', ''),
            ]
        }
        
    def test_numeric_tags(self):
        "Check if tags consisting of numeric values are allowed."
        # Spawn a normal object and add the tag as str via the TagHandler
        obj = spawn(self.prototype)[0]
        self.assertTrue(obj)
        obj.tags.add('10467', category='zip')
        self.assertTrue('10467' in obj.tags.all(), "Stringified integer was not added to tags via tags.add method.")
        
        # Do the same with a numeric tag cast as int
        obj = spawn(self.prototype)[0]
        self.assertTrue(obj)
        obj.tags.add(10467, category='zip')
        self.assertTrue('10467' in obj.tags.all(), "Integer was not added to tags via tags.add method.")
        
        # Try creating numeric tag using spawner workflow both cast as int and str
        new = {k:v for k,v in self.prototype.items()}
        new['tags'].extend([
            ('10467', 'zip', '10467'),
            (10468, 'zip', 10468),
        ])
        obj = spawn(new)[0]
        self.assertTrue(obj)
        self.assertTrue('10467' in obj.tags.all(), "Stringified integer was not added to tags when using spawner.")
        self.assertTrue('10468' in obj.tags.all(), "Integer was not added to tags when using spawner.")
        
```
#### Traceback
```
======================================================================
ERROR: test_numeric_tags (typeclasses.tests.SpawnerAttributesTest)
Check if tags consisting of numeric values are allowed.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/workspace/demogame/typeclasses/tests.py", line 75, in test_numeric_tags
    obj = spawn(new)[0]
  File "/home/ubuntu/workspace/evennia/evennia/prototypes/spawner.py", line 794, in spawn
    return batch_create_object(*objsparams)
  File "/home/ubuntu/workspace/evennia/evennia/prototypes/spawner.py", line 649, in batch_create_object
    obj.save()
  File "/home/ubuntu/workspace/evennia/evennia/utils/idmapper/models.py", line 403, in save
    super().save(*args, **kwargs)
  File "/home/ubuntu/workspace/EV37/lib/python3.7/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/ubuntu/workspace/EV37/lib/python3.7/site-packages/django/db/models/base.py", line 790, in save_base
    update_fields=update_fields, raw=raw, using=using,
  File "/home/ubuntu/workspace/EV37/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/home/ubuntu/workspace/EV37/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/home/ubuntu/workspace/evennia/evennia/typeclasses/models.py", line 71, in call_at_first_save
    instance.at_first_save()
  File "/home/ubuntu/workspace/evennia/evennia/objects/objects.py", line 1105, in at_first_save
    self.tags.batch_add(*cdict["tags"])
  File "/home/ubuntu/workspace/evennia/evennia/typeclasses/tags.py", line 415, in batch_add
    self.add(tag=key, category=category, data=data.get(category, None))
  File "/home/ubuntu/workspace/evennia/evennia/typeclasses/tags.py", line 260, in add
    tagstr = tagstr.strip().lower()
AttributeError: 'int' object has no attribute 'strip'
```

#### Environment, Evennia version, OS etc
Evennia 0.9.0 (rev c6aa943)

#### Additional context
https://github.com/evennia/evennia/blob/541a6fa85525f0c40d47cd0074149ba49b9b60c9/evennia/typeclasses/tags.py#L234-L261

The `add` method never does any casting or validation of the `tag` value before attempting to perform a `strip()` on it. Looking at the code the `category` value is subject to the same issue.

Modifying these two lines does resolve the errors in the test above, though I have not run the entire core suite:
```
tagstr = str(tagstr).strip().lower()
category = str(category).strip().lower() if category else category
```

**Comment by Griatch** [comment]
Closed by #1957.
