### ISSUE TITLE
[BUG] `Msg` objects not rendering correctly with external sender

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#1982]
#### Describe the bug
The `Msg` object seems to make a presumption that senders will always have a `key` attribute when rendering the object for display.

#### To Reproduce
```
def test_render_external_sender(self):
        from evennia.utils.create import create_message
        msg = create_message('peewee herman', 'heh-heh!', header='mail time!')
        print(msg)
```

```
Traceback (most recent call last):
  File "/home/ubuntu/workspace/demogame/world/objects/tests.py", line 13, in test_render_external_sender
    print(msg)
  File "/home/ubuntu/workspace/evennia2/evennia/comms/models.py", line 403, in __str__
    senders = ",".join(obj.key for obj in self.senders)
  File "/home/ubuntu/workspace/evennia2/evennia/comms/models.py", line 403, in <genexpr>
    senders = ",".join(obj.key for obj in self.senders)
AttributeError: 'str' object has no attribute 'key'
```

#### Expected behavior
```
peewee herman->: heh-heh!
```
#### Environment, Evennia version, OS etc
```
Evennia 0.9.0 (rev ff7b739) (rev ff7b739)
    OS: posix
    Python: 3.7.5
    Twisted: 19.7.0
    Django: 2.2.6
```

**Comment by Griatch** [comment]
This looks like a trivial fix to do for someone who wants the experience of helping out. :smile:
