### ISSUE TITLE
[BUG] "builtins.RuntimeError: dictionary changed size during iteration" error when using "IDLE_TIMEOUT" feature

### ISSUE THREAD

**Issue by GulliblePsychologist** [evennia/evennia#1992]
#### Describe the bug
```
Unhandled Error
        Traceback (most recent call last):
          File "~/muddev/evenv/lib/python3.7/site-packages/twisted/internet/base.py", line 1283, in run
            self.mainLoop()
          File "~/muddev/evenv/lib/python3.7/site-packages/twisted/internet/base.py", line 1292, in mainLoop
            self.runUntilCurrent()
          File "~/muddev/evenv/lib/python3.7/site-packages/twisted/internet/base.py", line 913, in runUntilCurrent
            call.func(*call.args, **call.kw)
          File "~/muddev/evenv/lib/python3.7/site-packages/twisted/internet/task.py", line 239, in __call__
            d = defer.maybeDeferred(self.f, *self.a, **self.kw)
        --- <exception caught here> ---
          File "~/evenv/lib/python3.7/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
            result = f(*args, **kw)
          File "~/evennia/evennia/server/server.py", line 152, in _server_maintenance
            sess for sess in SESSIONS.values() if (now - sess.cmd_last) > _IDLE_TIMEOUT
          File "~/evennia/evennia/server/server.py", line 152, in <genexpr>
            sess for sess in SESSIONS.values() if (now - sess.cmd_last) > _IDLE_TIMEOUT
        builtins.RuntimeError: dictionary changed size during iteration
```

#### To Reproduce
1. Set an IDLE_TIMEOUT in server/conf/settings.py to a positive value.
2. Wait for a client to idle.
3. The first client to idle is kicked from the server. The error is then displayed. After that, the server maintenance loop no longer runs.

#### Expected behavior
Clients that have been idle for longer than the prescribed IDLE_TIMEOUT should be automatically disconnected from the server.

#### Environment, Evennia version, OS etc
```
$ evennia -v
Evennia 0.9.0 (rev 41365fdc) (rev 41365fdc)
    OS: posix
    Python: 3.7.5
    Twisted: 19.7.0
    Django: 2.2.6
```

#### Additional context
I have replaced the following line in server.py in the "_server_maintenance" function:

```sess for sess in SESSIONS.values() if (now - sess.cmd_last) > _IDLE_TIMEOUT```

with:

```sess for sess in list(SESSIONS.values()).copy() if (now - sess.cmd_last) > _IDLE_TIMEOUT```

**Comment by GulliblePsychologist** [comment]
This issue was closed in January, but I don't see any changes in `evennia/server/server.py` on line 155 in the current "develop" branch.

**Comment by Griatch** [comment]
@GulliblePsychologist Not sure what version of `develop` branch you have, but this is definitely addressed in upstream develop: https://github.com/evennia/evennia/blob/develop/evennia/server/server.py#L162
