### ISSUE TITLE
[Documentation] Quick Start step 4 assumes virtualenv/python3

### ISSUE THREAD

**Issue by spiralofhope** [evennia/evennia#2019]
#### Documentation issue

https://github.com/evennia/evennia/wiki/Getting-Started#quick-start

Step 4 is:

``` bash
virtualenv evenv
```

However for someone who has both python2 and python3 (For me, under Debian 10) this might default to python2 and fail.

#### Suggested change

``` bash
virtualenv --python='/usr/bin/python3' evenv
```

(`/usr/bin/python3.7` is also valid for me, but I figure `/usr/bin/python3` is best)

**Comment by spiralofhope** [comment]
Furthermore, this same step will fail unless the user uses a symlink-capable filesystem.  NTFS will not work:

```Using base prefix '/usr'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 357, in copyfile
    os.symlink(srcpath, dest)
PermissionError: [Errno 1] Operation not permitted: '/usr/lib/python3.7/config-3.7m-x86_64-linux-gnu' -> '/path/to/evennia/evenv/lib/python3.7/config-3.7m-x86_64-linux-gnu'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/virtualenv", line 11, in <module>
    load_entry_point('virtualenv==15.1.0', 'console_scripts', 'virtualenv')()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 724, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 950, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 1181, in install_python
    copyfile(join(stdlib_dir, fn), join(lib_dir, fn), symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 360, in copyfile
    copyfileordir(src, dest, symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 335, in copyfileordir
    shutil.copytree(src, dest, symlink)
  File "/usr/lib/python3.7/shutil.py", line 365, in copytree
    raise Error(errors)
shutil.Error: [('/usr/lib/python3.7/config-3.7m-x86_64-linux-gnu/libpython3.7m.so', 'asfasfasfasf/evennia/evenv/lib/python3.7/config-3.7m-x86_64-linux-gnu/libpython3.7m.so', "[Errno 1] Operation not permitted: '../../x86_64-linux-gnu/libpython3.7m.so.1' -> '/path/to/evennia/evenv/lib/python3.7/config-3.7m-x86_64-linux-gnu/libpython3.7m.so'"), ('/usr/lib/python3.7/config-3.7m-x86_64-linux-gnu/libpython3.7.so', '/path/to/evennia/evenv/lib/python3.7/config-3.7m-x86_64-linux-gnu/libpython3.7.so', "[Errno 1] Operation not permitted: '../../x86_64-linux-gnu/libpython3.7m.so.1' -> '/path/to/evennia/evenv/lib/python3.7/config-3.7m-x86_64-linux-gnu/libpython3.7.so'")]
```

**Comment by Griatch** [comment]
Thanks for the feedback! But the quick-start is just the minimal common install instruction for all the various OS:es supported (the path `/usr/bin/python3` is not valid for Windows, for example). The use of `virtualenv -p /usr/bin/python3 evenv` is covered in the extended Linux install instructions and is where you should look if you have issues.

The NTFS error is a (very) special case that I've now added as a troubleshooting entry - it's certainly not common nor recommended for a Linux user to use NTFS ...
