### ISSUE TITLE
[BUG] Fatal error when using reload command

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#2028]
#### Describe the bug
Attempting to use the `@reload` command from in-game often produces a traceback of the webserver internal port being in-use that prevents the server from restarting, leaving the game dead.

```
20-01-18 17:21:03-05 [..] Server disconnected from the portal.
20-01-18 17:21:03-05 Main loop terminated.
20-01-18 17:21:03-05 Server Shut Down.
20-01-18 17:21:03-05 Loading /home/tehom/arx/evennia/evennia/server/server.py...
20-01-18 17:21:05-05 Loaded.
20-01-18 17:21:05-05 twistd 19.10.0 (/home/tehom/arx/arxvenv/bin/python 3.8.1) starting up.
20-01-18 17:21:05-05 reactor class: twisted.internet.epollreactor.EPollReactor.
20-01-18 17:21:05-05 Traceback (most recent call last):
20-01-18 17:21:05-05   File "/home/tehom/arx/arxvenv/lib/python3.8/site-packages/twisted/internet/tcp.py", line 1361, in startListening
20-01-18 17:21:05-05     skt.bind(addr)
20-01-18 17:21:05-05 OSError: [Errno 98] Address already in use
20-01-18 17:21:05-05
20-01-18 17:21:05-05 During handling of the above exception, another exception occurred:
20-01-18 17:21:05-05
20-01-18 17:21:05-05 Traceback (most recent call last):
20-01-18 17:21:05-05   File "/home/tehom/arx/arxvenv/bin/twistd", line 11, in <module>
20-01-18 17:21:05-05     load_entry_point('Twisted==19.10.0', 'console_scripts', 'twistd')()
20-01-18 17:21:05-05   File "/home/tehom/arx/arxvenv/lib/python3.8/site-packages/twisted/scripts/twistd.py", line 31, in run
20-01-18 17:21:05-05     app.run(runApp, ServerOptions)
20-01-18 17:21:05-05   File "/home/tehom/arx/arxvenv/lib/python3.8/site-packages/twisted/application/app.py", line 674, in run
20-01-18 17:21:05-05     runApp(config)
20-01-18 17:21:05-05   File "/home/tehom/arx/arxvenv/lib/python3.8/site-packages/twisted/scripts/twistd.py", line 25, in runApp
20-01-18 17:21:05-05     runner.run()
20-01-18 17:21:05-05   File "/home/tehom/arx/arxvenv/lib/python3.8/site-packages/twisted/application/app.py", line 385, in run
20-01-18 17:21:05-05     self.postApplication()
20-01-18 17:21:05-05   File "/home/tehom/arx/arxvenv/lib/python3.8/site-packages/twisted/scripts/_twistd_unix.py", line 254, in postApplication
20-01-18 17:21:05-05     self.startApplication(self.application)
20-01-18 17:21:05-05   File "/home/tehom/arx/arxvenv/lib/python3.8/site-packages/twisted/scripts/_twistd_unix.py", line 442, in startApplication
20-01-18 17:21:05-05     service.IService(application).privilegedStartService()
20-01-18 17:21:05-05   File "/home/tehom/arx/arxvenv/lib/python3.8/site-packages/twisted/application/service.py", line 283, in privilegedStartService
20-01-18 17:21:05-05     service.privilegedStartService()
20-01-18 17:21:05-05   File "/home/tehom/arx/arxvenv/lib/python3.8/site-packages/twisted/application/service.py", line 283, in privilegedStartService
20-01-18 17:21:05-05     service.privilegedStartService()
20-01-18 17:21:05-05   File "/home/tehom/arx/arxvenv/lib/python3.8/site-packages/twisted/application/internet.py", line 114, in privilegedStartService
20-01-18 17:21:05-05     self._port = self._getPort()
20-01-18 17:21:05-05   File "/home/tehom/arx/arxvenv/lib/python3.8/site-packages/twisted/application/internet.py", line 141, in _getPort
20-01-18 17:21:05-05     return getattr(_maybeGlobalReactor(self.reactor),
20-01-18 17:21:05-05   File "/home/tehom/arx/arxvenv/lib/python3.8/site-packages/twisted/internet/posixbase.py", line 495, in listenTCP
20-01-18 17:21:05-05     p.startListening()
20-01-18 17:21:05-05   File "/home/tehom/arx/arxvenv/lib/python3.8/site-packages/twisted/internet/tcp.py", line 1363, in startListening
20-01-18 17:21:05-05     raise CannotListenError(self.interface, self.port, le)
20-01-18 17:21:05-05 twisted.internet.error.CannotListenError: Couldn't listen on 127.0.0.1:5001: [Errno 98] Address already in use.
```

#### To Reproduce
1. Use `@reload`
2. Sometimes the above happens randomly
3. See error

#### Expected behavior
The game to restart normally. Using `evennia reload` from shell works just fine.

#### Environment, Evennia version, OS etc
Evennia version: 0.9.0 (rev 9649295)
         OS: posix
         Python: 3.8.1
         Twisted: 19.10.0
         Django: 2.2.9

#### Additional context
WEBSERVER_PORTAL_INTERNAL is set to 5001. So far that's the only 'port in use' issue we've come across.

**Comment by Griatch** [comment]
This is not reproducible on a vanilla system (I've never seen it and as you can imagine,  I reload _a lot_ during development). So this seems most likely to be some sort of race condition due to load or database size.

**Comment by TehomCD** [comment]
Yeah, I was assuming it was something like load causing the webserver to shut down cleanly much slower than it expects so the port is still occupied, but that's just a shot in the dark.

**Comment by GulliblePsychologist** [comment]
I have seen this happen on my production server. `evennia reload` would hang on "Server reloading..." and this error would appear in the logs.

Unfortunately, it seems to be an intermittent problem.

**Comment by TehomCD** [comment]
Just to confirm this happens on the commandline as well if you start it there:
```
Server reloading...

^C(arxvenv) tehom@arxhost:~/arx/arx$ evennia reload

    NOTE: Django 2.2.9 found. This is newer than Evennia's
    recommended version (2.2.5). It might work, but may be new
    enough to not be fully tested yet. Report any issues.

Server down. Re-starting ...
... Server re-started.
```
So the behavior is try to restart, hangs/stops, restart again and it works.

**Comment by Griatch** [comment]
Hm, I wonder if one could insert a strategic `sleep()` in one of the webserver's shutdown hooks to try to replicate this reliably?

**Comment by Griatch** [comment]
Hm, I wonder if one could insert a strategic `sleep()` in one of the webserver's shutdown hooks to try to replicate this reliably?

**Comment by TehomCD** [comment]
That might be a good way to go about it. I did have it fail to restart on the first re-try once, when I did a reload, then attempted to restart it from the console 6 seconds later. So apparently sometimes the port can stay occupied after shutdown is initiated for at least 6 seconds.

**Comment by TehomCD** [comment]
I should mention that I have a stage server that's a duplicate environment aside from having almost no one connected to it - uses a copy of the same database, etc. It's never had the server restart issue. So I'd speculate it's purely a matter of load/activity, not anything related to the db.

**Comment by strikaco** [comment]
If it's at all related, I also often experience the same issue, on a different port, but under the same circumstances:

```
20-01-31 18:53:55 twisted.internet.error.CannotListenError: Couldn't listen on 127.0.0.1:4005: [Errno 98] Address already in use.
```

If the `@reload` is initiated in-game, it will hang and require me to drop to the shell to do a manual `evennia restart` to force it. 5-6 seconds does seem to be the average length of time required to wait for release of the socket, and database load is usually heaviest preceding these issues.

Sometimes this can be manually replicated from the command line using `evennia stop && evennia restart` to make both commands fire in quick succession, but the precursor usually needs to be any or all of a blocking script, async call or heavy load.

It is possible at all to put in at least a cooldown/retry mechanism that, upon socket error, wait 5 seconds, retry, wait 10 more seconds, retry, then fail? I know nothing of the Twisted internals.

**Comment by TehomCD** [comment]
Yeah, it's the same error. The WSGIWebServer on that port is failing to stop listening on the port while the rest of the reactor shuts down. Code where it starts listening:

https://github.com/evennia/evennia/blob/master/evennia/server/server.py#L685

I'm not sure how to tell it's still in use: the impression I got is that once you see 'Main loop terminated'/'Server shut down' that the process is supposed to be gone, but it's clearly still in the process of shutting down.

**Comment by Griatch** [comment]
I cannot reproduce this at all, which makes it hard to devise a fix. I tried make a command with `time.sleep(30)` in it. This locks the reload alright, but the Portal simply waits until the sleep time is passed and then reloads correctly ... it never leads to the port being occupied since the Portal knows not to try again until the Server has reported it has closed. 

I suspect the way to replicate this is to investigate the callbacks in `evennia/server/portal/amp_server.py` and insert a `sleep()` in a way so as to trick the portal the server has actually closed down when it has not. It's unclear to me just how well this would mimic reality though and how the situation actually occurs in the wild.

**Comment by TehomCD** [comment]
It's infuriating because it happens literally every time on my prod environment now. It clearly has to be tied to activity in some way, and the port that refuses to release is the webserver, but as to the precise cause, I have no idea.

It might be better to have some re-try mechanism on startup for an occupied port, maybe. That wouldn't solve the underlying cause but would probably function as a solution, and make the entire process less brittle.

**Comment by GulliblePsychologist** [comment]
I can reproduce this reliably on my production server. When I've left the server running for a couple of hours and then reload, it'll always produce this error and I have to reload it again. If it's within the span of a couple of hours the server reloads fine.

The RAM usage of my server jumps and can easily use 5+ GB, so I suspect it's taking a little longer to unload everything but the reload process decides to boot up a new `server.py` process too early.

The obvious solution IMO is to catch this error and simply retry after a couple of seconds for x amount of times.

**Comment by Griatch** [comment]
Alas, I've never been able to reliably reproduce this. Maybe I need to synthetically build a very large database to test with then. 

@GulliblePsychologist 
What's your setting for `IDMAPPER_CACHE_MAXSIZE`?

**Comment by GulliblePsychologist** [comment]
```
IDMAPPER_CACHE_MAXSIZE = 2048
```

**Comment by Griatch** [comment]
@TehomCD I've spent most of today trying to reproduce this and cannot :disappointed: I can introduce pauses in the start of the server and/or webserver that does give the `CannotListenError`, but every time this is a transient error - whenever the component catches up out the server restarts normally. So no fatal error at all for me, just one that gets a bit spammy in the log. This is with Python 3.10 and Twisted 21.7 on `develop` branch, but I don't think there should be much different for something like this. 

As far as I can tell, the `CannotListenError` is not really something I can catch either, because it's thrown by the main `twistd` executor when it initates the server - the exception never goes through any evennia code and so far I've not found a good way to plug in an error handler because this error is raised at the OS level. 

Unless someone can come up with a test to reliably reproduce the 'fatal' error for this, I don't know that there is something I can do further to investigate this sadly. :confused:

**Comment by InspectorCaracal** [comment]
I don't have a lot of info to present since I wasn't expecting this to happen at all, but - I just ran into this bug today for the first time when attempting to reload my dev server. My dev server is very small, not even 200 dbrefs used, it had been sitting idle all weekend and while I was logged in on my one account when I tried to reload, nothing was actually happening in the game. So whatever is causing this, it's clearly _not_ high load.

Unfortunately there's nothing notable in any of my logs and it's not repeating the error, so that's all the information I have to offer.

**Comment by volundmush** [comment]
I suggest altering the reload process so that it uses os.exec() on the server side to re-launch itself after shutting down the reactor loop. This would ensure the Python interpreter reloads all modules, and, as long as all file handles are closed before doing so, is perfectly fine and will not leak resources. The portal can just keep trying to connect to the server.

**Comment by InspectorCaracal** [comment]
I've run into this issue again recently after I'd left my dev server running for a while - I usually shut it down when I'm done working, but I left it running without touching it for a few days on two different recent instances, and both times this happened.

With that, I've realized that the only change between the core object/code load *before* it started and *after* it started is that I added two tickers to my character class.

I don't know if it's only happened when there's been an idle character that didn't successfully time out, but I know that the *most recent* time, that was the case. I have a feeling that the server attempting to stop those two tickers is, for some reason, slowing things down enough to trigger this. (Which is concerning on its own but a separate thing I would need to verify.)

So, to reproduce locally, I would suggest trying putting a ticker on your Character class, logging in, and leaving it and the character idle for a few days before attempting a reload.

**Comment by ShardsDev** [comment]
I just hit this bug today too, at least I think it's the same one. Here's the traceback in case it helps:
|Portal| 2023-02-28 22:19:07 [..] Portal starting server ... 
|Portal| 2023-02-28 22:19:30 [EE] AMP Error from b'MsgPortal2Server': Traceback (most recent call last):
|Portal| 2023-02-28 22:19:30 [EE] --- <exception caught here> ---
|Portal| 2023-02-28 22:19:30 [EE]   File "/home/deej/muddev/evenv/lib/python3.11/site-packages/twisted/internet/defer.py", line 892, in _runCallbacks
|Portal| 2023-02-28 22:19:30 [EE]     current.result = callback(  # type: ignore[misc]
|Portal| 2023-02-28 22:19:30 [EE]   File "/home/deej/muddev/evenv/lib/python3.11/site-packages/twisted/protocols/amp.py", line 1946, in _massageError
|Portal| 2023-02-28 22:19:30 [EE]     error.trap(RemoteAmpError)
|Portal| 2023-02-28 22:19:30 [EE]   File "/home/deej/muddev/evenv/lib/python3.11/site-packages/twisted/python/failure.py", line 480, in trap
|Portal| 2023-02-28 22:19:30 [EE]     self.raiseException()
|Portal| 2023-02-28 22:19:30 [EE]   File "/home/deej/muddev/evenv/lib/python3.11/site-packages/twisted/python/failure.py", line 504, in raiseException
|Portal| 2023-02-28 22:19:30 [EE]     raise self.value.with_traceback(self.tb)
|Portal| 2023-02-28 22:19:30 [EE] twisted.protocols.amp.UnhandledCommand: (b'UNHANDLED', "Unhandled Command: b'MsgPortal2Server'")
|Portal| 2023-02-28 22:19:30 [EE]  (b'UNHANDLED', "Unhandled Command: b'MsgPortal2Server'")
2023-02-28 22:19:08 [EE]     self.postApplication()
2023-02-28 22:19:08 [EE]   File "/home/deej/muddev/evenv/lib/python3.11/site-packages/twisted/scripts/_twistd_unix.py", line 254, in postApplication
2023-02-28 22:19:08 [EE]     self.startApplication(self.application)
2023-02-28 22:19:08 [EE]   File "/home/deej/muddev/evenv/lib/python3.11/site-packages/twisted/scripts/_twistd_unix.py", line 444, in startApplication
2023-02-28 22:19:08 [EE]     service.IService(application).privilegedStartService()
2023-02-28 22:19:08 [EE]   File "/home/deej/muddev/evenv/lib/python3.11/site-packages/twisted/application/service.py", line 271, in privilegedStartService
2023-02-28 22:19:08 [EE]     service.privilegedStartService()
2023-02-28 22:19:08 [EE]   File "/home/deej/muddev/evenv/lib/python3.11/site-packages/twisted/application/service.py", line 271, in privilegedStartService
2023-02-28 22:19:08 [EE]     service.privilegedStartService()
2023-02-28 22:19:08 [EE]   File "/home/deej/muddev/evenv/lib/python3.11/site-packages/twisted/application/internet.py", line 115, in privilegedStartService
2023-02-28 22:19:08 [EE]     self._port = self._getPort()
2023-02-28 22:19:08 [EE]                  ^^^^^^^^^^^^^^^
2023-02-28 22:19:08 [EE]   File "/home/deej/muddev/evenv/lib/python3.11/site-packages/twisted/application/internet.py", line 139, in _getPort
2023-02-28 22:19:08 [EE]     return getattr(
2023-02-28 22:19:08 [EE]            ^^^^^^^^
2023-02-28 22:19:08 [EE]   File "/home/deej/muddev/evenv/lib/python3.11/site-packages/twisted/internet/posixbase.py", line 369, in listenTCP
2023-02-28 22:19:08 [EE]     p.startListening()
2023-02-28 22:19:08 [EE]   File "/home/deej/muddev/evenv/lib/python3.11/site-packages/twisted/internet/tcp.py", line 1336, in startListening
2023-02-28 22:19:08 [EE]     raise CannotListenError(self.interface, self.port, le)
2023-02-28 22:19:08 [EE] twisted.internet.error.CannotListenError: Couldn't listen on 127.0.0.1:4005: [Errno 98] Address already in use.

**Comment by ShardsDev** [comment]
Just to add to my traceback: I have 3 accounts, 2 characters, 9 rooms, 20 exits, 6 other objects, no triggers, no scripts. I do have paxboards installed, extended room, and discord integration. There are currently no bulletin boards created. Discord is integrated with 1 discord server channel and has been running without issues. It might be a slowness issue, but for sure it's not just a large db issue I don't think.

**Comment by InspectorCaracal** [comment]
I've got some additional anecdotal data to toss into this pile.

My current active game runs into this issue basically all the time, and it has for the past couple major versions of evennia and multiple minor versions in the middle. I've been completely unable to identify any reproducible causes, but I do have some interesting correlations.

First, my server setup:

- Server is a Debian Nanode - I think it's Debian 11, I'll check and edit that back in
- Evennia runs in a virtual environment of course, using python 3.11
- Database is relatively current mariadb

At least one other person reported having this taken frequently to them in Ubuntu. Can't remember if they were using sqlite or psql.

Now here's the interesting part I got recently. I've noted for a while this issue only crops up when the game is idle for a while - at least several hours. So I'd speculated it had something to do with memory caching, or session activity....

WELL. A couple weeks ago, I noticed the server wasn't having this issue any more. I was perplexed since I hadn't done anything new to it, but glad I didn't have to worry about it. Several days passed... and due to a separate lag issue, I discovered that there was in fact one thing different.

There was a looping script running.

This one script, which should not have still been running, was ticking every second, and this activity *alone* was enough to prevent this reload issue from occurring.

I killed the script, fixed the bug that caused it... and loo and behold, the reload issue came back within 48 hours.

So I can say with great certainty now that while I still don't know what causes this issue, it *requires* the server to have *not* been actively running code and/or accessing the database for a significant window of time *at some point* since the previous server restart.

**Comment by Griatch** [comment]
I have seen this now once, when testing PR #3510 , which has `delays()` in the inputfunc. I think it's the first time I've seen something like it on my dev machine. So that could be a venue towards investigating this, maybe.
