### ISSUE TITLE
[BUG] EvTable and panes

### ISSUE THREAD

**Issue by kaleara** [evennia/evennia#2102]
#### Describe the bug
Using a layout that has multiple panes and trying to send an EvTable to one of them gives a traceback. The table works just fine in Main and I can output text to the other pane, but when I attempt to send an EvTable it doesn't work.

#### To Reproduce
1. Create new pane in addition to Main on in webclient
2. Send EvTable to that pane using a tag
4. Portal Traceback

 Traceback (most recent call last):
   File "f:\repositories\evennia\evennia\server\portal\portalsessionhandler.py", line 454, in data_out
     getattr(session, funcname)(*cmdargs, **cmdkwargs)
   File "f:\repositories\evennia\evennia\server\portal\webclient.py", line 273, in send_text
     args[0] = parse_html(text, strip_ansi=nocolor)
   File "f:\repositories\evennia\evennia\utils\text2html.py", line 369, in parse_html
     return parser.parse(string, strip_ansi=strip_ansi)
   File "f:\repositories\evennia\evennia\utils\text2html.py", line 337, in parse
     text = parse_ansi(text, strip_ansi=strip_ansi, xterm256=True, mxp=True)
   File "f:\repositories\evennia\evennia\utils\ansi.py", line 479, in parse_ansi
    return parser.parse_ansi(string, strip_ansi=strip_ansi, xterm256=xterm256, mxp=mxp)
   File "f:\repositories\evennia\evennia\utils\ansi.py", line 412, in parse_ansi
     string = self.brightbg_sub.sub(self.sub_brightbg, string)
 TypeError: expected string or bytes-like object`

**Comment by strikaco** [comment]
Maybe dumb/irrelevant, but have you tried casting your table to `str` before sending?

**Comment by Griatch** [comment]
@kaleara As @strikaco points out, converting the EvTable to a string before sending it as a text entry would have resolved this issue. I have now added a line to force the conversion into a string at the Portal level.
