### ISSUE TITLE
[BUG] Issues with closing webclient

### ISSUE THREAD

**Issue by Griatch** [evennia/evennia#2197]
#### Describe the bug

Seen in evdemo log
```
20-09-16 23:03:40  |Portal| Timing out client: IPv4Address(type='TCP', host='XX.XX.XX.XX', port=XXXXX)  
(repeated 5 more times)
```
This appears pretty regularly in the log when the webclient is concerned. It's not always an unclean shutdown.

This was attached to this, much more rare error (probably after a user timed out/closed their browser window uncleanly):

```
20-09-16 23:06:27  |Portal| [::] Traceback (most recent call last):                                                                                                           
20-09-16 23:06:27  |Portal| [::]   File "/root/evdemo/evennia/evennia/server/portal/portalsessionhandler.py", line 454, in data_out                                           
20-09-16 23:06:27  |Portal| [::]     getattr(session, funcname)(*cmdargs, **cmdkwargs)                                                                                        
20-09-16 23:06:27  |Portal| [::]   File "/root/evdemo/evennia/evennia/server/portal/webclient.py", line 278, in send_text                                                     
20-09-16 23:06:27  |Portal| [::]     self.sendLine(json.dumps([cmd, args, kwargs]))                                                                                           
20-09-16 23:06:27  |Portal| [::]   File "/root/evdemo/evennia/evennia/server/portal/webclient.py", line 194, in sendLine                                                      
20-09-16 23:06:27  |Portal| [::]     return self.sendMessage(line.encode())                                                                                                   
20-09-16 23:06:27  |Portal| [::]   File "/root/evdemo/vienv/lib/python3.8/site-packages/autobahn/websocket/protocol.py", line 2216, in sendMessage                            
20-09-16 23:06:27  |Portal| [::]     raise Disconnected("Attempt to send on a closed protocol")                                                                               
20-09-16 23:06:27  |Portal| [::] autobahn.exception.Disconnected: Attempt to send on a closed protocol
```

#### To Reproduce

1. Unclear, but probably because of an unclean shutdown. The Timeout may possibly be benign (but should not log in that case). 
2. ...?
3. See error

#### Expected behavior

We should not have tracebacks from neither unclean browser-closing nor timeouts from the webclient. 

#### Environment, Evennia version, OS etc
Master branch 

#### Additional context
This requires more testing with the webclient.

**Comment by Griatch** [comment]
Added a fix for the closed-protocol traceback in f40ca6a7391851fae6a6419530a8b4. Will let it run on the demo for a while to see if it does fix it, since that's where the issue have shown up the most.
