### ISSUE TITLE
[BUG] Commands in nested CmdSets losing reference to parent/owner object

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2221]
#### Describe the bug
Commands in multi-nested CmdSets seem to lose their reference to their "parent" object (`self.obj`) when merged.

(Commands added to a single-level CmdSet work as expected.)

#### To Reproduce
Given a setup like so:
```
class Thing(Object):

    def at_object_creation(self, *args, **kwargs):
        super().at_object_creation(*args, **kwargs)
        self.cmdset.add(ActionsCmdSet, permanent=True)

class CmdEquip(Command):
    
    key = 'equip'

    def func(self):
        self.msg(f"You {self.cmdstring} {self.obj}.")

class ClothingCmdSet(CmdSet):
    
    key = "Clothing"

    def at_cmdset_creation(self):
        self.add(CmdEquip)
```

Only one of the following implementations works as expected.
```
class ActionsCmdSet(CmdSet):
    """
    This one works fine.
    """
    key = "Actions"
    
    def at_cmdset_creation(self):
        # This is part of the ClothingCmdSet
        self.add(CmdEquip) 
        
```

```
class ActionsCmdSet(CmdSet):
    """
    This one eventually fails most lockchecking and 
    there is no `self.obj` accessible at the time of `func`.
    """
    key = "Actions"
    
    def at_cmdset_creation(self):
        self.add(ClothingCmdSet)
        
```

Related stack trace:
```
20-10-09 00:23:47 Unhandled Error
        Traceback (most recent call last):
          File "/home/ubuntu/workspace/E37/lib/python3.7/site-packages/evennia/commands/cmdhandler.py", line 631, in _run_command
            ret = cmd.func()
          File "/home/ubuntu/workspace/E37/lib/python3.7/site-packages/evennia/commands/default/building.py", line 2658, in func
            ).addCallback(get_cmdset_callback)
          File "/home/ubuntu/workspace/E37/lib/python3.7/site-packages/twisted/internet/defer.py", line 322, in addCallback
            callbackKeywords=kw)
          File "/home/ubuntu/workspace/E37/lib/python3.7/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
            self._runCallbacks()
        --- <exception caught here> ---
          File "/home/ubuntu/workspace/E37/lib/python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/home/ubuntu/workspace/E37/lib/python3.7/site-packages/evennia/commands/default/building.py", line 2581, in get_cmdset_callback
            string = self.format_output(obj, cmdset)
          File "/home/ubuntu/workspace/E37/lib/python3.7/site-packages/evennia/commands/default/building.py", line 2512, in format_output
            avail_cmdset = sorted([cmd.key for cmd in avail_cmdset if cmd.access(obj, "cmd")])
          File "/home/ubuntu/workspace/E37/lib/python3.7/site-packages/evennia/commands/default/building.py", line 2512, in <listcomp>
            avail_cmdset = sorted([cmd.key for cmd in avail_cmdset if cmd.access(obj, "cmd")])
          File "/home/ubuntu/workspace/E37/lib/python3.7/site-packages/evennia/commands/command.py", line 328, in access
            return self.lockhandler.check(srcobj, access_type, default=default)
          File "/home/ubuntu/workspace/E37/lib/python3.7/site-packages/evennia/locks/lockhandler.py", line 555, in check
            bool(tup[0](accessing_obj, self.obj, *tup[1], **tup[2])) for tup in func_tup
          File "/home/ubuntu/workspace/E37/lib/python3.7/site-packages/evennia/locks/lockhandler.py", line 555, in <genexpr>
            bool(tup[0](accessing_obj, self.obj, *tup[1], **tup[2])) for tup in func_tup
          File "/home/ubuntu/workspace/E37/lib/python3.7/site-packages/evennia/locks/lockfuncs.py", line 633, in holds
            return hasattr(accessed_obj, "obj") and check_holds(accessed_obj.obj.dbid)
        builtins.AttributeError: 'NoneType' object has no attribute 'dbid'
```

#### Expected behavior
`self.obj` should propagate to all child CmdSets when nested, no?

#### Environment, Evennia version, OS etc
```
Evennia 0.9.0
    OS: posix
    Python: 3.7.9
    Twisted: 19.10.0
    Django: 2.2.12
```

**Comment by Griatch** [comment]
I'm not surprised - there is no support for nesting cmdsets this way, because they don't have a parent-child relationship at all. The ability to add a cmdsets' commands like this will just loop over the commands in the cmdset and add them rather simply as I recall. It should be rather simple to expand that with running `at_cmdset_creation` for every cmdset in the chain though.

**Comment by strikaco** [comment]
Thanks, that explains what I'm seeing then.

(Side question-- when creating cmdsets, is there any functional difference between adding instances of commands/sets or the classes for either? It looks like instanced commands/sets can be passed arbitrary kwargs but that's the only difference evident to me.)

**Comment by Griatch** [comment]
@strikaco Actually, looking over this again, I think that while cmdsets doesn't have a child-parent relationship, I don't see why `.obj` should not transfer. This ended up being a bug in the cmdset initialization which is now fixed!
