### ISSUE TITLE
[BUG] ExitCmdSet appears to become 'stuck' on objects.

### ISSUE THREAD

**Issue by awranthyr** [evennia/evennia#2328]
#### Describe the bug
An object placed in a room with an Exit seems to maintain the ExitCmdSet on itself even after being moved to another location.

#### To Reproduce
1. dig/tel to a new room with no exits in it.
2. create/drop an object.
3. examine object (should be fine).
4. get object.
5. examine object (should still be fine).
6. dig an exit to another room.
7. drop object.
8. examine object (should still be fine, shows ExitCmdSet on object).
9. get object.
10. examine object (the examine will break at this point).
11. cmdsets object (this will show the ExitCmdSet still present on the object).

#### Expected behavior
I believe the intended behavior is for the ExitCmdSet to be removed from an object that is moved to a location with no Exits.

#### Environment, Evennia version, OS etc
    Evennia 0.9.5 (rev 135e1ba14) (rev 135e1ba14)
    OS: posix
    Python: 3.9.1
    Twisted: 20.3.0
    Django: 2.2.16

#### Additional context
I first ran into this issue while working on my current project, but tested with a newly --init'd instance to ensure the issue was not introduced though my own code.

The traceback when the examine error occurs, displays the following:
```
21-03-03 19:49:26-08 Unhandled error in Deferred:
21-03-03 19:49:26-08 Unhandled Error
        Traceback (most recent call last):
          File "/home/awranthyr/muddev/evennia/evennia/commands/cmdhandler.py", line 644, in _run_command
            ret = cmd.func()
          File "/home/awranthyr/muddev/evennia/evennia/commands/default/building.py", line 2739, in func
            get_and_merge_cmdsets(
          File "/home/awranthyr/muddev/env39/lib/python3.9/site-packages/twisted/internet/defer.py", line 321, in addCallback
            return self.addCallbacks(callback, callbackArgs=args,
          File "/home/awranthyr/muddev/env39/lib/python3.9/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
            self._runCallbacks()
        --- <exception caught here> ---
          File "/home/awranthyr/muddev/env39/lib/python3.9/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/home/awranthyr/muddev/evennia/evennia/commands/default/building.py", line 2659, in get_cmdset_callback
            self.msg(self.format_output(obj, cmdset).strip())
          File "/home/awranthyr/muddev/evennia/evennia/commands/default/building.py", line 2548, in format_output
            all_cmdsets = [(cmdset.key, cmdset) for cmdset in current_cmdset.merged_from]
        builtins.AttributeError: 'NoneType' object has no attribute 'merged_from'

```

**Comment by Griatch** [comment]
Yeah, sounds like the ExitHandler is htting an edge-case. The exit-cmdset expects to be replaced by a new exit-cmdset in the next room but doesn't take into account that it can end up in a room without any exits whatsoever (so no cmdset whatsoever instead of an empty one).

**Comment by Griatch** [comment]
This is no longer reproducible in `develop` branch. Also `examine` has been updated to correctly handle the case where the `current_cmdset` is removed.
