### ISSUE TITLE
[BUG] Evennia.init() fails if COMMAND_DEFAULT_CLASS uses flat API

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#2330]
#### Describe the bug
In discord, Mysterin encountered a TypeError where she received a confusing traceback:
```
File "C:\Users\mysti\Documents\MudDev\Mystavaria\typeclasses\accounts.py", line 28, in <module>
    class Account(DefaultAccount):
TypeError: NoneType takes no arguments
```

It seemed the source of this was a separate traceback:
```
Traceback (most recent call last):
  File "C:\Users\mysti\Documents\MudDev\evenv\Scripts\evennia_launcher.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "C:\Users\mysti\Documents\MudDev\evennia\bin\windows\evennia_launcher.py", line 18, in <module>
    main()
  File "c:\users\mysti\documents\muddev\evennia\evennia\server\evennia_launcher.py", line 2209, in main
    init_game_directory(CURRENT_DIR, check_db=True)
  File "c:\users\mysti\documents\muddev\evennia\evennia\server\evennia_launcher.py", line 1746, in init_game_directory
    check_database()
  File "c:\users\mysti\documents\muddev\evennia\evennia\server\evennia_launcher.py", line 1449, in check_database
    evennia._init()
  File "c:\users\mysti\documents\muddev\evennia\evennia\__init__.py", line 173, in _init
    from .accounts.accounts import DefaultAccount
  File "c:\users\mysti\documents\muddev\evennia\evennia\accounts\accounts.py", line 25, in <module>
    from evennia.commands import cmdhandler
  File "c:\users\mysti\documents\muddev\evennia\evennia\commands\cmdhandler.py", line 47, in <module>
    from evennia.comms.channelhandler import CHANNELHANDLER
  File "c:\users\mysti\documents\muddev\evennia\evennia\comms\channelhandler.py", line 38, in <module>
    _COMMAND_DEFAULT_CLASS = class_from_module(settings.COMMAND_DEFAULT_CLASS)
  File "c:\users\mysti\documents\muddev\evennia\evennia\utils\utils.py", line 1464, in class_from_module
    mod = importlib.import_module(testpath, package="evennia")
  File "c:\program files\python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\mysti\Documents\MudDev\Mystavaria\commands\command.py", line 14, in <module>
    class Command(BaseCommand):
TypeError: NoneType takes no arguments
```

The tldr here is that `init` when importing the `DefaultAccount` imports cmdhandler, which imports `CHANNELHANDLER`, which fetches the default command class - which is in a user file which employed the flat API, and therefore `Command` (imported by her as `BaseCommand`) had not yet been populated by `_init`.

#### To Reproduce
1. Call evennia.init() while `settings.COMMAND_DEFAULT_CLASS` points to a file with flat api
2. See error

#### Expected behavior
I would expect the flat API to not break based on the default command class's imports.

#### Additional context
Maybe just moving the command imports above DefaultAccount might solve it? Changing cmdhandler to a local import in the `execute_cmd` method where it's used in `DefaultAccount` might be cleaner though, and break the cascading imports that caused the error.

**Comment by Griatch** [comment]
I fear there will always be the risk of a circular import here. I recently removed the BASE_*_TYPECLASS imports in `__init__` for this very reason - it was only a mild convenience to have them in the flat API and they were a major reason for causing circular import problems since people are likely to use the flat api for their custom typeclasses. 

Doing a delayed import of cmdhandler in accounts.py (and objects.py) seems like the cleanest solution indeed.
