### ISSUE TITLE
[DEVEL] [BUG] builtins.RuntimeError: Request.finish called on a request after its connection was lost

### ISSUE THREAD

**Issue by GulliblePsychologist** [evennia/evennia#2458]
#### Describe the bug
```
21-06-27 13:31:45+01  |Portal| Unhandled Error
        Traceback (most recent call last):
          File "site-packages\twisted\application\app.py", line 306, in runReactorWithLogging
            reactor.run()
          File "site-packages\twisted\internet\base.py", line 1423, in run
            self.mainLoop()
          File "site-packages\twisted\internet\base.py", line 1436, in mainLoop
            reactorBaseSelf.doIteration(t)
          File "site-packages\twisted\internet\selectreactor.py", line 143, in doSelect
            _logrun(selectable, _drdw, selectable, method)
        --- <exception caught here> ---
          File "site-packages\twisted\python\log.py", line 101, in callWithLogger
            return callWithContext({"system": lp}, func, *args, **kw)
          File "site-packages\twisted\python\log.py", line 85, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "site-packages\twisted\python\context.py", line 118, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "site-packages\twisted\python\context.py", line 83, in callWithContext
            return func(*args, **kw)
          File "site-packages\twisted\internet\selectreactor.py", line 154, in _doReadOrWrite
            self._disconnectSelectable(selectable, why, method == "doRead")
          File "site-packages\twisted\internet\posixbase.py", line 300, in _disconnectSelectable
            selectable.readConnectionLost(f)
          File "site-packages\twisted\internet\tcp.py", line 307, in readConnectionLost
            self.connectionLost(reason)
          File "site-packages\twisted\internet\tcp.py", line 506, in connectionLost
            self._commonConnection.connectionLost(self, reason)
          File "site-packages\twisted\internet\tcp.py", line 324, in connectionLost
            protocol.connectionLost(reason)
          File "site-packages\twisted\web\http.py", line 657, in connectionLost
            self.handleResponseEnd()
          File "site-packages\twisted\web\proxy.py", line 82, in handleResponseEnd
            self.father.finish()
          File "site-packages\twisted\web\server.py", line 279, in finish
            return http.Request.finish(self)
          File "site-packages\twisted\web\http.py", line 1133, in finish
            raise RuntimeError(
        builtins.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
```

#### To Reproduce
1. Boot up the game.
2. Repeatedly press CTRL+R on a page in your web browser.
3. Eventually, your browser will terminate an old connection prematurely.
4. See error.

#### Expected behavior
No stack trace is supposed to be logged for this, because a connection being terminated halfway is normal behavior.

#### Environment, Evennia version, OS etc
Evennia 1.0-dev (rev 43fd533f2) (rev 43fd533f2)
OS: nt
Python: 3.8.0
Twisted: 21.2.0
Django: 3.2.4

**Comment by Griatch** [comment]
I've seen this, but at this time it's unclear just where this is coming from and how to catch it properly.

**Comment by Griatch** [comment]
I don't know if the rework of the web folder helped or the newer version of twisted, but I'm not seeing this anymore in `develop`; at least I can't easily reproduce it by reloading the page etc. I'm closing this for now, if this is still a common event for you, make a comment and we can re-open.
