### ISSUE TITLE
[BUG] makemessages starts from root directory

### ISSUE THREAD

**Issue by mrseeker** [evennia/evennia#2582]
#### Describe the bug
In windows, running `evennia makemessages --locale nl` will cause django to create pot files from the root directory.

#### To Reproduce
1. Use windows
2. run `evennia makemessages --locale nl`
3. See error

#### Expected behavior
Create a potfile from the evennia folder.

#### Environment, Evennia version, OS etc
  Evennia 1.0-dev
    OS: nt
    Python: 3.9.7
    Twisted: 21.7.0
    Django: 3.2.9

#### Additional context
This is output from my end:

```
PS D:\Data\Git\evennia-dev\evennia> evennia makemessages --locale nl

    TESTING: Using Evennia's default settings file (evennia.settings_default).
    (use 'evennia test --settings settings.py .' to run only your custom game tests)

UnicodeDecodeError: skipped file _sample.txt in .\Data\Dropbox\BCMGames\Plugins (reason: 'utf-8' codec can't decode byte 0xf6 in position 498: invalid start byte)
UnicodeDecodeError: skipped file Readme.txt in .\Data\Dropbox\Keepers\Ham\MMSSTV (reason: 'utf-8' codec can't decode byte 0xa9 in position 8: invalid start byte)
UnicodeDecodeError: skipped file Terms.txt in .\Data\Dropbox\Keepers\Ham\MMSSTV (reason: 'utf-8' codec can't decode byte 0xa9 in position 8: invalid start byte)
UnicodeDecodeError: skipped file Credits.txt in .\Data\Dropbox\Keepers\netgore\netgore\trunk\DevContent\Grh\Tiles\LPC full\Attributions (reason: 'utf-8' codec can't decode byte 0xf6 in position 5818: invalid start byte)
UnicodeDecodeError: skipped file 127.0.0.1.txt in .\Data\Dropbox\MUDGame\MUDGame\bin\Debug (reason: 'utf-8' codec can't decode byte 0xff in position 6: invalid start byte)
Traceback (most recent call last):
  File "C:\Users\Julius\AppData\Local\Programs\Python\Python39\Scripts\evennia_launcher.py", line 18, in <module>
    main()
  File "C:\Users\Julius\AppData\Local\Programs\Python\Python39\Lib\site-packages\evennia\server\evennia_launcher.py", line 2342, in main
    sys.exit(execute_from_command_line(sys.argv))
  File "C:\Users\Julius\AppData\Local\Programs\Python\Python39\Lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "C:\Users\Julius\AppData\Local\Programs\Python\Python39\Lib\site-packages\django\core\management\__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Julius\AppData\Local\Programs\Python\Python39\Lib\site-packages\django\core\management\base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\Julius\AppData\Local\Programs\Python\Python39\Lib\site-packages\django\core\management\base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "C:\Users\Julius\AppData\Local\Programs\Python\Python39\Lib\site-packages\django\core\management\commands\makemessages.py", line 382, in handle
    potfiles = self.build_potfiles()
  File "C:\Users\Julius\AppData\Local\Programs\Python\Python39\Lib\site-packages\django\core\management\commands\makemessages.py", line 432, in build_potfiles
    self.process_files(file_list)
  File "C:\Users\Julius\AppData\Local\Programs\Python\Python39\Lib\site-packages\django\core\management\commands\makemessages.py", line 503, in process_files
    self.process_locale_dir(locale_dir, files)
  File "C:\Users\Julius\AppData\Local\Programs\Python\Python39\Lib\site-packages\django\core\management\commands\makemessages.py", line 522, in process_locale_dir
    build_file.preprocess()
  File "C:\Users\Julius\AppData\Local\Programs\Python\Python39\Lib\site-packages\django\core\management\commands\makemessages.py", line 107, in preprocess
    src_data = fp.read()
  File "C:\Users\Julius\AppData\Local\Programs\Python\Python39\lib\codecs.py", line 319, in decode
    def decode(self, input, final=False):
KeyboardInterrupt
^CTerminate batch job (Y/N)? Y
```

**Comment by Griatch** [comment]
@mrseeker This is due to standing in the wrong location. You need to stand in the `evennia/evennia/` folder (same level as the `locale` folder) to run these commands. I now added a check to make sure you get a nicer warning if being in the wrong location. See the Evennia documentation on i18n, which describes these steps in detail.
