### ISSUE TITLE
[BUG] Error after connecting Admin account

### ISSUE THREAD

**Issue by THEGODFATHERRX** [evennia/evennia#2626]
#### Describe the bug
could not connect, so checked logs, there were a lot of errors, and all of them were AccountDB has no attribute something.

for example
`22-01-14 13:21:17  |Portal| [EE]  'AccountDB' object has no attribute 'at_init' (error logged on other side)
`
```
22-01-14 13:21:19  |Portal| [EE] AMP Error from AdminPortal2Server: Traceback (most recent call last):
22-01-14 13:21:19  |Portal| [EE] Failure: builtins.Exception: 'AccountDB' object has no attribute 'at_disconnect' (error logged on other side)
22-01-14 13:21:19  |Portal| [EE]  'AccountDB' object has no attribute 'at_disconnect' (error logged on other side)

```
```
22-01-14 15:33:58 [::] Traceback (most recent call last):
22-01-14 15:33:58 [::]   File "/home/godfather/evennia/evennia/server/sessionhandler.py", line 853, in call_inputfuncs
22-01-14 15:33:58 [::]     _INPUT_FUNCS[cname](session, *cmdargs, **cmdkwargs)
22-01-14 15:33:58 [::]   File "/home/godfather/evennia/evennia/server/inputfuncs.py", line 84, in text
22-01-14 15:33:58 [::]     txt = session.account.nicks.nickreplace(
22-01-14 15:33:58 [::] AttributeError: 'AccountDB' object has no attribute 'nicks'
22-01-14 15:49:43 [SS] Authentication Success: username(account 2) (IP: 127.0.0.1).
22-01-14 15:49:43 [..] Logged in: username(account 2) 127.0.0.1 (1 session(s) total)

```

#### To Reproduce
I am just following 'Getting Started' guide for Linux, I successfully made an account, but when I tried connecting the admin account it would return an error.(client side)
```
Traceback (most recent call last):
  File "/home/godfather/evennia/evennia/commands/cmdhandler.py", line 644, in _run_command
    ret = cmd.func()
  File "/home/godfather/evennia/evennia/commands/default/unloggedin.py", line 151, in func
    session.sessionhandler.login(session, account)
  File "/home/godfather/evennia/evennia/server/sessionhandler.py", line 506, in login
    account.at_init()
AttributeError: 'AccountDB' object has no attribute 'at_init'

```
I can however login using the admin dashboard website.
Also normal user account works just fine, but I can still see the "has no attribute" error in the Evennia server logs
#### Expected behavior
Admin accounts should connect.
there shouldn't be those "has no attributes" errors
#### Environment, Evennia version, OS etc
```

    Evennia 0.9.5 (rev fa79110ba) (rev fa79110ba)
    OS: posix
    Python: 3.10.1
    Twisted: 21.7.0
    Django: 3.2.11
    
```
OS is Arch Linux.

#### Additional context
```
❯ evennia start -l
   Tailing logfiles /home/godfather/Code/muddev/mygame/server/logs/server.log and portal.log (Ctrl-C to exit) ...
 [Devel: settings.IN_GAME_ERRORS is True. Turn off in production.]
 [Devel: settings.ALLOWED_HOSTS set to '*' (all). Limit in production.]
Portal starting ...
22-01-14 12:44:39  |Portal| Loading /home/godfather/evennia/evennia/server/portal/portal.py...
22-01-14 12:44:40  |Portal| Loaded.
22-01-14 12:44:40  |Portal| twistd 21.7.0 (/usr/bin/python 3.10.1) starting up.
22-01-14 12:44:40  |Portal| reactor class: twisted.internet.epollreactor.EPollReactor.
22-01-14 12:44:40  |Portal| AMP starting on 4006
22-01-14 12:44:40  |Portal| Telnet starting on 4000
22-01-14 12:44:40  |Portal| Websocket starting on 4002
22-01-14 12:44:40  |Portal| Webserver-proxy starting on 4001
... Portal started.
Server starting  ...
... Server started.
Evennia running.
------------------------ Evennia ---
mygame Portal 0.9.5 (rev fa79110ba)
    external ports:
        telnet: 4000
        webserver-proxy: 4001
        webclient-websocket: 4002
    internal_ports (to Server):
        webserver: 4005
        amp: 4006

mygame Server 0.9.5 (rev fa79110ba)
    internal ports (to Portal):
        webserver: 4005
        amp : 4006
------------------------------------
22-01-14 12:44:40  |Portal| Portal starting server ... 
22-01-14 12:44:40 Loading /home/godfather/evennia/evennia/server/server.py...
22-01-14 12:44:40 Loaded.
22-01-14 12:44:40 twistd 21.7.0 (/usr/bin/python 3.10.1) starting up.
22-01-14 12:44:40 reactor class: twisted.internet.epollreactor.EPollReactor.
22-01-14 12:44:40 Webserver starting on 4005
22-01-14 12:44:40 Evennia Server successfully started.
22-01-14 12:46:09  |Portal| Timing out client: IPv4Address(type='TCP', host='127.0.0.1', port=42018)
22-01-14 12:46:09 [SS] Authentication Success: gAdmin(account 3) (IP: 127.0.0.1).
22-01-14 12:46:09 [::] Traceback (most recent call last):
22-01-14 12:46:09 [::]   File "/home/godfather/evennia/evennia/commands/cmdhandler.py", line 644, in _run_command
22-01-14 12:46:09 [::]     ret = cmd.func()
22-01-14 12:46:09 [::]   File "/home/godfather/evennia/evennia/commands/default/unloggedin.py", line 151, in func
22-01-14 12:46:09 [::]     session.sessionhandler.login(session, account)
22-01-14 12:46:09 [::]   File "/home/godfather/evennia/evennia/server/sessionhandler.py", line 506, in login
22-01-14 12:46:09 [::]     account.at_init()
22-01-14 12:46:09 [::] AttributeError: 'AccountDB' object has no attribute 'at_init'
22-01-14 12:46:09 [EE] User input was: 'connect gAdmin FAKEpassword'.
```

CLIENT->
```
❯ telnet 127.0.0.1 4000
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.

==============================================================
 Welcome to mygame, version 0.9.5!

 If you have an existing account, connect to it by typing:
      connect <username> <password>
 If you need to create an account, type (without the <>'s):
      create <username> <password>

 Enter help for more info. look will re-show this screen.
==============================================================
connect gAdmin FAKEpassword
Traceback (most recent call last):
  File "/home/godfather/evennia/evennia/commands/cmdhandler.py", line 644, in _run_command
    ret = cmd.func()
  File "/home/godfather/evennia/evennia/commands/default/unloggedin.py", line 151, in func
    session.sessionhandler.login(session, account)
  File "/home/godfather/evennia/evennia/server/sessionhandler.py", line 506, in login
    account.at_init()
AttributeError: 'AccountDB' object has no attribute 'at_init'

An untrapped error occurred.
(Traceback was logged 22-01-14 12:46:09).

```

**Comment by strikaco** [comment]
Unrelated, but this sort of leakage in logs is not ideal:

> `22-01-14 12:46:09 [EE] User input was: 'connect gAdmin FAKEpassword'.`

**Comment by THEGODFATHERRX** [comment]
> Unrelated, but this sort of leakage in logs is not ideal:
> 
> > `22-01-14 12:46:09 [EE] User input was: 'connect gAdmin FAKEpassword'.`

I noticed that so I changed the text, but what you are saying is correct.

**Comment by THEGODFATHERRX** [comment]
OK so what I've noticed is that the problem only occurs if I try logging in a Admin account. 
while testing with a normal user account, no problems occur, and everything runs smoothly. (logging in, running commands, logging out, shutting down server).

while attempting to login with an Admin account, I cannot login, and cannot shutdown the server too, and have to kill it using htop. also loading the website gives this error on the server side
`        builtins.AttributeError: 'AccountDB' object has no attribute 'unpuppet_all'
` 
but website seems to work normally. (logging in accounts, loading the other pages)

so I think this error is just duplicate of #2627, because all the errors start after logging in the admin account. also, ive used the weblient and telnet, both times the error occurs.

**Comment by Griatch** [comment]
@THEGODFATHERRX What do you mean by an "Admin" account? An account created in the django admin or just an administrator-level account?

**Comment by THEGODFATHERRX** [comment]
@Griatch I created the account using 'evennia createsuperuser' from the terminal. 

I just created another Admin account(using terminal), and another normal user (using 'create' in game).
the problem replicates exactly as stated above, Admin account returns a traceback and crashes the connection, user account works fine.

**Comment by Griatch** [comment]
Additional accounts created using `createsuperuser` will not be setup correctly (the first account works, but this is normally created automatically). This is now blocked to avoid this confusion.
