### ISSUE TITLE
[BUG] Error handler logging authentication commands in plaintext

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2627]
#### Describe the bug
A user posted traceback logs which recorded plaintext credentials as a failed user input (in #2626).

(They caught it and sanitized it before posting, but this should not be happening.)

#### To Reproduce
```
22-01-14 12:44:40  |Portal| Portal starting server ... 
22-01-14 12:44:40 Loading /home/godfather/evennia/evennia/server/server.py...
22-01-14 12:44:40 Loaded.
22-01-14 12:44:40 twistd 21.7.0 (/usr/bin/python 3.10.1) starting up.
22-01-14 12:44:40 reactor class: twisted.internet.epollreactor.EPollReactor.
22-01-14 12:44:40 Webserver starting on 4005
22-01-14 12:44:40 Evennia Server successfully started.
22-01-14 12:46:09  |Portal| Timing out client: IPv4Address(type='TCP', host='127.0.0.1', port=42018)
22-01-14 12:46:09 [SS] Authentication Success: gAdmin(account 3) (IP: 127.0.0.1).
22-01-14 12:46:09 [::] Traceback (most recent call last):
22-01-14 12:46:09 [::]   File "/home/godfather/evennia/evennia/commands/cmdhandler.py", line 644, in _run_command
22-01-14 12:46:09 [::]     ret = cmd.func()
22-01-14 12:46:09 [::]   File "/home/godfather/evennia/evennia/commands/default/unloggedin.py", line 151, in func
22-01-14 12:46:09 [::]     session.sessionhandler.login(session, account)
22-01-14 12:46:09 [::]   File "/home/godfather/evennia/evennia/server/sessionhandler.py", line 506, in login
22-01-14 12:46:09 [::]     account.at_init()
22-01-14 12:46:09 [::] AttributeError: 'AccountDB' object has no attribute 'at_init'
22-01-14 12:46:09 [EE] User input was: 'connect gAdmin FAKEpassword'.
```
#### Expected behavior
Really not sure what the best solution is. 

* Logger should mask/sanitize the end of user input strings starting with `connect` (or some permutation of the letters to account for misspelling)?
* Maybe just don't _log_ strings meeting this criteria-- but display them to the caller if `IN_GAME_ERRORS` is enabled?

#### Additional context
I wrote a bunch of regexes to mask passwords from inputs/outputs for the auditing contrib. Might be reusable.

https://github.com/evennia/evennia/blob/fa79110ba6b219932f22297838e8ac72ebc0be0e/evennia/contrib/security/auditing/server.py#L24-L33

**Comment by Griatch** [comment]
@strikaco Your `AUDIT_MASKS` changes looks good, why not make a PR out of it?  :)

**Comment by strikaco** [comment]
This would involve changing core functionality (logging). My domain is security, not programming, so I'm hesitant to force adoption of my opinions on everyone without an opportunity for feedback. (I also don't have a ton of free time these days and need to plan-before-coding wherever possible.)

Implementing this would obfuscate discovery of client-specific authentication issues (dev won't see if authentication failure could be due to garbage characters inserted into client input string-- ironically I reported such an issue with Telnet years ago, which was detected because of this very loophole).

Making it toggleable invites trouble. A lax dev would (continue to) harvest creds from all authentication tracebacks if they forget to re-enable, which compromises users without any sort of accountability from the offender.
