### ISSUE TITLE
[BUG] After migrating from 0.9 to 0.9.5 evenia start tracebacks - deprecated usage of evennias Command class?

### ISSUE THREAD

**Issue by BP-Santo** [evennia/evennia#2709]
#### Describe the bug
While preparing to resume work on my project, I started migrating from 0.9 to 0.9.5 and having issues with importing evennias Command class.

With a fresh db after an `evennia migrate`, I get the following traceback from `evennia start`:
```
Traceback (most recent call last):
  File "/home/santo/development/ldmud/venv-3.10.4/bin/evennia", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/santo/development/ldmud/evennia/bin/unix/evennia", line 10, in <module>
    main()
  File "/home/santo/development/ldmud/evennia/evennia/server/evennia_launcher.py", line 2209, in main
    init_game_directory(CURRENT_DIR, check_db=True)
  File "/home/santo/development/ldmud/evennia/evennia/server/evennia_launcher.py", line 1746, in init_game_directory
    check_database()
  File "/home/santo/development/ldmud/evennia/evennia/server/evennia_launcher.py", line 1449, in check_database
    evennia._init()
  File "/home/santo/development/ldmud/evennia/evennia/__init__.py", line 160, in _init
    from .objects.objects import DefaultObject
  File "/home/santo/development/ldmud/evennia/evennia/objects/objects.py", line 44, in <module>
    _COMMAND_DEFAULT_CLASS = class_from_module(settings.COMMAND_DEFAULT_CLASS)
  File "/home/santo/development/ldmud/evennia/evennia/utils/utils.py", line 1468, in class_from_module
    mod = importlib.import_module(testpath, package="evennia")
  File "/home/santo/development/python-source/python3.10.4/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/santo/development/ldmud/ldmud/commands/default_mux_command.py", line 2, in <module>
    from commands.top_command import TopCommand
  File "/home/santo/development/ldmud/ldmud/commands/top_command.py", line 4, in <module>
    class TopCommand(Command):
TypeError: NoneType takes no arguments
```

CONTEXT:
default_mux_command.py contains my base command class (COMMAND_DEFAULT_CLASS points to it in settings.py) - it inherits from top_command.py, which itself is just a placeholder that inherits from evennias Command.
Pycharm linter sees `from evenia import Command` as a valid import however of type none which lines up with the traceback.

#### Environment, Evennia version, OS etc
Output of `evennia -v` for old environment (currently works fine) [debian 10]:
```
    Evennia 0.9.0 (rev 7b13553f2) (rev 7b13553f2)
    OS: posix
    Python: 3.8.3
    Twisted: 20.3.0
    Django: 2.2.12
```
Output for new (results in above traceback) [debian 11]:
```
    Evennia 0.9.5 (rev 5d708f72f) (rev 5d708f72f)
    OS: posix
    Python: 3.10.4
    Twisted: 21.7.0
    Django: 3.2.12
```

I have a year and a half worth of evennias commits to read through for changes but thought it would not hurt to make an issue to steal some brain folds from the community c:

**Comment by BP-Santo** [comment]
Had some time to look around and noticed the namespacing is different now and the following works as expect:
`from evennia.commands.command import Command`

Leaving issue open as not sure if `from evennia import Command` was intended to not longer work.

**Comment by Griatch** [comment]
This is due to importing at the top of a module before the evennia.__init__.py has had time to initialize. So a sort of circular race condition. Doing a delayed import or, as you did, import from the actual location of the Command resolves it. We have cleaned up the package a bit in later versions, but this remains a possibility to be aware of.
