### ISSUE TITLE
[BUG] Unhandled Error always occurs when you click Play Online on the homepage

### ISSUE THREAD

**Issue by aceamro** [evennia/evennia#2756]
#### Describe the bug
Unhandled Error always occurs when you click Play Online on the homepage

#### To Reproduce
1. evennia --init mygame
2. cd mygame
3. evennia -l start
4. web browser localhost:4005, Play Online (menu click)

#### Expected behavior
22-06-07 20:17:23  |Portal| Unhandled Error
	Traceback (most recent call last):
	  File "/Users/ethan/evenv/lib/python3.9/site-packages/twisted/python/log.py", line 101, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/Users/ethan/evenv/lib/python3.9/site-packages/twisted/python/log.py", line 85, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/Users/ethan/evenv/lib/python3.9/site-packages/twisted/python/context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/Users/ethan/evenv/lib/python3.9/site-packages/twisted/python/context.py", line 83, in callWithContext
	    return func(*args, **kw)
	--- <exception caught here> ---
	  File "/Users/ethan/evenv/lib/python3.9/site-packages/twisted/internet/selectreactor.py", line 149, in _doReadOrWrite
	    why = getattr(selectable, method)()
	  File "/Users/ethan/evenv/lib/python3.9/site-packages/twisted/internet/tcp.py", line 247, in doRead
	    return self._dataReceived(data)
	  File "/Users/ethan/evenv/lib/python3.9/site-packages/twisted/internet/tcp.py", line 252, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/Users/ethan/evenv/lib/python3.9/site-packages/twisted/protocols/basic.py", line 554, in dataReceived
	    why = self.rawDataReceived(data)
	  File "/Users/ethan/evenv/lib/python3.9/site-packages/twisted/web/http.py", line 706, in rawDataReceived
	    self.handleResponseEnd()
	  File "/Users/ethan/evenv/lib/python3.9/site-packages/twisted/web/proxy.py", line 82, in handleResponseEnd
	    self.father.finish()
	  File "/Users/ethan/evenv/lib/python3.9/site-packages/twisted/web/server.py", line 279, in finish
	    return http.Request.finish(self)
	  File "/Users/ethan/evenv/lib/python3.9/site-packages/twisted/web/http.py", line 1131, in finish
	    raise RuntimeError(
	builtins.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
(Replace with a clear and concise description of what you expected to happen.)

#### Environment, Evennia version, OS etc
    Evennia 0.9.5 (rev fc6b8550b) (rev fc6b8550b)
    OS: posix
    Python: 3.9.12
    Twisted: 21.7.0
    Django: 3.2.13

#### Additional context
(Replace with any other context about the problem, or ideas on how to solve.)

**Comment by InspectorCaracal** [comment]
The default settings for evennia have the website on port `4001`, so you should be connecting to `localhost:4001` - `4005` is the internal port that the webserver listens on. Have you changed the port bindings?

**Comment by aceamro** [comment]
I'm sorry I misunderstood. Close the issue.

**Comment by Griatch** [comment]
Port 4005 is normally not open to the browser at all, it would only be possible to direct a browser to it on localhost or if the router/firewall was equally set up to let it through. But to be fair, the error here is not obvious; we could probably do something more informative ...
