### ISSUE TITLE
[BUG] dumpdata and typeclasses.Attribute

### ISSUE THREAD

**Issue by dvoraen** [evennia/evennia#2806]
#### Describe the bug
Use of the django-admin dumpdata command on typeclasses.Attribute will fail.  PickledObjectField will fail to serialize.

#### To Reproduce
1. Go to the root folder for your evennia project.
2. Command line: "evennia dumpdata -o test.json --indent 4 typeclasses.Attribute"
3. Observe the following error:

```
CommandError: Unable to serialize database: 'PickledObjectField' object has no attribute '_get_val_from_obj'
Exception ignored in: <generator object cursor_iter at 0x00000280921BB4A0>
Traceback (most recent call last):
  File "F:\ArxDev\arxcode\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1557, in cursor_iter
    cursor.close()
sqlite3.ProgrammingError: Cannot operate on a closed database.
```

4. If you include --traceback option in the command line, this is the (expanded) error:
```
Traceback (most recent call last):
  File "F:\ArxDev\arxcode\venv\Scripts\evennia_launcher.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "F:\ArxDev\evennia\bin\windows\evennia_launcher.py", line 18, in <module>
    main()
  File "f:\arxdev\evennia\evennia\server\evennia_launcher.py", line 2282, in main
    sys.exit(execute_from_command_line(sys.argv))
  File "F:\ArxDev\arxcode\venv\Lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "F:\ArxDev\arxcode\venv\Lib\site-packages\django\core\management\__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "F:\ArxDev\arxcode\venv\Lib\site-packages\django\core\management\base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "F:\ArxDev\arxcode\venv\Lib\site-packages\django\core\management\base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "F:\ArxDev\arxcode\venv\Lib\site-packages\django\core\management\commands\dumpdata.py", line 181, in handle
    serializers.serialize(
  File "F:\ArxDev\arxcode\venv\Lib\site-packages\django\core\serializers\__init__.py", line 128, in serialize
    s.serialize(queryset, **options)
  File "F:\ArxDev\arxcode\venv\Lib\site-packages\django\core\serializers\base.py", line 107, in serialize
    self.handle_field(obj, field)
  File "F:\ArxDev\arxcode\venv\Lib\site-packages\django\core\serializers\python.py", line 50, in handle_field
    self._current[field.name] = self._value_from_field(obj, field)
  File "F:\ArxDev\arxcode\venv\Lib\site-packages\django\core\serializers\python.py", line 47, in _value_from_field
    return value if is_protected_type(value) else field.value_to_string(obj)
  File "f:\arxdev\evennia\evennia\utils\picklefield.py", line 289, in value_to_string
    value = self._get_val_from_obj(obj)
AttributeError: 'PickledObjectField' object has no attribute '_get_val_from_obj'
Exception ignored in: <generator object cursor_iter at 0x000001EB86E0FCF0>
Traceback (most recent call last):
  File "F:\ArxDev\arxcode\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1557, in cursor_iter
    cursor.close()
sqlite3.ProgrammingError: Cannot operate on a closed database.
```

#### Expected behavior
A bigass file named test.json in my current directory that contains a (JSON) dump of the attribute table.

#### Environment, Evennia version, OS etc
Python 3.8.10
Windows 10 (PowerShell)
Evennia 0.9.5 (Tehom's fork of it for Arx)

#### Additional context
I looked through the master branch of Evennia, and it seems like the code for PickledObjectField hasn't really changed compared to the fork I'm using (that is, the line ```value = self._get_val_from_obj(obj)``` is still present in PickledObjectField) so I presume it affects the current state of Evennia as well.

My dive through the Evennia code led me to wonder if ```value_from_string()``` in PickledObjectField is using defunct code, in that I can't find any function/method named ```_get_val_from_obj()``` anywhere, including django, from which PickledObjectField inherits.

**Comment by aogier** [comment]
FYI, in vanilla 0.9.5 evennia error exist, although different from what you report. In 1.0 it does not. Could it be feasible to ask your fork maintainer to update his base branch?

**Comment by Griatch** [comment]
@TehomCD This is more something for ArxCode. Closing this against Evennia 1.0-dev.
