### ISSUE TITLE
[BUG] tzdata missing from requirements.txt

### ISSUE THREAD

**Issue by Routhinator** [evennia/evennia#2840]
#### Describe the bug
`tzdata`, while required for Timestamps on `[MudInfo]` events, is not in the requirements.txt file. As a result, unless the system already had it installed before evennia was installed, there are stack traces seen in the game whenever a `[MudInfo]` event occurs.
#### To Reproduce
1. Install evennia on a system where `tzdata` is not installed.
2. Start evennia
3. Login with a superuser that recieves `[MudInfo]` events.

#### Expected behavior
`tzdata` should be explicitly declared in requirements.txt as a dependency.

#### Environment, Evennia version, OS etc
Tested on a fresh Ubuntu 22.04 container with Python 3.10 installed.

**Comment by Griatch** [comment]
I have no `tzdata` package in my Evennia development virtualenv ... (running Python 3.10 on Linux Mint 20.3)

**Comment by Routhinator** [comment]
After our discussion in #getting-help - it appears this is new behaviour when the system does not have a system timezone set, as of Python 3.9

From https://docs.python.org/3/library/zoneinfo.html
> By default, [zoneinfo](https://docs.python.org/3/library/zoneinfo.html#module-zoneinfo) uses the system’s time zone data if available; if no system time zone data is available, the library will fall back to using the first-party [tzdata](https://pypi.org/project/tzdata/) package available on PyPI. 


Since containers don't usually have a TZ set for the system, this is likely to be prevalent in containerized deployments.

**Comment by Routhinator** [comment]
Full stack trace (for prosperity!)

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/zoneinfo/_common.py", line 12, in load_tzdata
    return importlib.resources.open_binary(package_name, resource_name)
  File "/usr/lib/python3.10/importlib/resources.py", line 43, in open_binary
    package = _common.get_package(package)
  File "/usr/lib/python3.10/importlib/_common.py", line 66, in get_package
    resolved = resolve(package)
  File "/usr/lib/python3.10/importlib/_common.py", line 57, in resolve
    return cand if isinstance(cand, types.ModuleType) else importlib.import_module(cand)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tzdata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/evennia/evennia/commands/cmdhandler.py", line 621, in _run_command
    ret = cmd.func()
  File "/usr/src/evennia/evennia/commands/default/account.py", line 816, in func
    account.disconnect_session_from_account(self.session, reason)
  File "/usr/src/evennia/evennia/accounts/accounts.py", line 271, in disconnect_session_from_account
    _SESSIONS.disconnect(session, reason)
  File "/usr/src/evennia/evennia/server/sessionhandler.py", line 573, in disconnect
    session.at_disconnect(reason)
  File "/usr/src/evennia/evennia/server/serversession.py", line 136, in at_disconnect
    account.at_disconnect(reason)
  File "/usr/src/evennia/evennia/accounts/accounts.py", line 1485, in at_disconnect
    self._send_to_connect_channel(
  File "/usr/src/evennia/evennia/accounts/accounts.py", line 1399, in _send_to_connect_channel
    now = timezone.localtime()
  File "/usr/local/lib/python3.10/dist-packages/django/utils/timezone.py", line 203, in localtime
    timezone = get_current_timezone()
  File "/usr/local/lib/python3.10/dist-packages/django/utils/timezone.py", line 84, in get_current_timezone
    return getattr(_active, "value", get_default_timezone())
  File "/usr/local/lib/python3.10/dist-packages/django/utils/timezone.py", line 70, in get_default_timezone
    return zoneinfo.ZoneInfo(settings.TIME_ZONE)
  File "/usr/lib/python3.10/zoneinfo/_common.py", line 24, in load_tzdata
    raise ZoneInfoNotFoundError(f"No time zone found with key {key}")
zoneinfo._common.ZoneInfoNotFoundError: 'No time zone found with key UTC'

```
