### ISSUE TITLE
[BUG - Develop] Can't start server on fresh game install - builtins.MemoryError

### ISSUE THREAD

**Issue by audiodude** [evennia/evennia#2854]
#### Describe the bug
When trying the initial `evennia start` from within a fresh game install based on the develop branch, the server won't start and the logs report a `builtins.MemoryError` over and over

#### To Reproduce
1. Create a new game with `evennia --init`
2. cd into the directory of the game and run `evennia migrate`
3. Try to start the game with `evennia start`
4. Script reports `... Server started.`, but it is not connectable
5. Open logs for server in game directory, see:

```
22-09-10 11:10:04 [..] Server disconnected from the portal.
22-09-10 11:10:05 Unhandled Error
	Traceback (most recent call last):
	  File "<redacted path>/scriptslash-ev/venv/lib/python3.9/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "<redacted path>/scriptslash-ev/venv/lib/python3.9/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "<redacted path>/scriptslash-ev/venv/lib/python3.9/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "<redacted path>/scriptslash-ev/venv/lib/python3.9/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "<redacted path>/scriptslash-ev/venv/lib/python3.9/site-packages/twisted/internet/selectreactor.py", line 149, in _doReadOrWrite
	    why = getattr(selectable, method)()
	  File "<redacted path>/scriptslash-ev/venv/lib/python3.9/site-packages/twisted/internet/tcp.py", line 627, in doConnect
	    self._connectDone()
	  File "<redacted path>/scriptslash-ev/venv/lib/python3.9/site-packages/twisted/internet/tcp.py", line 656, in _connectDone
	    self.protocol.makeConnection(self)
	  File "<redacted path>/evennia/evennia/server/portal/amp.py", line 348, in makeConnection
	    amp.BinaryBoxProtocol.makeConnection(self, transport)
	  File "<redacted path>/scriptslash-ev/venv/lib/python3.9/site-packages/twisted/protocols/amp.py", line 2391, in makeConnection
	    self.connectionMade()
	  File "<redacted path>/evennia/evennia/server/amp_client.py", line 118, in connectionMade
	    self.factory.server.run_initial_setup()
	  File "<redacted path>/evennia/evennia/server/server.py", line 345, in run_initial_setup
	    last_initial_setup_step = ServerConfig.objects.conf("last_initial_setup_step")
	  File "<redacted path>/evennia/evennia/server/manager.py", line 50, in conf
	    if not conf:
	  File "<redacted path>/scriptslash-ev/venv/lib/python3.9/site-packages/django/db/models/query.py", line 278, in __bool__
	    self._fetch_all()
	  File "<redacted path>/scriptslash-ev/venv/lib/python3.9/site-packages/django/db/models/query.py", line 1242, in _fetch_all
	    self._result_cache = list(self._iterable_class(self))
	  File "<redacted path>/scriptslash-ev/venv/lib/python3.9/site-packages/django/db/models/query.py", line 55, in __iter__
	    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
	  File "<redacted path>/scriptslash-ev/venv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1142, in execute_sql
	    cursor.execute(sql, params)
	  File "<redacted path>/scriptslash-ev/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
	    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
	  File "<redacted path>/scriptslash-ev/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
	    return executor(sql, params, many, context)
	  File "<redacted path>/scriptslash-ev/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
	    return self.cursor.execute(sql, params)
	  File "<redacted path>/scriptslash-ev/venv/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
	    return Database.Cursor.execute(self, query, params)
	builtins.MemoryError: 
```

#### Expected behavior
Server starts without errors

#### Develop-branch commit
Evennia 0.9.0 (rev a61918c6) (rev a61918c6)

#### Additional context
Running on macOS 10.15.7 with Python 3.9.13 installed using asdf. Directory structure is:

code/evennia
code/scriptslash-ev
code/scriptslash-ev/venv

Evennia installed in the venv with `pip install -e ../evennia` from the `scriptslash-ev` directory.

**Comment by audiodude** [comment]
Additionally, this puts server startup in a bad state. If I `evennia stop` it says the server has already stopped, but if I then `evennia start` I get:

```
22-09-10 22:00:39 twisted.internet.error.CannotListenError: Couldn't listen on 127.0.0.1:4005: [Errno 48] Address already in use.
```

**Comment by audiodude** [comment]
Realized my evennia/develop branch was literally 1000 commits behind the official repo. Tried again, with the same result.

**Develop-branch commit**

 Evennia 1.0-dev (rev b1bf2be88) (rev b1bf2be88)

**Stack trace**

```
2022-09-11 03:45:02 [..] Webserver starting on 4005
2022-09-11 03:45:02 [!!] Unhandled Error
	Traceback (most recent call last):
	  File "<path redacted>/scriptslash-ev/venv/lib/python3.9/site-packages/twisted/python/log.py", line 101, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "<path redacted>/scriptslash-ev/venv/lib/python3.9/site-packages/twisted/python/log.py", line 85, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "<path redacted>/scriptslash-ev/venv/lib/python3.9/site-packages/twisted/python/context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "<path redacted>/scriptslash-ev/venv/lib/python3.9/site-packages/twisted/python/context.py", line 83, in callWithContext
	    return func(*args, **kw)
	--- <exception caught here> ---
	  File "<path redacted>/scriptslash-ev/venv/lib/python3.9/site-packages/twisted/internet/selectreactor.py", line 149, in _doReadOrWrite
	    why = getattr(selectable, method)()
	  File "<path redacted>/scriptslash-ev/venv/lib/python3.9/site-packages/twisted/internet/tcp.py", line 614, in doConnect
	    self._connectDone()
	  File "<path redacted>/scriptslash-ev/venv/lib/python3.9/site-packages/twisted/internet/tcp.py", line 642, in _connectDone
	    self.protocol.makeConnection(self)
	  File "<path redacted>/evennia/evennia/server/portal/amp.py", line 448, in makeConnection
	    amp.BinaryBoxProtocol.makeConnection(self, transport)
	  File "<path redacted>/scriptslash-ev/venv/lib/python3.9/site-packages/twisted/protocols/amp.py", line 2346, in makeConnection
	    self.connectionMade()
	  File "<path redacted>/evennia/evennia/server/amp_client.py", line 118, in connectionMade
	    self.factory.server.run_initial_setup()
	  File "<path redacted>/evennia/evennia/server/server.py", line 344, in run_initial_setup
	    last_initial_setup_step = ServerConfig.objects.conf("last_initial_setup_step")
	  File "<path redacted>/evennia/evennia/server/manager.py", line 50, in conf
	    if not conf:
	  File "<path redacted>/scriptslash-ev/venv/lib/python3.9/site-packages/django/db/models/query.py", line 324, in __bool__
	    self._fetch_all()
	  File "<path redacted>/scriptslash-ev/venv/lib/python3.9/site-packages/django/db/models/query.py", line 1507, in _fetch_all
	    self._result_cache = list(self._iterable_class(self))
	  File "<path redacted>/scriptslash-ev/venv/lib/python3.9/site-packages/django/db/models/query.py", line 57, in __iter__
	    results = compiler.execute_sql(
	  File "<path redacted>/scriptslash-ev/venv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1361, in execute_sql
	    cursor.execute(sql, params)
	  File "<path redacted>/scriptslash-ev/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
	    return self._execute_with_wrappers(
	  File "<path redacted>/scriptslash-ev/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
	    return executor(sql, params, many, context)
	  File "<path redacted>/scriptslash-ev/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
	    return self.cursor.execute(sql, params)
	  File "<path redacted>/scriptslash-ev/venv/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 477, in execute
	    return Database.Cursor.execute(self, query, params)
	builtins.MemoryError: 
```

**Comment by audiodude** [comment]
I binary searched python versions and this error occurred for me in python 3.9.0, 3.9.1, 3.9.2, 3.9.4, 3.9.6 and 3.9.13

**Comment by audiodude** [comment]
What's particularly odd is that in the sqlite db, the `server_serverconfig` table is completely empty.

**Comment by audiodude** [comment]
Results of `sqlite3 --version`, in case it matters:

```
3.28.0 2019-04-15 14:49:49 378230ae7f4b721c8b8d83c8ceb891449685cd23b1702a57841f1be40b5daapl
```

**Comment by audiodude** [comment]
Okay so I figured it had to do with the sqlite version and I managed to install the latest version using homebrew (`brew install sqlite`) then linked to that when building my python version 3.9.13. That resolved the issue.

**Comment by Griatch** [comment]
Interesting. This sounds useful to add to the troubleshooting section of the documentation. Thanks for investigating.

**Comment by jotwin** [comment]
I'm getting the same error on evennia 1.1.0 and macos 12.6.2. Fresh install and server doesn't work. I guess it has to do with the sqlite macos provides. I don't know how to link the homebrew version. I tried both python 3.11.1 and 3.10.9.

```
	    if not conf:
	  File "/Users/jakub/work/games/godmush/evenv/lib/python3.11/site-packages/django/db/models/query.py", line 408, in __bool__
	    self._fetch_all()
	  File "/Users/jakub/work/games/godmush/evenv/lib/python3.11/site-packages/django/db/models/query.py", line 1867, in _fetch_all
	    self._result_cache = list(self._iterable_class(self))
	  File "/Users/jakub/work/games/godmush/evenv/lib/python3.11/site-packages/django/db/models/query.py", line 87, in __iter__
	    results = compiler.execute_sql(
	  File "/Users/jakub/work/games/godmush/evenv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1398, in execute_sql
	    cursor.execute(sql, params)
	  File "/Users/jakub/work/games/godmush/evenv/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
	    return self._execute_with_wrappers(
	  File "/Users/jakub/work/games/godmush/evenv/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
	    return executor(sql, params, many, context)
	  File "/Users/jakub/work/games/godmush/evenv/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
	    return self.cursor.execute(sql, params)
	  File "/Users/jakub/work/games/godmush/evenv/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
	    return Database.Cursor.execute(self, query, params)
	builtins.MemoryError: 
```

**Comment by audiodude** [comment]
@jotwin I've fully documented the steps I used to resolve the issue in the related discussion [here](https://github.com/evennia/evennia/discussions/2637#discussioncomment-3630761)
