### ISSUE TITLE
Adding Functionality to prototype for a random location choice from a zone list search (caused  bug)

### ISSUE THREAD

**Issue by Sk33t3rson** [evennia/evennia#2902]
#### Describe the solution you'd like
{..., "location": "$choice($objlist(beach, type=tag))", ...} -- thanks Griatch

**Comment by Griatch** [comment]
Thanks for the request. Added. :)

**Comment by Sk33t3rson** [comment]
Traceback (most recent call last):
  File "c:\muddev\evennia\evennia\commands\cmdhandler.py", line 624, in _run_command
    _progressive_cmd_run(cmd, ret)
  File "c:\muddev\evennia\evennia\commands\cmdhandler.py", line 234, in _progressive_cmd_run
    value = next(generator)
  File "c:\muddev\evennia\evennia\commands\default\building.py", line 4399, in func
    for obj in spawner.spawn(prototype, caller=self.caller):
  File "c:\muddev\evennia\evennia\prototypes\spawner.py", line 950, in spawn
    create_kwargs["db_location"] = init_spawn_value(
  File "c:\muddev\evennia\evennia\prototypes\prototypes.py", line 1133, in init_spawn_value
    result = protfunc_parser(value, caller=caller, prototype=prototype)
  File "c:\muddev\evennia\evennia\prototypes\prototypes.py", line 962, in protfunc_parser
    result = FUNC_PARSER.parse(value, raise_errors=True, return_str=False, caller=caller, **kwargs)
  File "c:\muddev\evennia\evennia\utils\funcparser.py", line 540, in parse
    exec_return = self.execute(
  File "c:\muddev\evennia\evennia\utils\funcparser.py", line 259, in execute
    ret = func(*args, **kwargs)
  File "c:\muddev\evennia\evennia\utils\funcparser.py", line 1170, in funcparser_callable_search_list
    return funcparser_callable_search(
  File "c:\muddev\evennia\evennia\utils\funcparser.py", line 1127, in funcparser_callable_search
    return_list = kwargs.pop("return_list", "false").lower() == "true"
AttributeError: 'bool' object has no attribute 'lower'

An untrapped error occurred.
(Traceback was logged 22-10-05 15:54:02-04).

**Comment by Sk33t3rson** [comment]
Traceback (most recent call last):
  File "c:\muddev\evennia\evennia\commands\cmdhandler.py", line 624, in _run_command
    _progressive_cmd_run(cmd, ret)
  File "c:\muddev\evennia\evennia\commands\cmdhandler.py", line 234, in _progressive_cmd_run
    value = next(generator)
  File "c:\muddev\evennia\evennia\commands\default\building.py", line 4399, in func
    for obj in spawner.spawn(prototype, caller=self.caller):
  File "c:\muddev\evennia\evennia\prototypes\spawner.py", line 950, in spawn
    create_kwargs["db_location"] = init_spawn_value(
  File "c:\muddev\evennia\evennia\prototypes\prototypes.py", line 1133, in init_spawn_value
    result = protfunc_parser(value, caller=caller, prototype=prototype)
  File "c:\muddev\evennia\evennia\prototypes\prototypes.py", line 962, in protfunc_parser
    result = FUNC_PARSER.parse(value, raise_errors=True, return_str=False, caller=caller, **kwargs)
  File "c:\muddev\evennia\evennia\utils\funcparser.py", line 540, in parse
    exec_return = self.execute(
  File "c:\muddev\evennia\evennia\utils\funcparser.py", line 259, in execute
    ret = func(*args, **kwargs)
  File "c:\muddev\evennia\evennia\utils\funcparser.py", line 877, in funcparser_callable_choice
    return random.choice(args[0])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: string index out of range

**Comment by Sk33t3rson** [comment]
> 

CRAB = {
    "key": "Large crab",
    "Attacks":["lsweep","bash","stomp"],
    "typeclass":"typeclasses.characters.Crab",
    "location": "$choice($objlist(beach, type=tag, category=zone))"
}

**Comment by Sk33t3rson** [comment]
> @Sk33t3rson What does your prototype look like?

CRAB = {
    "key": "Large crab",
    "Attacks":["lsweep","bash","stomp"],
    "typeclass":"typeclasses.characters.Crab",
    "location": "$choice($objlist(beach, type=tag, category=zone))"
}

**Comment by Sk33t3rson** [comment]
so i did some tinkering, it doesnt mean much to me but makes sense on the error now.

i did my bootleg version if seeing what comes through that kicks the error, hopefully this will help!

**prototype:**
CRAB = {
    "key": "Large crab",
    "Attacks":["lsweep","bash","stomp"],
    "typeclass":"typeclasses.characters.Crab",
    "location": '$obj($choice($objlist(beach,category=zone,type=tag)))'
}
**command:**
spawn crab

bold variables are what I had the system message me their values, now based on my observation I see that when the tag comes through its presents the return_list value, when the type value object comes through it does an object search **prototype** its like prototype isn't an object my guy! Should it be doing the object search on the **choice return** and not the **prototype**? my brain is think it should nix the prototype stuff and only hold onto the $choice results and be searching against that object

**Kwargs:** {'return_list': True, 'category': 'zone', 'type': 'tag', 'prototype': {'key': 'Large crab', 'typeclass': 'typeclasses.characters.Crab', 'location': '$obj($choice($objlist(beach,category=zone,type=tag)))', 'prototype_key': 'crab', 'prototype_tags': ['module'], 'prototype_locks': 'spawn:all();edit:all()', 'prototype_desc': '', 'attrs': [('Attacks', ['lsweep', 'bash', 'stomp'], None, '')], 'tags': []}, 'funcparser': <evennia.utils.funcparser.FuncParser object at 0x00000236167711E0>, 'raise_errors': True}
**return list:** True
**type:** tag

**Kwargs:** {'prototype': {'key': 'Large crab', 'typeclass': 'typeclasses.characters.Crab', 'location': '$obj($choice($objlist(beach,category=zone,type=tag)))', 'prototype_key': 'crab', 'prototype_tags': ['module'], 'prototype_locks': 'spawn:all();edit:all()', 'prototype_desc': '', 'attrs': [('Attacks', ['lsweep', 'bash', 'stomp'], None, '')], 'tags': []}, 'funcparser': <evennia.utils.funcparser.FuncParser object at 0x00000236167711E0>, 'raise_errors': True}
**return list:** False
**type:** obj

Traceback (most recent call last):
  File "c:\muddev\evennia\evennia\commands\cmdhandler.py", line 624, in _run_command
    _progressive_cmd_run(cmd, ret)
  File "c:\muddev\evennia\evennia\commands\cmdhandler.py", line 234, in _progressive_cmd_run
    value = next(generator)
  File "c:\muddev\evennia\evennia\commands\default\building.py", line 4399, in func
    for obj in spawner.spawn(prototype, caller=self.caller):
  File "c:\muddev\evennia\evennia\prototypes\spawner.py", line 950, in spawn
    create_kwargs["db_location"] = init_spawn_value(
  File "c:\muddev\evennia\evennia\prototypes\prototypes.py", line 1133, in init_spawn_value
    result = protfunc_parser(value, caller=caller, prototype=prototype)
  File "c:\muddev\evennia\evennia\prototypes\prototypes.py", line 962, in protfunc_parser
    result = FUNC_PARSER.parse(value, raise_errors=True, return_str=False, caller=caller, **kwargs)
  File "c:\muddev\evennia\evennia\utils\funcparser.py", line 540, in parse
    exec_return = self.execute(
  File "c:\muddev\evennia\evennia\utils\funcparser.py", line 259, in execute
    ret = func(*args, **kwargs)
  File "c:\muddev\evennia\evennia\utils\funcparser.py", line 1143, in funcparser_callable_search
    targets = search.search_object(*args, **search_kwargs)
TypeError: ObjectDBManager.search_object() got an unexpected keyword argument 'prototype'

An untrapped error occurred.
(Traceback was logged 22-10-06 10:04:30-04).

**Comment by Griatch** [comment]
The lingering issues with this should be resolved now.
