### ISSUE TITLE
[BUG - Develop] Built-in `$choice` func for funcparser seems broken

### ISSUE THREAD

**Issue by audiodude** [evennia/evennia#2910]
#### Describe the bug
Built-in `$choice` func for funcparser seems broken. Found when attempting to add tests for this (it has no tests currently).

#### To Reproduce
Attempting to add unit tests for the `$choice` function:

```
    def test_choice(self):
        string = "$choice([red, green]) apple"
        ret = self.parser.parse(string)
        self.assertIn(ret, ('red apple', 'green apple'))

    def test_choice_raise(self):
        string = "$choice([red, green]) apple"
        ret = self.parser.parse(string, raise_errors=True)
        self.assertIn(ret, ('red apple', 'green apple'))
```

Gives the following:

```
======================================================================
ERROR: test_choice_raise (evennia.utils.tests.test_funcparser.TestDefaultCallables)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tmoney/code/evennia/evennia/utils/tests/test_funcparser.py", line 544, in test_choice_raise
    ret = self.parser.parse(string, raise_errors=True)
  File "/home/tmoney/code/evennia/evennia/utils/funcparser.py", line 540, in parse
    exec_return = self.execute(
  File "/home/tmoney/code/evennia/evennia/utils/funcparser.py", line 259, in execute
    ret = func(*args, **kwargs)
  File "/home/tmoney/code/evennia/evennia/utils/funcparser.py", line 882, in funcparser_callable_choice
    args, _ = safe_convert_to_types(("py", {}), *args, **kwargs)
  File "/home/tmoney/code/evennia/evennia/utils/utils.py", line 2609, in safe_convert_to_types
    args[iarg] = converter(arg)
  File "/home/tmoney/code/evennia/evennia/utils/utils.py", line 2592, in _safe_eval
    raise ParsingError(err)
evennia.utils.funcparser.ParsingError: Errors converting '[red, green]' to python:
literal_eval raised ValueError: malformed node or string: <ast.Name object at 0x7f69b9a4d910>
simple_eval raised FeatureNotAvailable: Sorry, List is not available in this evaluator

======================================================================
FAIL: test_choice (evennia.utils.tests.test_funcparser.TestDefaultCallables)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tmoney/code/evennia/evennia/utils/tests/test_funcparser.py", line 540, in test_choice
    self.assertIn(ret, ('red apple', 'green apple'))
AssertionError: ' apple' not found in ('red apple', 'green apple')
```

#### Expected behavior
The tests pass

#### Develop-branch commit
b0f24f9975e14fddeabef06a19b5b61575957b1c

#### Additional context
The string `"$choice(red, green) apple"` also fails, and produces output `" apple"`

**Comment by Griatch** [comment]
This is actually a rather complex problem, that comes down to converting strings to Python in a safe way. I'm taking a look at it.

**Comment by Griatch** [comment]
Resolved. I also un-skipped the unit related unit tests.
