### ISSUE TITLE
[BUG - Develop] `$search` in funcparser throws wrong exception when no results found

### ISSUE THREAD

**Issue by audiodude** [evennia/evennia#2916]
#### Describe the bug
The `$search()` func should throw funcparser.ParsingError when no results found. Instead it throws NameError because the variable used in the f string is not found.

#### To Reproduce
Test:
```
    def test_search_not_found(self):
        string = "$search(foo)"
        with self.assertRaises(funcparser.ParsingError):
            self.parser.parse(string, caller=self.char1, return_str=False, raise_errors=True)

        ret = self.parser.parse(string, caller=self.char1, return_str=False, raise_errors=False)
        self.assertEqual("$search(foo)", ret)

        ret = self.parser.parse(string, caller=self.char1, return_list=True, raise_errors=False)
        self.assertEqual([], ret)
```

Result:
```
======================================================================
ERROR: test_search_not_found (evennia.utils.tests.test_funcparser.TestCallableSearch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tmoney/code/evennia/evennia/utils/tests/test_funcparser.py", line 688, in test_search_not_found
    self.parser.parse(string, caller=self.char1, return_str=False, raise_errors=True)
  File "/home/tmoney/code/evennia/evennia/utils/funcparser.py", line 540, in parse
    exec_return = self.execute(
  File "/home/tmoney/code/evennia/evennia/utils/funcparser.py", line 259, in execute
    ret = func(*args, **kwargs)
  File "/home/tmoney/code/evennia/evennia/utils/funcparser.py", line 1156, in funcparser_callable_search
    raise ParsingError(f"$search: Query '{query}' gave no matches.")
NameError: name 'query' is not defined

----------------------------------------------------------------------
```

https://github.com/evennia/evennia/blob/develop/evennia/utils/funcparser.py#L1160

#### Expected behavior
The proper ParsingError is thrown.

#### Develop-branch commit
b0f24f9975e14fddeabef06a19b5b61575957b1c

#### Additional context
This is a pretty simple bug to fix, but I'm trying to write tests to increase test coverage without modifying any code-under-test, since that confuses things. I will add the failing test with a 'skip' to demonstrate the issue, and it can be unskipped when it is fixed.

**Comment by audiodude** [comment]
Fixed in https://github.com/audiodude/evennia/tree/search-f-string
