### ISSUE TITLE
[BUG - Develop] Exception when teleporting by name

### ISSUE THREAD

**Issue by Qaishin** [evennia/evennia#2969]
#### Describe the bug
When attempting to teleport to a room by name such as "Limbo", an exception is thrown and the command fails. Teleporting by dbref works as intended.

```
Traceback (most recent call last):
  File "/home/david/muddev/evennia/evennia/commands/cmdhandler.py", line 617, in _run_command
    yield cmd.parse()
  File "/home/david/muddev/evennia/evennia/commands/default/building.py", line 3634, in parse
    self.destination = self.caller.search(self.lhs, global_search=True)
  File "/home/david/muddev/evennia/evennia/objects/objects.py", line 501, in search
    return _AT_SEARCH_RESULT(
  File "/home/david/muddev/evennia/evennia/utils/utils.py", line 2296, in at_search_result
    aliases = [alias for alias in aliases if alias.category not in ("plural_key",)]
  File "/home/david/muddev/evennia/evennia/utils/utils.py", line 2296, in <listcomp>
    aliases = [alias for alias in aliases if alias.category not in ("plural_key",)]
AttributeError: 'Tag' object has no attribute 'category'
```

#### To Reproduce
1.Type `tel Limbo`
2. See error

#### Expected behavior
The player should be teleported to a matching object or presented a list if encountering multiple matches.

#### Develop-branch commit
0eda75187

**Comment by InspectorCaracal** [comment]
Looks like this is from a very recent bugfix (probably unintentionally) removing a previous `hasattr` check, I'll put in a quick patch for it.
