### ISSUE TITLE
[BUG] MemoryError when starting Evennia

### ISSUE THREAD

**Issue by stevesmit** [evennia/evennia#3119]
#### Describe the bug
I run `evennia start` and get 
```
Portal starting ...
... Portal started.
Server starting  ...
```

This doesn't start. Inspecting logs with `evennia --log` I get the traceback:

```
2023-02-22 22:55:16 [!!] Unhandled Error
        Traceback (most recent call last):
          File "/.../fmud/env/lib/python3.10/site-packages/twisted/python/log.py", line 96, in callWithLogger
            return callWithContext({"system": lp}, func, *args, **kw)
          File "/.../fmud/env/lib/python3.10/site-packages/twisted/python/log.py", line 80, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/.../fmud/env/lib/python3.10/site-packages/twisted/python/context.py", line 117, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/.../fmud/env/lib/python3.10/site-packages/twisted/python/context.py", line 82, in callWithContext
            return func(*args, **kw)
        --- <exception caught here> ---
          File "/.../fmud/env/lib/python3.10/site-packages/twisted/internet/selectreactor.py", line 148, in _doReadOrWrite
            why = getattr(selectable, method)()
          File "/.../fmud/env/lib/python3.10/site-packages/twisted/internet/tcp.py", line 615, in doConnect
            self._connectDone()
          File "/.../fmud/env/lib/python3.10/site-packages/twisted/internet/tcp.py", line 643, in _connectDone
            self.protocol.makeConnection(self)
          File "/.../fmud/env/lib/python3.10/site-packages/evennia/server/portal/amp.py", line 449, in makeConnection
            amp.BinaryBoxProtocol.makeConnection(self, transport)
          File "/.../fmud/env/lib/python3.10/site-packages/twisted/protocols/amp.py", line 2345, in makeConnection
            self.connectionMade()
          File "/.../fmud/env/lib/python3.10/site-packages/evennia/server/amp_client.py", line 120, in connectionMade
            self.factory.server.run_initial_setup()
          File "/.../fmud/env/lib/python3.10/site-packages/evennia/server/server.py", line 362, in run_initial_setup
            last_initial_setup_step = ServerConfig.objects.conf("last_initial_setup_step")
          File "/.../fmud/env/lib/python3.10/site-packages/evennia/server/manager.py", line 50, in conf
            if not conf:
          File "/.../fmud/env/lib/python3.10/site-packages/django/db/models/query.py", line 408, in __bool__
            self._fetch_all()
          File "/.../fmud/env/lib/python3.10/site-packages/django/db/models/query.py", line 1867, in _fetch_all
            self._result_cache = list(self._iterable_class(self))
          File "/.../fmud/env/lib/python3.10/site-packages/django/db/models/query.py", line 87, in __iter__
            results = compiler.execute_sql(
          File "/.../fmud/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1398, in execute_sql
            cursor.execute(sql, params)
          File "/.../fmud/env/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
            return self._execute_with_wrappers(
          File "/.../fmud/env/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
            return executor(sql, params, many, context)
          File "/.../fmud/env/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
            return self.cursor.execute(sql, params)
          File "/.../fmud/env/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
            return Database.Cursor.execute(self, query, params)
        builtins.MemoryError: 

2023-02-22 22:55:17 [..] Server disconnected from the portal.
```

#### To Reproduce
1. Follow evennia install guide on the homepage of the site
2. See error when examining logs with evennia --log

#### Expected behavior
The server to start successfully.

#### Environment, Evennia version, OS etc
    Evennia 1.1.1
    OS: posix
    Python: 3.10.7
    Twisted: 22.10.0
    Django: 4.1.7

macOS Ventura 13.2.1, M1 2020 chip
SQLite3 version: `3.39.5 2022-10-14 20:58:05 554764a6e721fab307c63a4f98cd958c8428a5d9d8edfde951858d6fd02daapl`
#### Additional context
I have seen the other "accepted/solved" solution but this is quite a complicated approach and TBH they had the problem with an older version of sqlite, I am now 11 minor versions ahead of that used in the guide. Something else must be going on?

**Comment by stevesmit** [comment]
In the end I gave in and followed the guide [here](https://github.com/evennia/evennia/discussions/2637#discussioncomment-3630761) but tweaked it for my environment, because I use `pyenv` and don't want to clutter my machine with lots of different python installs:

1. `$ brew install sqlite` - this should install in keg-only mode so it doesn't interfere with the system sqlite binary
2. Export the relevant build arg flags so they're env vars:
```
$ export CFLAGS="-I$(brew --prefix sqlite)/include"  
$ export LDFLAGS="-L$(brew --prefix sqlite)/lib"
```
4. Build the relevant version of python with `pyenv` - `$ pyenv install 3.10.6`

Voila it should work. You can confirm that the version of sqlite that this version of python is built with is the same as that of the one just installed via brew by doing, in python:

```
import sqlite3
sqlite3.sqlite_version_info
```

and comparing to `$ sqlite3 --version` in a terminal
