### ISSUE TITLE
[BUG] Freshly installed game keeps erroring out and disconnecting (mac)

### ISSUE THREAD

**Issue by trandromeda** [evennia/evennia#3143]
#### Describe the bug
I cannot get an Evennia server to start on MacOS

#### To Reproduce
1. Git clone Evennia (up to date as of Mar 12, 2023)
2. Make a `venv` and activate it
3. `pip install -e evennia`
4. `evennia --init my-game`
5. `cd my-game`
6. `evennia migrate` - proceeds without error
7. `evennia start -l` - enter name, email, password, and then it crashes

The first time I try to start the server, I get this error:
```
❯ evennia start -l
   Tailing logfiles /Users/trandromeda/dev/evennia/evennia/tut-evennia/server/logs/server.log and portal.log (Ctrl-C to exit) ...
 [Devel: settings.IN_GAME_ERRORS is True. Turn off in production.]
 [Devel: settings.ALLOWED_HOSTS set to '*' (all). Limit in production.]
 [Devel: settings.SERVER_HOSTNAME is set to 'localhost'. Update to the actual hostname in production.]
Portal is already running as process 12366. Not restarted.
Server starting ...
[Failure instance: Traceback (failure with no frames): <class 'Exception'>: [Errno 2] No such file or directory: '/Users/trandromeda/dev/tut-evennia/server/logs/server.log' (error logged on other side)
]
```

I ctrl-c out of this, run `evennia stop` and then I need to manually kill the process e.g. `kill -9 <some_process>`, otherwise I get an address already in use error, and then try `evennia start -l` again and this error prints on a loop.

```
2023-03-12 05:00:19 [..] Server disconnected from the portal.
2023-03-12 05:00:20 [!!] Unhandled Error
	Traceback (most recent call last):
	  File "/Users/trandromeda/dev/evenv/lib/python3.11/site-packages/twisted/python/log.py", line 96, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/Users/trandromeda/dev/evenv/lib/python3.11/site-packages/twisted/python/log.py", line 80, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/Users/trandromeda/dev/evenv/lib/python3.11/site-packages/twisted/python/context.py", line 117, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/Users/trandromeda/dev/evenv/lib/python3.11/site-packages/twisted/python/context.py", line 82, in callWithContext
	    return func(*args, **kw)
	--- <exception caught here> ---
	  File "/Users/trandromeda/dev/evenv/lib/python3.11/site-packages/twisted/internet/selectreactor.py", line 148, in _doReadOrWrite
	    why = getattr(selectable, method)()
	  File "/Users/trandromeda/dev/evenv/lib/python3.11/site-packages/twisted/internet/tcp.py", line 615, in doConnect
	    self._connectDone()
	  File "/Users/trandromeda/dev/evenv/lib/python3.11/site-packages/twisted/internet/tcp.py", line 643, in _connectDone
	    self.protocol.makeConnection(self)
	  File "/Users/trandromeda/dev/evennia/evennia/server/portal/amp.py", line 449, in makeConnection
	    amp.BinaryBoxProtocol.makeConnection(self, transport)
	  File "/Users/trandromeda/dev/evenv/lib/python3.11/site-packages/twisted/protocols/amp.py", line 2345, in makeConnection
	    self.connectionMade()
	  File "/Users/trandromeda/dev/evennia/evennia/server/amp_client.py", line 120, in connectionMade
	    self.factory.server.run_initial_setup()
	  File "/Users/trandromeda/dev/evennia/evennia/server/server.py", line 362, in run_initial_setup
	    last_initial_setup_step = ServerConfig.objects.conf("last_initial_setup_step")
	  File "/Users/trandromeda/dev/evennia/evennia/server/manager.py", line 50, in conf
	    if not conf:
	  File "/Users/trandromeda/dev/evenv/lib/python3.11/site-packages/django/db/models/query.py", line 408, in __bool__
	    self._fetch_all()
	  File "/Users/trandromeda/dev/evenv/lib/python3.11/site-packages/django/db/models/query.py", line 1867, in _fetch_all
	    self._result_cache = list(self._iterable_class(self))
	  File "/Users/trandromeda/dev/evenv/lib/python3.11/site-packages/django/db/models/query.py", line 87, in __iter__
	    results = compiler.execute_sql(
	  File "/Users/trandromeda/dev/evenv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1398, in execute_sql
	    cursor.execute(sql, params)
	  File "/Users/trandromeda/dev/evenv/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
	    return self._execute_with_wrappers(
	  File "/Users/trandromeda/dev/evenv/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
	    return executor(sql, params, many, context)
	  File "/Users/trandromeda/dev/evenv/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
	    return self.cursor.execute(sql, params)
	  File "/Users/trandromeda/dev/evenv/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
	    return Database.Cursor.execute(self, query, params)
	builtins.MemoryError:
```

#### Expected behavior
Server to start and able to connect to game via web client

#### Environment, Evennia version, OS etc
    Evennia 1.2.1 (rev fd8c5abd0)
    OS: posix
    Python: 3.11.2
    Twisted: 22.10.0
    Django: 4.1.7

#### Additional context
I have been able to run Evennia before. The difference is that at the time I had a Homebrew-installed version of Python@3.11. I replaced this with Pyenv and a Pyenv-installed Python@3.11.2. However, I've also removed, re-cloned and re-installed Evennia several times before posting this issue.

These errors occur similarly in a virtual env and non-virtual env.

Further notes:
- similar errors if I install Evennia from PyPi i.e. `pip install evennia` and use that instead
- I tried reproducing these steps on another machine (WSL 2 on my PC) and got Evennia running successfully there. The versioning on the other machine was the exact same except for `Evennia 1.2.1 (rev 4ef81b5c)` instead

Update: Just realized my issue is the same (I think) as this one, so going to try and follow their solution: https://github.com/evennia/evennia/issues/3119

Update 2: Can confirm that it worked! I followed the instructions specifically `brew install sqlite` (version 3.41 when I installed it), re-installed python 3.11.2 via pyenv, and then confirmed in python interactive that the version was 3.41 matching `brew info sqlite` (`sqlite3 --version` still showed the older, system sqlite version)

**Comment by harleyndavis** [comment]
Have you tried using Python 3.10, which according to discord is the recommended python for windows due to issues.

**Comment by Griatch** [comment]
Glad it works; sounds like we need to expand our Mac troubleshooting to cover this.
