### ISSUE TITLE
[BUG] XYZGrid only functions with lowercase z-coords

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#3331]
#### Describe the bug
When attempting to use a zcoord name with any capitalization (such as the example documentation's `Dungeon of Doom`), spawning your map will fail.

```
Traceback (most recent call last):
  File ".\minenv\Scripts\evennia_launcher.py", line 7, in   File ".\minenv\lib\site-packages\evennia\server\evennia_launcher.py", line 2422, in main
    if run_custom_commands(option, *unknown_args):
  File ".\minenv\lib\site-packages\evennia\server\evennia_launcher.py", line 2026, in run_custom_commands
    command(*args)
  File ".\minenv\lib\site-packages\evennia\contrib\grid\xyzgrid\launchcmd.py", line 446, in xyzcommand
    _option_spawn(*suboptions)
  File ".\minenv\lib\site-packages\evennia\contrib\grid\xyzgrid\launchcmd.py", line 337, in _option_spawn
    grid.spawn(xyz=(x, y, z))
  File ".\minenv\lib\site-packages\evennia\contrib\grid\xyzgrid\xyzgrid.py", line 277, in spawn
    xymap.spawn_links(xy=(x, y), directions=directions)
  File ".\minenv\lib\site-packages\evennia\contrib\grid\xyzgrid\xymap.py", line 722, in spawn_links
    node.spawn_links(directions=directions)
  File ".\minenv\lib\site-packages\evennia\contrib\grid\xyzgrid\xymap_legend.py", line 416, in spawn_links
    exi, err = Typeclass.create(
  File ".\minenv\lib\site-packages\evennia\contrib\grid\xyzgrid\xyzroom.py", line 604, in create
    source = XYZRoom.objects.get_xyz(xyz=(x, y, z))
  File ".\minenv\lib\site-packages\evennia\contrib\grid\xyzgrid\xyzroom.py", line 111, in get_xyz
    raise self.model.DoesNotExist(inp)
evennia.contrib.grid.xyzgrid.xyzroom.XYZRoom.DoesNotExist: Query: xyz=(3,1,Townsburg),
```

#### To Reproduce
1. Create and test a valid XYZ grid map module
2. Change the zcoord name to anything including a capital letter
3. Attempt to create a new game map using that modified map

#### Expected behavior
It seems to be converting to lowercase when saving to the database, so it should either convert to lowercase to query as well or it should not force the original zcoord to lowercase.

**Comment by Griatch** [comment]
I made the zcoord query `__iexact`, so case-insensitive. This should fix this.
