### ISSUE TITLE
test_new_task_waiting_input failing intermittently on Windows

### ISSUE THREAD

**Issue by 0xDEADFED5** [evennia/evennia#3596]
evennia.commands.default.tests.TestCmdTasks.test_new_task_waiting_input is failing about half the time for me on Windows:

```
======================================================================
FAIL: test_new_task_waiting_input (evennia.commands.default.tests.TestCmdTasks.test_new_task_waiting_input)
Test task completing than a new task with the same ID being made while waitinf for input.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\ANON\repos\AI_Grotto\evennia\evennia\commands\default\tests.py", line 553, in test_new_task_waiting_input
    self.assertEqual(text, "Task completed while waiting for input.")
AssertionError: 'cancel request completed.The task function cancel returned: True' != 'Task completed while waiting for input.'
- cancel request completed.The task function cancel returned: True
+ Task completed while waiting for input.
----------------------------------------------------------------------
Ran 1 test in 0.463s
```
This is with a fresh venv on a freshly initialized game.  In Linux it's working fine for me.

**Comment by 0xDEADFED5** [comment]
I've looked into this a bit more, and I can't get the test to fail in the debugger.

I can catch this exception with an impressively long trace, but the test still passes:

```
Exception has occurred: _DefGen_Return       (note: full exception trace is shown but execution is paused at: _get_cmdsets)
(<commands.default_cmdsets.AccountCmdSet object at 0x0000023D80F853A0>, [<commands.default_cmdsets.AccountCmdSet object at 0x0000023D80F853A0>])
  File "C:\Users\ANON\repos\AI_Grotto\evenv\Lib\site-packages\twisted\internet\defer.py", line 1904, in returnValue
    raise _DefGen_Return(val)
  File "C:\Users\ANON\repos\AI_Grotto\evennia\evennia\commands\cmdhandler.py", line 411, in _get_cmdsets (Current frame)
    returnValue(obj.get_cmdsets(caller=caller, current=current))
  File "C:\Users\ANON\repos\AI_Grotto\evenv\Lib\site-packages\twisted\internet\defer.py", line 2000, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "C:\Users\ANON\repos\AI_Grotto\evenv\Lib\site-packages\twisted\internet\defer.py", line 2168, in _cancellableInlineCallbacks
    _inlineCallbacks(None, gen, status, _copy_context())
  File "C:\Users\ANON\repos\AI_Grotto\evenv\Lib\site-packages\twisted\internet\defer.py", line 2256, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "C:\Users\ANON\repos\AI_Grotto\evennia\evennia\commands\cmdhandler.py", line 420, in get_and_merge_cmdsets
    current, cur_cmdsets = yield _get_cmdsets(cmdobj, current_cmdset)
  File "C:\Users\ANON\repos\AI_Grotto\evenv\Lib\site-packages\twisted\internet\defer.py", line 2000, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "C:\Users\ANON\repos\AI_Grotto\evenv\Lib\site-packages\twisted\internet\defer.py", line 2168, in _cancellableInlineCallbacks
    _inlineCallbacks(None, gen, status, _copy_context())
  File "C:\Users\ANON\repos\AI_Grotto\evenv\Lib\site-packages\twisted\internet\defer.py", line 2256, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "C:\Users\ANON\repos\AI_Grotto\evennia\evennia\commands\cmdhandler.py", line 688, in cmdhandler
    cmdset = yield get_and_merge_cmdsets(
  File "C:\Users\ANON\repos\AI_Grotto\evenv\Lib\site-packages\twisted\internet\defer.py", line 2000, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "C:\Users\ANON\repos\AI_Grotto\evenv\Lib\site-packages\twisted\internet\defer.py", line 2168, in _cancellableInlineCallbacks
    _inlineCallbacks(None, gen, status, _copy_context())
  File "C:\Users\ANON\repos\AI_Grotto\evenv\Lib\site-packages\twisted\internet\defer.py", line 2256, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "C:\Users\ANON\repos\AI_Grotto\evennia\evennia\objects\objects.py", line 953, in execute_cmd
    return _CMDHANDLER(self, raw_string, callertype="object", session=session, **kwargs)
  File "C:\Users\ANON\repos\AI_Grotto\evennia\evennia\commands\default\tests.py", line 549, in test_new_task_waiting_input
    self.char1.execute_cmd("y")
  File "C:\Python312\Lib\unittest\case.py", line 589, in _callTestMethod
    if method() is not None:
  File "C:\Python312\Lib\unittest\case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "C:\Python312\Lib\unittest\case.py", line 690, in __call__
    return self.run(*args, **kwds)
  File "C:\Users\ANON\repos\AI_Grotto\evenv\Lib\site-packages\django\test\testcases.py", line 416, in _setup_and_call
    super().__call__(result)
  File "C:\Users\ANON\repos\AI_Grotto\evenv\Lib\site-packages\django\test\testcases.py", line 381, in __call__
    self._setup_and_call(result)
  File "C:\Python312\Lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Python312\Lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Python312\Lib\unittest\runner.py", line 240, in run
    test(result)
  File "C:\Users\ANON\repos\AI_Grotto\evenv\Lib\site-packages\django\test\runner.py", line 983, in run_suite
    return runner.run(suite)
  File "C:\Users\ANON\repos\AI_Grotto\evenv\Lib\site-packages\django\test\runner.py", line 1061, in run_tests
    result = self.run_suite(suite)
  File "C:\Users\ANON\repos\AI_Grotto\evenv\Lib\site-packages\django\core\management\commands\test.py", line 68, in handle
    failures = test_runner.run_tests(test_labels)
  File "C:\Users\ANON\repos\AI_Grotto\evenv\Lib\site-packages\django\core\management\base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "C:\Users\ANON\repos\AI_Grotto\evenv\Lib\site-packages\django\core\management\base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\ANON\repos\AI_Grotto\evenv\Lib\site-packages\django\core\management\commands\test.py", line 24, in run_from_argv
    super().run_from_argv(argv)
  File "C:\Users\ANON\repos\AI_Grotto\evenv\Lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\ANON\repos\AI_Grotto\evenv\Lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\Users\ANON\repos\AI_Grotto\evennia\evennia\server\evennia_launcher.py", line 2432, in main
    sys.exit(execute_from_command_line(sys.argv))
  File "C:\Users\ANON\repos\AI_Grotto\evenv\Scripts\evennia_launcher.py", line 18, in <module>
    main()
  File "C:\Python312\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "C:\Python312\Lib\runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
twisted.internet.defer._DefGen_Return: (<commands.default_cmdsets.AccountCmdSet object at 0x0000023D80F853A0>, [<commands.default_cmdsets.AccountCmdSet object at 0x0000023D80F853A0>])
```

**Comment by 0xDEADFED5** [comment]
this is resolved, i'll submit a fix
