### ISSUE TITLE
[BUG] Server unstartable after installing evennia[extra]

### ISSUE THREAD

**Issue by kenneaal** [evennia/evennia#3606]
#### Describe the bug
After installing optional site packages with pip install evennia[extra], the game became unstartable on next boot, with complaints related to database.

#### To Reproduce
1. Install and initialize an evennia game with just pip install evennia. I use Postgres DB backend
2. Run pip install evennia[extra]
3. Restart the game. 

#### Expected behavior
Normal game start

#### Environment, Evennia version, OS etc
    Evennia 4.3.0
    OS: posix
    Python: 3.12.3
    Twisted: 23.10.0
    Django: 4.2.15

#### Additional context
server.log
`2024-09-02 20:53:54 [..] Attempting to reconnect to Portal ...
2024-09-02 20:54:00 [!!] Unhandled Error
        Traceback (most recent call last):
          File "/home/kenneaal/evennia/venv/lib/python3.12/site-packages/twisted/python/log.py", line 96, in callWithLogger
            return callWithContext({"system": lp}, func, *args, **kw)
          File "/home/kenneaal/evennia/venv/lib/python3.12/site-packages/twisted/python/log.py", line 80, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/home/kenneaal/evennia/venv/lib/python3.12/site-packages/twisted/python/context.py", line 117, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/home/kenneaal/evennia/venv/lib/python3.12/site-packages/twisted/python/context.py", line 82, in callWithContext
            return func(*args, **kw)
        --- <exception caught here> ---
          File "/home/kenneaal/evennia/venv/lib/python3.12/site-packages/twisted/internet/posixbase.py", line 487, in _doReadOrWrite
            why = selectable.doWrite()
          File "/home/kenneaal/evennia/venv/lib/python3.12/site-packages/twisted/internet/tcp.py", line 615, in doConnect
            self._connectDone()
          File "/home/kenneaal/evennia/venv/lib/python3.12/site-packages/twisted/internet/tcp.py", line 643, in _connectDone
            self.protocol.makeConnection(self)
          File "/home/kenneaal/evennia/venv/lib/python3.12/site-packages/evennia/server/portal/amp.py", line 449, in makeConnection
            amp.BinaryBoxProtocol.makeConnection(self, transport)
          File "/home/kenneaal/evennia/venv/lib/python3.12/site-packages/twisted/protocols/amp.py", line 2348, in makeConnection
            self.connectionMade()
          File "/home/kenneaal/evennia/venv/lib/python3.12/site-packages/evennia/server/amp_client.py", line 121, in connectionMade
            self.factory.server.run_initial_setup()
          File "/home/kenneaal/evennia/venv/lib/python3.12/site-packages/evennia/server/service.py", line 391, in run_initial_setup
            last_initial_setup_step = evennia.ServerConfig.objects.conf("last_initial_setup_step")
          File "/home/kenneaal/evennia/venv/lib/python3.12/site-packages/evennia/server/manager.py", line 51, in conf
            if not conf:
          File "/home/kenneaal/evennia/venv/lib/python3.12/site-packages/django/db/models/query.py", line 412, in __bool__
            self._fetch_all()
          File "/home/kenneaal/evennia/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1881, in _fetch_all
            self._result_cache = list(self._iterable_class(self))
          File "/home/kenneaal/evennia/venv/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
            results = compiler.execute_sql(
          File "/home/kenneaal/evennia/venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1560, in execute_sql
            cursor = self.connection.cursor()
          File "/home/kenneaal/evennia/venv/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
            return func(*args, **kwargs)
          File "/home/kenneaal/evennia/venv/lib/python3.12/site-packages/django/db/backends/base/base.py", line 330, in cursor
            return self._cursor()
          File "/home/kenneaal/evennia/venv/lib/python3.12/site-packages/django/db/backends/base/base.py", line 307, in _cursor
            with self.wrap_database_errors:
          File "/home/kenneaal/evennia/venv/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
            raise dj_exc_value.with_traceback(traceback) from exc_value
          File "/home/kenneaal/evennia/venv/lib/python3.12/site-packages/django/db/backends/base/base.py", line 308, in _cursor
            return self._prepare_cursor(self.create_cursor(name))
          File "/home/kenneaal/evennia/venv/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
            return func(*args, **kwargs)
          File "/home/kenneaal/evennia/venv/lib/python3.12/site-packages/django/db/backends/postgresql/base.py", line 330, in create_cursor
            cursor = self.connection.cursor()
        django.db.utils.InterfaceError: connection already closed
`

**Comment by kenneaal** [comment]
No, I did not make any changes requiring restarts before this. And yes, I have verified that the database is up and running, and accessible with the provided credentials.

**Comment by Griatch** [comment]
@kenneaal Hm, this is not reproducible on sqlite3 so could be a postgres related issue. I presume you have actually fully shut down the server (`evennia stop` or `evennia reboot`) and not just done `evennia reload` when seeing this?

**Comment by kenneaal** [comment]
@Griatch Yes, full restarts for both the Postgresql server and Evennia have been attempted. (Evennia has to be killed, as the script fails to stop the server when it is in this state)

**Comment by Griatch** [comment]
Can't reproduce this. @aMiss-aWry, I know you are using postgres, have you faced any issues installing `evennia[extra]`?
