### ISSUE TITLE
[BUG] `batch_update_objects_with_prototype` doesn't fully update typeclass

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#3607]
#### Describe the bug
I have a function which will "transform" one object into another by using `batch_update_objects_with_prototype` to apply a different prototype to it. However, it seems as though this function does not actually change the *active* typeclass of the object into the new one.

Here is how one such modified object looks before a server reload:
```
Name/key: mysterious object (#555)
Typeclass: GrabbableCharacter (typeclasses.usable.EffectOnUse)
```
(The full typeclass before running the function was `typeclasses.characters.GrabbableCharacter`)

Trying to use the object - which should at this point be usable, as `EffectOnUse` is - results in a traceback indicating it is still indeed using the `GrabbableCharacter` class:
```
Traceback (most recent call last):
  File "./evgames/dungeons-and-potions/venv/lib/python3.11/site-packages/evennia/commands/cmdhandler.py", line 629, in _run_command
    ret = cmd.func()
          ^^^^^^^^^^
  File "./evgames/dungeons-and-potions/commands/interact.py", line 1001, in func
    target.at_use(self.caller)
    ^^^^^^^^^^^^^
AttributeError: 'GrabbableCharacter' object has no attribute 'at_use'
```

After a reload, it loads the changed typeclass, as expected:
```
Name/key: mysterious object (#555)
Typeclass: EffectOnUse (typeclasses.usable.EffectOnUse)
```
and my USE command works on it as expected.

#### Expected behavior
I'd expect the function to modify the objects passed to it in a way that leaves them in a consistent state with their data.

#### Environment, Evennia version, OS etc
Evennia 4.3.0

#### Additional context
While my particular use-case is a bit unusual, changing the typeclass of a prototype is something I'd expect to happen in normal use - e.g. if you decided to split edible and drinkable consumables into their own typeclasses - and so should be working properly without requiring an entire server reload.

**Comment by aMiss-aWry** [comment]
What is the code that you use (originally) to update the typeclass in question, when you don't use `swap_typeclass`?

**Comment by aMiss-aWry** [comment]
Possibly helpful for you:
https://www.evennia.com/docs/latest/Components/Typeclasses.html#caveats
```
Evennia uses the idmapper to cache its typeclasses (Django proxy models) in memory. The idmapper allows things like on-object handlers and properties to be stored on typeclass instances and to not get lost as long as the server is running (they will only be cleared on a Server reload). Django does not work like this by default; by default every time you search for an object in the database you’ll get a different instance of that object back and anything you stored on it that was not in the database would be lost. The bottom line is that Evennia’s Typeclass instances subside in memory a lot longer than vanilla Django model instance do.
```

The operative code in `swap_typeclass`:

```
self.typeclass_path = new_typeclass.path
self.__class__ = new_typeclass
```

https://www.evennia.com/docs/latest/_modules/evennia/typeclasses/models.html#TypedObject.swap_typeclass

**Comment by InspectorCaracal** [comment]
> What is the code that you use (originally) to update the typeclass in question, when you don't use `swap_typeclass`?

It's just the titular function. 
`batch_update_objects_with_prototype(choice(trick_or_treat), objects=[ghost], exact=True)`

**Comment by Griatch** [comment]
This works for the general prototype build menu; there could be a cache refresh that is lost somewhere then.

**Comment by InspectorCaracal** [comment]
@Griatch Unfortunately, when I went to investigate the difference between how the OLC works and what I did, I discovered that it has the exact same issue.

To make sure it wasn't anything weird involving swapping from a Character to an Object, I made two basic new typeclasses, `ObjectOne` and `ObjectTwo`. I then created a new prototype using the OLC, with the typeclass ObjectOne, spawned an object, and used the OLC again to change the typeclass to ObjectTwo.

The result has the same issue: the typeclass data is changed, but the active typeclass is not.

```
Name/key: test thing (#4)
Aliases: a test thing,one test thing
Typeclass: ObjectOne (typeclasses.objects.ObjectTwo)
```
