### ISSUE TITLE
[BUG] With postgres as the db, searching objects by tag results in an error when the given tag is an integer.

### ISSUE THREAD

**Issue by aMiss-aWry** [evennia/evennia#3624]
#### Describe the bug
Trying to search objects (or presumably any model) by tag fails in postgres when the tag given is an integer rather than a string.

Error: `django.db.utils.ProgrammingError: function upper(integer) does not exist`
`LINE 1: ...R('test_category') AND UPPER(U0."db_key"::text) = UPPER(1)))...`

#### To Reproduce
1. Use a postgres db. [Steps to follow in docs](https://www.evennia.com/docs/latest/Setup/Choosing-a-Database.html)
2. Input in-game with `py` access:
```
py/edit
from evennia.utils.search import search_tag
objs = search_tag(1, "test_category")
self.msg(objs)
:wq
```
3. See traceback.

#### Expected behavior
Search should return results or lack thereof.

#### Environment, Evennia version, OS etc
```
         Evennia version: 4.3.0 (rev 389a212c63)
         OS: posix
         Python: 3.11.9
         Twisted: 23.10.0
         Django: 4.2.13
```
DB version:
```
select version();
 PostgreSQL 14.13 (Homebrew) on aarch64-apple-darwin23.4.0, compiled by Apple clang version 15.0.0 (clang-1500.3.9.4), 64-bit
```

#### Additional context
This is relatively easily resolved on my side by surrounding all relevant search_tag args in str() e.g. `search_tag(str(id))`, but the behavior differs from sqlite3 and I think that as postgres is a [suggested supported db](https://www.evennia.com/docs/latest/Setup/Choosing-a-Database.html) it should behave the same way.

I confirmed this issue doesn't exist in sqlite3.

*The real problem is a difference in behavior between SQL and postgres* - UPPER() in SQL is a no-op on integers: `SELECT UPPER(12);` results in `12`, while in postgres `SELECT UPPER(12);` results in `ERROR:  function upper(integer) does not exist`.  Unfortunately that filters down to us (or maybe this is a django problem I can't deal with).

Maybe a resolution is casting tags to strings somewhere else along the way? We do a lot of that in the tags class anyway: https://github.com/evennia/evennia/blob/f2a5c5a85a7858b24141b8ddbb79ff16eb390308/evennia/typeclasses/tags.py#L375C15-L375C19

Full traceback:
```
2024-09-23 22:24:45 [!!] Traceback (most recent call last):
2024-09-23 22:24:45 [!!]   File "redacted/evennia/evennia/commands/cmdhandler.py", line 629, in _run_command
2024-09-23 22:24:45 [!!]     ret = cmd.func()
2024-09-23 22:24:45 [!!]           ^^^^^^^^^^
2024-09-23 22:24:45 [!!]   File "redacted/gardenmud/commands/admin/admin_commands.py", line 235, in func
2024-09-23 22:24:45 [!!]     if watching:
2024-09-23 22:24:45 [!!]   File "redacted/evenv/lib/python3.11/site-packages/django/db/models/query.py", line 412, in __bool__
2024-09-23 22:24:45 [!!]     self._fetch_all()
2024-09-23 22:24:45 [!!]   File "redacted/evenv/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
2024-09-23 22:24:45 [!!]     self._result_cache = list(self._iterable_class(self))
2024-09-23 22:24:45 [!!]                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-23 22:24:45 [!!]   File "redacted/evenv/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
2024-09-23 22:24:45 [!!]     results = compiler.execute_sql(
2024-09-23 22:24:45 [!!]               ^^^^^^^^^^^^^^^^^^^^^
2024-09-23 22:24:45 [!!]   File "redacted/evenv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
2024-09-23 22:24:45 [!!]     cursor.execute(sql, params)
2024-09-23 22:24:45 [!!]   File "redacted/evenv/lib/python3.11/site-packages/django/db/backends/utils.py", line 102, in execute
2024-09-23 22:24:45 [!!]     return super().execute(sql, params)
2024-09-23 22:24:45 [!!]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-23 22:24:45 [!!]   File "redacted/evenv/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
2024-09-23 22:24:45 [!!]     return self._execute_with_wrappers(
2024-09-23 22:24:45 [!!]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-23 22:24:45 [!!]   File "redacted/evenv/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
2024-09-23 22:24:45 [!!]     return executor(sql, params, many, context)
2024-09-23 22:24:45 [!!]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-23 22:24:45 [!!]   File "redacted/evenv/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
2024-09-23 22:24:45 [!!]     with self.db.wrap_database_errors:
2024-09-23 22:24:45 [!!]   File "redacted/evenv/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
2024-09-23 22:24:45 [!!]     raise dj_exc_value.with_traceback(traceback) from exc_value
2024-09-23 22:24:45 [!!]   File "redacted/evenv/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
2024-09-23 22:24:45 [!!]     return self.cursor.execute(sql, params)
2024-09-23 22:24:45 [!!]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-23 22:24:45 [!!] django.db.utils.ProgrammingError: function upper(integer) does not exist
2024-09-23 22:24:45 [!!] LINE 1: ...R('test_category') AND UPPER(U0."db_key"::text) = UPPER(1...
2024-09-23 22:24:45 [!!]                                                              ^
2024-09-23 22:24:45 [!!] HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

**Comment by aMiss-aWry** [comment]
The same issue (with 'record' rather than 'int') is happening with `prototypes.search_prototype()`

```
2024-09-25 16:20:36 [!!]   File ".../gardenmud/commands/admin/building.py", line 1476, in func
2024-09-25 16:20:36 [!!]     environ_tagged = search_prototype(tags=[(cur_environ, "environ")])
2024-09-25 16:20:36 [!!]                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-25 16:20:36 [!!]   File ".../evennia/evennia/prototypes/prototypes.py", line 665, in search_prototype
2024-09-25 16:20:36 [!!]     db_prototypes = [] if no_db else _search_db_based_prototypes(key, tags, fuzzy_match_db)
2024-09-25 16:20:36 [!!]                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-25 16:20:36 [!!]   File ".../evennia/evennia/prototypes/prototypes.py", line 641, in _search_db_based_prototypes
2024-09-25 16:20:36 [!!]     for db_id in query.values_list("id", flat=True).order_by("db_key"):
2024-09-25 16:20:36 [!!]   File ".../evenv/lib/python3.11/site-packages/django/db/models/query.py", line 398, in __iter__
2024-09-25 16:20:36 [!!]     self._fetch_all()
2024-09-25 16:20:36 [!!]   File ".../evenv/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
2024-09-25 16:20:36 [!!]     self._result_cache = list(self._iterable_class(self))
2024-09-25 16:20:36 [!!]                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-25 16:20:36 [!!]   File ".../evenv/lib/python3.11/site-packages/django/db/models/query.py", line 285, in __iter__
2024-09-25 16:20:36 [!!]     for row in compiler.results_iter(
2024-09-25 16:20:36 [!!]                ^^^^^^^^^^^^^^^^^^^^^^
2024-09-25 16:20:36 [!!]   File ".../evenv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1513, in results_iter
2024-09-25 16:20:36 [!!]     results = self.execute_sql(
2024-09-25 16:20:36 [!!]               ^^^^^^^^^^^^^^^^^
2024-09-25 16:20:36 [!!]   File ".../evenv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
2024-09-25 16:20:36 [!!]     cursor.execute(sql, params)
2024-09-25 16:20:36 [!!]   File ".../evenv/lib/python3.11/site-packages/django/db/backends/utils.py", line 102, in execute
2024-09-25 16:20:36 [!!]     return super().execute(sql, params)
2024-09-25 16:20:36 [!!]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-25 16:20:36 [!!]   File ".../evenv/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
2024-09-25 16:20:36 [!!]     return self._execute_with_wrappers(
2024-09-25 16:20:36 [!!]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-25 16:20:36 [!!]   File ".../evenv/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
2024-09-25 16:20:36 [!!]     return executor(sql, params, many, context)
2024-09-25 16:20:36 [!!]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-25 16:20:36 [!!]   File ".../evenv/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
2024-09-25 16:20:36 [!!]     with self.db.wrap_database_errors:
2024-09-25 16:20:36 [!!]   File ".../evenv/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
2024-09-25 16:20:36 [!!]     raise dj_exc_value.with_traceback(traceback) from exc_value
2024-09-25 16:20:36 [!!]   File ".../evenv/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
2024-09-25 16:20:36 [!!]     return self.cursor.execute(sql, params)
2024-09-25 16:20:36 [!!]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-25 16:20:36 [!!] django.db.utils.ProgrammingError: function upper(record) does not exist
2024-09-25 16:20:36 [!!] LINE 1: ...ER('db_prototype') AND UPPER(U0."db_key"::text) = UPPER(('in...
2024-09-25 16:20:36 [!!]                                                              ^
2024-09-25 16:20:36 [!!] HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

This one was a little more confusing. It's hitting the same problem as the issue above. I ultimately fixed it locally by tacking on a string casting https://github.com/evennia/evennia/blob/main/evennia/prototypes/prototypes.py#L620-L622 ->
```
        if tags:
            # exact match on tag(s)
            tags = make_iter(tags)
            tags = [str(tag) for tag in tags] 
```
(which I don't think is great)

**Comment by InspectorCaracal** [comment]
Tags are - or at least should be - cast to strings when being added to the db, yeah. In fact, ime they're forcibly lowercased, too.

The fact that the *search terms* being passed into the queries aren't being similarly cast is definitely a problem. I'll test if similar issues arise in mysql

**Comment by InspectorCaracal** [comment]
Follow-up: my game backed with mysql (or at least mariadb, which is typically equivalent) gracefully handles the following with no issues, so I think it might be down to Django's query generation like you suggested:

- passing an integer as the search term to `search_tag`
- retrieving integer tags with `obj.tags.get(category="test")` and using the returned value in `search_tag`
- passing an object's attribute containing an integer directly in as the argument, `search_tag(obj.db.test)`, for both strings and ints

**Comment by Griatch** [comment]
A few of the core taghandler methods were missing the key string cast. Also added a few missing casts to `category` while I was at it.

**Comment by Griatch** [comment]
Reopening this again, my fix came with unexpected side effects, so had to revert it and need to look at this more carefully.

**Comment by aMiss-aWry** [comment]
I no longer get this problem after adding `tags = [str(tag) for tag in tags]` right after https://github.com/evennia/evennia/blob/main/evennia/prototypes/prototypes.py#L622

I'm loathe to suggest that as a proper solution but if anyone else has this problem and finds this issue before it's fixed, try that.
