### ISSUE TITLE
[BUG] `EvMore` system can cause tracebacks when given Account caller

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#3641]
#### Describe the bug
When an `EvMore` object is created for an account when that player is puppeting a character, the auto-exit function completely breaks.

The `EvMore` pager relies on the system cmd nomatch handling to catch commands that are not pager commands and, when such commands are caught, to close the pager. The problem arises because the caller for the nomatch isn't the account - it's the puppeted character, which doesn't have the `EvMore` object's NAttribute set.

#### To Reproduce
1. Log into a character
2. `py from evennia.utils.evmore import EvMore; EvMore(self.account, "text", self.sessions.all()[0])`
3. `look`

#### Expected behavior
Since this can easily be caused by any command that uses `account_caller = True` and a pager, it should most likely handle the discrepancy more gracefully than a traceback.

#### Environment, Evennia version, OS etc
Evennia 4.4.1

#### Additional context
Full traceback:
```
Traceback (most recent call last):
  File "./testgame/venv/lib/python3.11/site-packages/evennia/commands/cmdhandler.py", line 755, in cmdhandler
    raise ExecSystemCommand(syscmd, sysarg)
evennia.commands.cmdhandler.ExecSystemCommand: (<evennia.utils.evmore.CmdMoreExit object at 0x7f801747e1d0>, 'l')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./testgame/venv/lib/python3.11/site-packages/evennia/commands/cmdhandler.py", line 629, in _run_command
    ret = cmd.func()
          ^^^^^^^^^^
  File "./testgame/venv/lib/python3.11/site-packages/evennia/utils/evmore.py", line 117, in func
    more.page_quit()
    ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'page_quit'

An untrapped error occurred.
(Traceback was logged 24-10-11 22:23:57).
Traceback (most recent call last):
  File "./testgame/venv/lib/python3.11/site-packages/evennia/commands/cmdhandler.py", line 755, in cmdhandler
    raise ExecSystemCommand(syscmd, sysarg)
evennia.commands.cmdhandler.ExecSystemCommand: (<evennia.utils.evmore.CmdMoreExit object at 0x7f801747e1d0>, 'l')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./testgame/venv/lib/python3.11/site-packages/evennia/commands/cmdhandler.py", line 779, in cmdhandler
    ret = yield _run_command(
          ^^^^^^^^^^^^^^^^^^^
evennia.commands.cmdhandler.ErrorReported: l

A command handler bug occurred. If this is not due to a local change,
please file a bug report with the Evennia project, including the
traceback and steps to reproduce.
(Traceback was logged 24-10-11 22:23:57).
```

**Comment by InspectorCaracal** [comment]
I saw how `CmdMore` was already solving this problem literally five seconds after filing the issue, so I went ahead and fixed it :laughing:
