### ISSUE TITLE
MySQL timeout Issue: 'mysql server has gone away'

### ISSUE THREAD

**Issue by Antrare** [evennia/evennia#619]
I have to manually stop/start the Evennia server to get it back up and running.  As no action is required with MySQL leads me to believe the issue is not there.

2014-11-20 13:56:57+0000 [AMPProtocol,0,127.0.0.1] [::] Traceback (most recent call last):
2014-11-20 13:56:57+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/root/evennia/src/commands/cmdhandler.py", line 393, in cmdhandler
2014-11-20 13:56:57+0000 [AMPProtocol,0,127.0.0.1] [::]     yield cmd.obj.scripts.validate()
2014-11-20 13:56:57+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/root/evennia/src/scripts/scripthandler.py", line 125, in validate
2014-11-20 13:56:57+0000 [AMPProtocol,0,127.0.0.1] [::]     ScriptDB.objects.validate(obj=self.obj, init_mode=init_mode)
2014-11-20 13:56:57+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/root/evennia/src/scripts/manager.py", line 172, in validate
2014-11-20 13:56:57+0000 [AMPProtocol,0,127.0.0.1] [::]     scripts = self.get_all_scripts_on_obj(obj, key=key)
2014-11-20 13:56:57+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/root/evennia/src/typeclasses/managers.py", line 30, in func
2014-11-20 13:56:57+0000 [AMPProtocol,0,127.0.0.1] [::]     for dbobj in make_iter(matches)]
2014-11-20 13:56:57+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 141, in __iter__
2014-11-20 13:56:57+0000 [AMPProtocol,0,127.0.0.1] [::]     self._fetch_all()
2014-11-20 13:56:57+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 966, in _fetch_all
2014-11-20 13:56:57+0000 [AMPProtocol,0,127.0.0.1] [::]     self._result_cache = list(self.iterator())
2014-11-20 13:56:57+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 265, in iterator
2014-11-20 13:56:57+0000 [AMPProtocol,0,127.0.0.1] [::]     for row in compiler.results_iter():
2014-11-20 13:56:57+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 700, in results_iter
2014-11-20 13:56:57+0000 [AMPProtocol,0,127.0.0.1] [::]     for rows in self.execute_sql(MULTI):
2014-11-20 13:56:57+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
2014-11-20 13:56:57+0000 [AMPProtocol,0,127.0.0.1] [::]     cursor.execute(sql, params)
2014-11-20 13:56:57+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 65, in execute
2014-11-20 13:56:57+0000 [AMPProtocol,0,127.0.0.1] [::]     return self.cursor.execute(sql, params)
2014-11-20 13:56:57+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
2014-11-20 13:56:57+0000 [AMPProtocol,0,127.0.0.1] [::]     six.reraise(dj_exc_type, dj_exc_value, traceback)
2014-11-20 13:56:57+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 65, in execute
2014-11-20 13:56:57+0000 [AMPProtocol,0,127.0.0.1] [::]     return self.cursor.execute(sql, params)
2014-11-20 13:56:57+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 128, in execute
2014-11-20 13:56:57+0000 [AMPProtocol,0,127.0.0.1] [::]     return self.cursor.execute(query, args)
2014-11-20 13:56:57+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 205, in execute
2014-11-20 13:56:57+0000 [AMPProtocol,0,127.0.0.1] [::]     self.errorhandler(self, exc, value)
2014-11-20 13:56:57+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
2014-11-20 13:56:57+0000 [AMPProtocol,0,127.0.0.1] [::]     raise errorclass, errorvalue
2014-11-20 13:56:57+0000 [AMPProtocol,0,127.0.0.1] [::] OperationalError: (2006, 'MySQL server has gone away')
2014-11-20 13:56:57+0000 [AMPProtocol,0,127.0.0.1] [EE] %s
2014-11-20 13:56:57+0000 [AMPProtocol,0,127.0.0.1] [EE] Above traceback is from an untrapped error. Please file a bug report.
2014-11-20 14:36:02+0000 [AMPProtocol,0,127.0.0.1] [::] Traceback (most recent call last):

**Comment by Griatch** [comment]
I recently saw this error on devel, again running mysql. I wonder if one can catch it and force a re-connect somehow. Or at least codedly increase the timeout.

**Comment by Griatch** [comment]
I guess adding the recommended Django solution is the way to go: https://code.djangoproject.com/ticket/21597#comment:29
