### ISSUE TITLE
Strange traceback with character.msg()

### ISSUE THREAD

**Issue by volundmush** [evennia/evennia#630]
I'm getting a double Traceback (see below) with my new upgraded channels. Since this bug is in the models and waaaay past my ability to grok, I'm asking for some help!

My distribute_message is only slightly different from normal:
```python
    def distribute_message(self, msg, online=False):
        """
        Method for grabbing all listeners that a message should be sent to on
        this channel, and sending them a message.
        """
        # get all characters connected to this channel and send to them
        subs = self.dbobj.sub_characters.all()
        for subscription in subs:
            character = subscription.cobj.typeclass
            try:
                character.msg(msg.message, from_obj=msg.senders, from_channel=self.id)
            except AttributeError, e:
                logger.log_trace("%s\nCannot send msg to player '%s'." % (e, character))
        # Evennia default included to account for chat bots, etc.
        for player in self.dbobj.db_subscriptions.all():
            player = player.typeclass
            try:
                # note our addition of the from_channel keyword here. This could be checked
                # by a custom player.msg() to treat channel-receives differently.
                player.msg(msg.message, from_obj=msg.senders, from_channel=self.id)
            except AttributeError, e:
                logger.log_trace("%s\nCannot send msg to player '%s'." % (e, player))
```
```python
 Traceback (most recent call last):
   File "/home/mouvar/PycharmProjects/evennia/src/objects/models.py", line 548, in msg
     _GA(from_obj, "at_msg_send")(text=text, to_obj=_GA(self, "typeclass"), **kwargs)
 AttributeError: 'list' object has no attribute 'at_msg_send'
 Traceback (most recent call last):
   File "/home/mouvar/PycharmProjects/evennia/src/objects/models.py", line 548, in msg
     _GA(from_obj, "at_msg_send")(text=text, to_obj=_GA(self, "typeclass"), **kwargs)
AttributeError: 'list' object has no attribute 'at_msg_send'
```

**Comment by Griatch** [comment]
From the traceback: The `from_obj` keyword of `msg()` allows only one single sender, you are sending it a list of senders. Skip the `from_obj` keyword and call `sender.at_msg_send()` manually on each sender if you really want every single one of them to have that hook triggered every multi-message.
