### ISSUE TITLE
Devel: Msg not accepting Characters as sender

### ISSUE THREAD

**Issue by volundmush** [evennia/evennia#639]
This happens when I try to use a Character Object as a sender for a Channel.

```python
Traceback (most recent call last):
  File "/home/mouvar/PycharmProjects/evennia/evennia/commands/cmdhandler.py", line 452, in cmdhandler
    yield syscmd.func()
  File "/home/mouvar/PycharmProjects/evemush/commands/wildmatch.py", line 45, in func
    self.send_to_channel(cstr, switches, args)
  File "/home/mouvar/PycharmProjects/evemush/commands/wildmatch.py", line 65, in send_to_channel
    channel.send_message(self.character, text)
  File "/home/mouvar/PycharmProjects/evemush/typeclasses/channels.py", line 74, in send_message
    message = create_message(character, text, channels=self)
  File "/home/mouvar/PycharmProjects/evennia/evennia/utils/create.py", line 260, in create_message
    new_message.senders = sender
  File "/home/mouvar/PycharmProjects/evennia/evennia/comms/models.py", line 134, in __senders_set
    self.db_sender_players.add(obj)
  File "/home/mouvar/evenenv/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 921, in add
    self._add_items(self.source_field_name, self.target_field_name, *objs)
  File "/home/mouvar/evenenv/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 1015, in _add_items
    (self.model._meta.object_name, obj)
TypeError: 'PlayerDB' instance expected, got <Character: root>
```

As far as I can tell, the problem is located in evennia.comms.managers under identify_object. it's not returning the proper output that Msg.__senders_set is expecting and mistakes a Character for a Player.

This likely has to do with the new typeclass system but I'm not entirely sure how this thing works so don't feel brave enough to futz with it myself.

**Comment by volundmush** [comment]
Would it not be simpler, rather than making a function to try and pin down what an object is, to have the object itself report that?

for instance:

```python
@property
def base_typeclass(self):
    return 'player'
```

Something like that on each major typeclass?

**Comment by Griatch** [comment]
This is already present in the form of obj.__class__ (e.g. Object) and obj.__dbclass__ (ObjectDB).

**Comment by volundmush** [comment]
Shows what I know.

I just think the way identify_object is doing it seems weird? But really what do I know? :(

Either way that part isn't quite working right!

**Comment by Griatch** [comment]
No, you are correct, Msg() was not modified at all up to this point and the way it determines type is no longer the way to do in in devel.

**Comment by Griatch** [comment]
... Besides, there is no way for you to know about `__dbclass__` since it's new in devel and I've not documented it anywhere (yet). :)
