### ISSUE TITLE
(devel) Can not run evennia --init <PATH> in upper level

### ISSUE THREAD

**Issue by luyijun** [evennia/evennia#650]
I downloaded the latest devel codes. I went to the upper level (I put codes in ```/Python/devel/``` and I went to ```/Python/```), and ran ```evennia --init game```, but it showed:
```
Traceback (most recent call last):
  File "/Python/env/bin/evennia", line 10, in <module>
    execfile(__file__)
  File "/Python/devel/bin/unix/evennia", line 13, in <module>
    from  evennia.server.evennia_launcher import main
ImportError: No module named server.evennia_launcher
```
I could use this command in previous version (before ```/bin/evenia``` moved to ```/bin/unix/evennia```). And in current version, this command works in other directories, for example in ```/Python/test/``` or a directory faraway from evennia's directory. It's strange.

**Comment by Griatch** [comment]
Your virtualenv may still point to the old files, before the move of the launcher. Have you tried uninstalling evennia (pip uninstall evennia) and then reinstalling it (pip install evennia . -e)? 

Since we are using -e, If fond that there may be some symlinking issues that are not showing up when using the normal pip install. So after uninstalling it may be a good idea to go into your virtualenv's bin/ and lib/ directories and make sure there is nothing named evennia remaining in there.

**Comment by luyijun** [comment]
I uninstalled evennia, removed evennia files in virtualenv, and even created a new virtualenv and redownloaded codes to a clean directory, I still got this error.

**Comment by luyijun** [comment]
I found the reason. I put the devel branch codes in ```/Python/devel/``` and the master branch codes in ```/Python/evennia/```. When I call ```evennia --init game``` in ```/Python/```, the Python path ```evennia.server.evennia_launcher``` points to ```/Python/evennia/``` instead of ```/Python/devel/evennia```, so I get errors.

**Comment by Griatch** [comment]
I see, you have a folder `evennia` (master) that contains an `__init__.py`, which Python thus looks to first when trying to locate the evennia package during initialization (Python always starts in the same directory). 
I can see why this can be confusing, but you are basically tricking the evennia launcher to use another library than it should. I don't think one can deactivate the fact that Python first looks in the current directory for a module/package and then in `sys.path` ... will need to ponder that, but good to know what causes it.

**Comment by luyijun** [comment]
I think it's ```sys.path.insert(0, os.path.abspath(os.getcwd()))``` in ```/bin/unix/evennia``` line 11 who adds current working path to ```sys.path```. I comment this line out, and the problem is solved.

**Comment by Griatch** [comment]
Not sure that works reliably everywhere and on Windows. At least I seem to recall I had to add that for a good reason. Would need to test.

**Comment by luyijun** [comment]
I think remove ```sys.path.insert(0, os.path.abspath(os.getcwd()))``` in ```/bin/unix/evennia``` is safe, because ```/evennia/server/evennia_launcher.py```'s main function calls ```init_game_directory(CURRENT_DIR, check_db=check_db)``` (line 886) and ```init_game_directory``` calls ```sys.path.insert(1, GAMEDIR)``` (line 601), the current working directory is still added.

**Comment by Griatch** [comment]
Testing this both with -e install and full install still seems to work. Ok, so removed it. It seems to still be necessary for -e installs on Windows though, might remove it later. Merged and closed (github does not auto-close devel-branch issues).
