### ISSUE TITLE
Bug: Subclass of DefaultObject kwargs issue

### ISSUE THREAD

**Issue by ear7631** [evennia/evennia#669]
#### Steps to reproduce the issue:

1. Create a clean environment, installation, and game world
2. Put the following script in your world directory: [link](http://pastebin.com/5maHYDpz)
3. Log in, run:  @batchcode myobjs

#### What I expect to see and what I actually see (tracebacks, error messages etc):

Expected to see "All done" sent back, and a lever object.
```
Running Batch-code processor - Automatic mode for myobjs ...
01/01: #CODE : \nfrom evennia import DefaultObject\nclass MyObj([...]
03: except RuntimeError: pass
04: finally: del settings_module
05: #CODE : 
06: from evennia import DefaultObject
07: class MyObj(DefaultObject):
08:     def at_object_creation(self):
09:         desc = "A large brass lever is attached to the platform, connected to an intricate " +\
10:         "array of interconnected machinery."
11:         self.db.desc = descTraceback (most recent call last):

	File "&lt;string&gt;", line 7, in &lt;module&gt;

	File "/Users/redacted/Code/evennia_clean/evennia/evennia/typeclasses/models.py", 
line 108, in __new__
	new_class = patched_new(cls, name, bases, attrs)

	File "/Users/redacted/Code/evennia_clean/evennia/evennia/typeclasses/django_new_patch.py", line 83, 
in patched_new
	kwargs = {"app_label": package_components[app_label_index]}

	IndexError: list index out of range
```

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve:
OSX, latest version of devel

**Comment by ear7631** [comment]
Not a real issue.

Typeclass definitions must exist in python modules on the actual file system. Do NOT declare a new typeclass in a batchcode script - do it in the proper place (/gamedirectory/typeclasses/) and import it.
