### ISSUE TITLE
@reload failure

### ISSUE THREAD

**Issue by Tirit** [evennia/evennia#698]
So recently I've been having issues with the @reload command. The server will act as it is reloading, gives the message "Server restarting ..." and then will not finish. It makes no changes. server.log is showing;

```
2015-03-09 18:03:37-0700 [-] Unhandled Error
        Traceback (most recent call last):
          File "/home/evennia/vienv/local/lib/python2.7/site-packages/twisted/internet/base.py", line 846, in runUntilCurrent
            self.fireSystemEvent("shutdown")
          File "/home/evennia/vienv/local/lib/python2.7/site-packages/twisted/internet/base.py", line 639, in fireSystemEvent
            event.fireEvent()
          File "/home/evennia/vienv/local/lib/python2.7/site-packages/twisted/internet/base.py", line 410, in fireEvent
            result = callable(*args, **kwargs)
          File "/home/evennia/vienv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1253, in unwindGenerator
            return _inlineCallbacks(None, gen, Deferred())
        --- <exception caught here> ---
          File "/home/evennia/vienv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1107, in _inlineCallbacks
            result = g.send(result)
          File "/home/evennia/evennia/evennia/server/server.py", line 370, in shutdown
            yield [s.at_server_shutdown() for s in ScriptDB.get_all_cached_instances()]
        exceptions.AttributeError: 'ScriptDB' object has no attribute 'at_server_shutdown'
```

When I try to do an "evennia reload" from command, anyone in-game and connected receives a "
" ... Portal lost connection to Server.
No command sets found! This is a sign of a critical bug.
The error was logged. If disconnecting/reconnecting doesn't
solve the problem, try to contact the server admin through
some other means for assistance."

the server.log shows;

```
2015-03-09 18:09:57-0700 [evennia.server.amp.AmpServerFactory] AMPProtocol connection established (HOST:IPv4Address(TCP, '127.0.0.1', 5000) PEER:IPv4Address(TCP, '127.0.0.1', 41304))
2015-03-09 18:09:57-0700 [AMPProtocol,0,127.0.0.1] [::] Traceback (most recent call last):
2015-03-09 18:09:57-0700 [AMPProtocol,0,127.0.0.1] [::]   File "/home/evennia/evennia/evennia/typeclasses/models.py", line 191, in __init__
2015-03-09 18:09:57-0700 [AMPProtocol,0,127.0.0.1] [::]     self.__class__ = class_from_module(self.db_typeclass_path)
2015-03-09 18:09:57-0700 [AMPProtocol,0,127.0.0.1] [::]   File "/home/evennia/evennia/evennia/utils/utils.py", line 971, in class_from_module
2015-03-09 18:09:57-0700 [AMPProtocol,0,127.0.0.1] [::]     raise ImportError(err)
2015-03-09 18:09:57-0700 [AMPProtocol,0,127.0.0.1] [::] ImportError: Could not load typeclass 'evennia.scripts.scripts.CheckSessions'.
2015-03-09 18:09:57-0700 [AMPProtocol,0,127.0.0.1] [::] Traceback (most recent call last):
2015-03-09 18:09:57-0700 [AMPProtocol,0,127.0.0.1] [::]   File "/home/evennia/evennia/evennia/typeclasses/models.py", line 191, in __init__
2015-03-09 18:09:57-0700 [AMPProtocol,0,127.0.0.1] [::]     self.__class__ = class_from_module(self.db_typeclass_path)
2015-03-09 18:09:57-0700 [AMPProtocol,0,127.0.0.1] [::]   File "/home/evennia/evennia/evennia/utils/utils.py", line 971, in class_from_module
2015-03-09 18:09:57-0700 [AMPProtocol,0,127.0.0.1] [::]     raise ImportError(err)
2015-03-09 18:09:57-0700 [AMPProtocol,0,127.0.0.1] [::] ImportError: Could not load typeclass 'evennia.scripts.scripts.ValidateScripts'.
2015-03-09 18:09:57-0700 [AMPProtocol,0,127.0.0.1] [::] Traceback (most recent call last):
2015-03-09 18:09:57-0700 [AMPProtocol,0,127.0.0.1] [::]   File "/home/evennia/evennia/evennia/typeclasses/models.py", line 191, in __init__
2015-03-09 18:09:57-0700 [AMPProtocol,0,127.0.0.1] [::]     self.__class__ = class_from_module(self.db_typeclass_path)
2015-03-09 18:09:57-0700 [AMPProtocol,0,127.0.0.1] [::]   File "/home/evennia/evennia/evennia/utils/utils.py", line 971, in class_from_module
2015-03-09 18:09:57-0700 [AMPProtocol,0,127.0.0.1] [::]     raise ImportError(err)
2015-03-09 18:09:57-0700 [AMPProtocol,0,127.0.0.1] [::] ImportError: Could not load typeclass 'evennia.scripts.scripts.ValidateChannelHandler'.
2015-03-09 18:09:57-0700 [AMPProtocol,0,127.0.0.1] [::] Traceback (most recent call last):
2015-03-09 18:09:57-0700 [AMPProtocol,0,127.0.0.1] [::]   File "/home/evennia/evennia/evennia/typeclasses/models.py", line 191, in __init__
2015-03-09 18:09:57-0700 [AMPProtocol,0,127.0.0.1] [::]     self.__class__ = class_from_module(self.db_typeclass_path)
2015-03-09 18:09:57-0700 [AMPProtocol,0,127.0.0.1] [::]   File "/home/evennia/evennia/evennia/utils/utils.py", line 971, in class_from_module
2015-03-09 18:09:57-0700 [AMPProtocol,0,127.0.0.1] [::]     raise ImportError(err)
2015-03-09 18:09:57-0700 [AMPProtocol,0,127.0.0.1] [::] ImportError: Could not load typeclass 'evennia.scripts.scripts.ValidateIdmapperCache'.
2015-03-09 18:09:57-0700 [AMPProtocol,0,127.0.0.1] [::] Traceback (most recent call last):
2015-03-09 18:09:57-0700 [AMPProtocol,0,127.0.0.1] [::]   File "/home/evennia/evennia/evennia/typeclasses/models.py", line 191, in __init__
2015-03-09 18:09:57-0700 [AMPProtocol,0,127.0.0.1] [::]     self.__class__ = class_from_module(self.db_typeclass_path)
2015-03-09 18:09:57-0700 [AMPProtocol,0,127.0.0.1] [::]   File "/home/evennia/evennia/evennia/utils/utils.py", line 971, in class_from_module
2015-03-09 18:09:57-0700 [AMPProtocol,0,127.0.0.1] [::]     raise ImportError(err)
2015-03-09 18:09:57-0700 [AMPProtocol,0,127.0.0.1] [::] ImportError: Could not load typeclass 'evennia.utils.gametime.GameTime'.
```

After I do an 'evennia reload' from the command prompt in my game directory, and disconnect and reconnect from the game I get a traceback from the game on reconnecting as well.

```
Traceback (most recent call last):
  File "/home/evennia/evennia/evennia/commands/cmdhandler.py", line 384, in _run_command
    ret = yield cmd.func()
  File "/home/evennia/evennia/evennia/commands/default/unloggedin.py", line 189, in func
    session.sessionhandler.login(session, player)
  File "/home/evennia/evennia/evennia/server/sessionhandler.py", line 295, in login
    player.at_post_login(sessid=session.sessid)
  File "/home/evennia/evennia/evennia/players/players.py", line 641, in at_post_login
    self.puppet_object(sessid, self.db._last_puppet)
  File "/home/evennia/evennia/evennia/players/players.py", line 201, in puppet_object
    self.unpuppet_object(obj.sessid.get())
  File "/home/evennia/evennia/evennia/players/players.py", line 246, in unpuppet_object
    raise RuntimeError("No session was found.")
RuntimeError: No session was found.

Above traceback is from an untrapped error. Please file a bug report.
```

**Comment by Kelketek** [comment]
@Griatch ScriptDB doesn't have this hook but DefaultScript does. The other types, like Object and whatnot, do just fine, but the recent changes removed GameTime and what have you. This should force those objects to their default typeclasses. But I'm not sure the default typeclasses in settings_default are correct anymore.

**Comment by Griatch** [comment]
@Tirit 

Did you run migrations? The migration should have removed all remains of the default system scripts for you (see announcement on the mailing list). 

@Kelketek 

idmapper cache sits only on the database model (`ScriptDB`) so `ScriptDB.get_all_cached_instances()` returns all children of `ScriptDB` as well. What the error comes from is that the `Gametime` script typeclass cannot be found (since it doesn't exist), which means that Evennia in desperation falls back to using the base model instead (`ScriptDB`). I guess it would make more sense to have it fall back to `DefaultScript` (or whatever `settings.SCRIPT_TYPECLASS_DEFAULT` says) to avoid missing hook-errors like this.  Keeping this open as a remainer to add that.

**Comment by Tirit** [comment]
@griatch I did the migrate command.

Not sure how much this matters but after the last mege from devel branch I cleaned off the old files and started with a new clone and did a fresh rebuild.

**Comment by Griatch** [comment]
@Tirit 

I have made one more migration to remove scripts still from the old paths of Evennia. Also made the typeclass loading fallback in a series of steps, logging the failures as they go. This should avoid things like the confusing ScriptDB AttributeError, which comes from falling back to the model too fast when failing to load (or find) the specified typeclass. 

You still need to convert the typeclasses to the new locations and paths, there is no way around that. Evennia will convert any typeclasses stored to be in the old default location (src.objects.objects.Object for example) and convert them automatically to the new default. It will however not find your own custom typeclasses and you should convert those.

If you have, say, a Character in the old system with a typeclass of `game.gamesrc.objects.MyObject` and you since moved the `MyObject` class to the new game folder/typeclasses/, you can do this:

```bash
$ evennia shell
# (in python interpreter):
from evennia import ObjectDB
# as suggested by Kelketek :) 
ObjectDB.objects.filter(db_typeclass_path="game.gamesrc.objects.MyObject").update(db_typeclass_path = "typeclasses.MyObject") 
```

Closing this now, the issue has been addressed, converting objects needs to be done on a game-by-game basis.
```
