### ISSUE TITLE
Bug: MSDP OOB errors

### ISSUE THREAD

**Issue by Griatch** [evennia/evennia#707]
*Copied from the [mailing list posting](https://groups.google.com/forum/#!msg/evennia/8bXr1mU9PLc/xsgIPBAL5IAJ).*

Hello,

I've been working extensively using Evennia in attempt to help a friend build a project.

I'm really enjoying working with Evennia.Currently, I'm investing using a lua-based plugin in MushClient to utilize MSDP to orchestrate a gui.

Mind you, I have not overloaded `oob_cmds` or `oobhandler`.

I have my MushClient lua based plugin send the string: `SendPkt ("\255\250\69\1REPORT\2CHARACTER_NAME\255\240")`

The server errors with:
```
2015-03-13 01:01:49+0000 [AMPProtocol,0,127.0.0.1] [::] Traceback (most recent call last):
2015-03-13 01:01:49+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/opt/evennia/evennia/server/oobhandler.py", line 427, in execute_cmd
2015-03-13 01:01:49+0000 [AMPProtocol,0,127.0.0.1] [::]     oobfunc(session, *args, **kwargs)
2015-03-13 01:01:49+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/opt/evennia/evennia/server/oob_cmds.py", line 254, in oob_report
2015-03-13 01:01:49+0000 [AMPProtocol,0,127.0.0.1] [::]     OOB_HANDLER.add_field_monitor(obj, session.sessid, propname, "return_field_report")
2015-03-13 01:01:49+0000 [AMPProtocol,0,127.0.0.1] [::] AttributeError: 'NoneType' object has no attribute 'add_field_monitor'
2015-03-13 01:01:49+0000 [AMPProtocol,0,127.0.0.1] [EE] OOB ERROR: Exception in REPORT(*('CHARACTER_NAME',), **{}):
2015-03-13 01:01:49+0000 [AMPProtocol,0,127.0.0.1] [EE] 'NoneType' object has no attribute 'add_field_monitor'
```

I work around this by manually applying the monitors via `@py` (to test it prior to doing it post_puppet)

```
@py from evennia import OOB_HANDLER;sessions = [self.player.get_session(sessid) for sessid in self.sessid.get()]; OOB_HANDLER.add_field_monitor(self, sessions[0].sessid, "db_location", "return_field_report")

@py from evennia import OOB_HANDLER;sessions = [self.player.get_session(sessid) for sessid in self.sessid.get()]; OOB_HANDLER.add_attribute_monitor(self, sessions[0].sessid, "health", "return_attribute_report")
```

This works. The lua client plugin sees and receives the updates.

However, when I try to remove them with (pulled from the example in `oob_cmd.py`:

```
@py from evennia import OOB_HANDLER;sessions = [self.player.get_session(sessid) for sessid in self.sessid.get()]; OOB_HANDLER.remove_attribute_monitor(self, sessions[0].sessid, "health", "oob_return_attribute_report")
```

```
I get:
<<<   File "/opt/evennia/evennia/server/oobhandler.py", line 369, in remove_attribute_monitor
<<<     self._remove_monitor(attrobj, sessid, "db_value", attr_name, oobfuncname)
<<< TypeError: _remove_monitor() takes at most 5 arguments (6 given)
```

I decided to investigate the source code a bit and found in: [oobhandler.py](https://github.com/evennia/evennia/blob/96ac3f967b123564ff880209643761ec455a2982/evennia/server/oobhandler.py):

```python
172. def _remove_monitor(self, obj, sessid, fieldname, oobfuncname=None)
....
369. self._remove_monitor(attrobj, sessid, "db_value", attr_name, oobfuncname)
```

It appears what `_remove_monitor` is expecting and what 'remove_attribute_monitor' is giving are polar opposites. I'm newish to PY, but most languages expect an order into functions and I have no evidence to suggest py is any different.

The reason I ask, is because if I have to write a cleanup to remove the monitors on character unpuppet, it needs to work. If I don't remove the monitors, and I disconnect/reconnect, then I have a whole 'nother mess of it not finding the sessions.

Please let me know if I'm way off base on this one.

**Comment by Griatch** [comment]
Thanks for the report! This does look like a regression in the oob mechanism. I'll take a look at it and see what is going on.

**Comment by Griatch** [comment]
You were right, the `_remove_monitor` call had one argument too many in one place. The first issue was a cyclic import issue which has now been resolved. You should now get your oob data back correctly again.
