### ISSUE TITLE
Compile/Run Error on Start

### ISSUE THREAD

**Issue by Tirit** [evennia/evennia#740]
So I just did the latest pull, and upgrade to Django 1.8. 
I did a full stop, installed the new Django, did a migrate, and started evennia. 
On login I get 

>Compile/Run error when loading cmdset 'commands.default_cmdsets.UnloggedinCmdSet': Conflicting 'extendedroom' models in application 'typeclasses': <class 'evennia.contrib.extended_room.ExtendedRoom'> and <class 'typeclasses.extended_room.ExtendedRoom'>..
Compile/Run error when loading cmdset 'commands.default_cmdsets.UnloggedinCmdSet': Conflicting 'extendedroom' models in application 'typeclasses': <class 'evennia.contrib.extended_room.ExtendedRoom'> and <class 'typeclasses.extended_room.ExtendedRoom'>..
 (See log for details.)
Command '__unloggedin_look_command' is not available. Type "help" for help.
Compile/Run error when loading cmdset 'commands.default_cmdsets.UnloggedinCmdSet': Conflicting 'extendedroom' models in application 'typeclasses': <class 'evennia.contrib.extended_room.ExtendedRoom'> and <class 'typeclasses.extended_room.ExtendedRoom'>..
 (See log for details.)

I do have two extended_room.py files, and thus two ExtendedRoom classes. One from the contrib file, and one in my own typeclasses file (So I can properly edit it). 

My game "'commands.default_cmdsets.UnloggedinCmdSet':" shows nothing but the default for a fresh game.

**Comment by Tirit** [comment]
Sorry realized I should have posed the full traceback from the log
> 2015-04-08 15:22:10-0700 [AMPProtocol,0,127.0.0.1] [::] Traceback (most recent call last):
2015-04-08 15:22:10-0700 [AMPProtocol,0,127.0.0.1] [::]   File "/home/evennia/evennia/evennia/commands/cmdsethandler.py", line 123, in import_cmdset
2015-04-08 15:22:10-0700 [AMPProtocol,0,127.0.0.1] [::]     module = __import__(modulepath, fromlist=[True])
2015-04-08 15:22:10-0700 [AMPProtocol,0,127.0.0.1] [::]   File "/home/evennia/deepshadows/commands/default_cmdsets.py", line 19, in <module>
2015-04-08 15:22:10-0700 [AMPProtocol,0,127.0.0.1] [::]     from typeclasses import extended_room
2015-04-08 15:22:10-0700 [AMPProtocol,0,127.0.0.1] [::]   File "/home/evennia/deepshadows/typeclasses/extended_room.py", line 81, in <module>
2015-04-08 15:22:10-0700 [AMPProtocol,0,127.0.0.1] [::]     class ExtendedRoom(Room):
2015-04-08 15:22:10-0700 [AMPProtocol,0,127.0.0.1] [::]   File "/home/evennia/evennia/evennia/typeclasses/models.py", line 107, in __new__
2015-04-08 15:22:10-0700 [AMPProtocol,0,127.0.0.1] [::]     new_class = patched_new(cls, name, bases, attrs)
2015-04-08 15:22:10-0700 [AMPProtocol,0,127.0.0.1] [::]   File "/home/evennia/evennia/evennia/typeclasses/django_new_patch.py", line 254, in patched_new
2015-04-08 15:22:10-0700 [AMPProtocol,0,127.0.0.1] [::]     new_class._meta.apps.register_model(new_class._meta.app_label, new_class)
2015-04-08 15:22:10-0700 [AMPProtocol,0,127.0.0.1] [::]   File "/home/evennia/vienv/local/lib/python2.7/site-packages/django/apps/registry.py", line 221, in register_model
2015-04-08 15:22:10-0700 [AMPProtocol,0,127.0.0.1] [::]     (model_name, app_label, app_models[model_name], model))
2015-04-08 15:22:10-0700 [AMPProtocol,0,127.0.0.1] [::] RuntimeError: Conflicting 'extendedroom' models in application 'typeclasses': <class 'evennia.contrib.extended_room.ExtendedRoom'> and <class 'typeclasses.extended_room.ExtendedRoom'>.
2015-04-08 15:22:10-0700 [AMPProtocol,0,127.0.0.1] [EE] Compile/Run error when loading cmdset 'commands.default_cmdsets.UnloggedinCmdSet': Conflicting 'extendedroom' models in application 'typeclasses': <class 'evennia.contrib.extended_room.ExtendedRoom'> and <class 'typeclasses.extended_room.ExtendedRoom'>..

**Comment by Griatch** [comment]
Not sure why you didn't see this error until after the update because this was always an error. 
This is basically the only way a typeclass behaves differently from a normal Python class: all typeclasses must be uniquely named globally throughout the entirety of Evennia. 
Rename your copy of ExtendedRoom to MyExtendedRoom or something and it will work. 

It's highly recommended that you read the wiki page on Typeclasses to familiarize yourself.

Closing.
