### ISSUE TITLE
Bug: Custom command's caller.msg(value) with large text buffer results in TypeError

### ISSUE THREAD

**Issue by darkmusic** [evennia/evennia#750]
#### Steps to reproduce the issue:

1. Define a custom command for an object like the following:
```python
class CmdTypeError(default_cmds.MuxCommand):
        key = "typeerror"
        aliases = ["te"]
        locks = "cmd:all()"
 
        def func(self):
                caller = self.caller
                message = ""
                return_msg = ""
                for i in range(0, 150):
                        message += "#"
                for i in range(0, 1000):
                        return_msg += message + '\n'
                caller.msg(return_msg)
```
2. Add the new command to the object's command set.
3. In game, create the object and call the new command:

**te**

#### What I expect to see and what I actually see (tracebacks, error messages etc):
Expected: 1000 lines should be displayed, each with 150 '#' characters.
Actual: The following error message is displayed:

2015-05-24 03:37:51+0000 [AMPProtocol,0,127.0.0.1] [::] Traceback (most recent call last):
2015-05-24 03:37:51+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/home/dmu/evennia/evennia/commands/cmdhandler.py", line 415, in _run_command
2015-05-24 03:37:51+0000 [AMPProtocol,0,127.0.0.1] [::]     ret = yield cmd.func()
2015-05-24 03:37:51+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/home/dmu/evennia/ganymede/commands/datapad_command.py", line 100, in func
2015-05-24 03:37:51+0000 [AMPProtocol,0,127.0.0.1] [::]     caller.msg(return_msg)
2015-05-24 03:37:51+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/home/dmu/evennia/evennia/objects/objects.py", line 454, in msg
2015-05-24 03:37:51+0000 [AMPProtocol,0,127.0.0.1] [::]     sessions[0].msg(text=text, session=sessions, **kwargs)
2015-05-24 03:37:51+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/home/dmu/evennia/evennia/server/serversession.py", line 242, in data_out
2015-05-24 03:37:51+0000 [AMPProtocol,0,127.0.0.1] [::]     self.sessionhandler.data_out(session, text=text, **kwargs)
2015-05-24 03:37:51+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/home/dmu/evennia/evennia/server/sessionhandler.py", line 482, in data_out
2015-05-24 03:37:51+0000 [AMPProtocol,0,127.0.0.1] [::]     data=kwargs)
2015-05-24 03:37:51+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/home/dmu/evennia/evennia/server/amp.py", line 414, in call_remote_MsgServer2Portal
2015-05-24 03:37:51+0000 [AMPProtocol,0,127.0.0.1] [::]     return self.batch_send(MsgServer2Portal, sessid, msg=msg, data=data)
2015-05-24 03:37:51+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/home/dmu/evennia/evennia/server/amp.py", line 325, in batch_send
2015-05-24 03:37:51+0000 [AMPProtocol,0,127.0.0.1] [::]     deferred.addErrback(self.errback, "%s part %i/%i" % (command.key, ipart, part))
2015-05-24 03:37:51+0000 [AMPProtocol,0,127.0.0.1] [::] TypeError: %d format: a number is required, not str
Traceback (most recent call last):
  File "/home/dmu/evennia/evennia/commands/cmdhandler.py", line 415, in _run_command
    ret = yield cmd.func()
  File "/home/dmu/evennia/ganymede/commands/datapad_command.py", line 100, in func
    caller.msg(return_msg)
  File "/home/dmu/evennia/evennia/objects/objects.py", line 454, in msg
    sessions[0].msg(text=text, session=sessions, **kwargs)
  File "/home/dmu/evennia/evennia/server/serversession.py", line 242, in data_out
    self.sessionhandler.data_out(session, text=text, **kwargs)
  File "/home/dmu/evennia/evennia/server/sessionhandler.py", line 482, in data_out
    data=kwargs)
  File "/home/dmu/evennia/evennia/server/amp.py", line 414, in call_remote_MsgServer2Portal
    return self.batch_send(MsgServer2Portal, sessid, msg=msg, data=data)
  File "/home/dmu/evennia/evennia/server/amp.py", line 325, in batch_send
    deferred.addErrback(self.errback, "%s part %i/%i" % (command.key, ipart, part))
TypeError: %d format: a number is required, not str
 
Above traceback is from an untrapped error. Please file a bug report.
#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve:
Branch: master (commit: 16de3b0c1e0d4b237e47ca86af3fb5b804a6de3c)
OS: Ubuntu 11.10
DB:  Postgresql 9.1.9

**Comment by Griatch** [comment]
This was resolved in  c67aa4e.

*Note: This was possible to reproduce without making a custom command, using the `@py` command:* 

```python
@py self.msg("\n".join(["#".join(["" for i in range(150)]) for k in range(1000)]))
```
