### ISSUE TITLE
Menu system error.

### ISSUE THREAD

**Issue by Fayos** [evennia/evennia#754]
instructions in menusystem.py is to add file to default cmdset. I do this via `mygame/commands/defaultcmdset.py` simple copy/paste all 600 odd lines.
reload, reconnect:

```
1 - Log in with an existing account 
2 - Create a new account            
3 - Help                            
4 - Quit
2

Please enter your desired account name (empty to abort).
test

Please enter your password (empty to go back).
jacking
Traceback (most recent call last):
  File "/Users/keda/Desktop/undaunted/evennia/evennia/contrib/menu_login.py", line 226, in func
    pchanneldef = settings.CHANNEL_PUBLIC
  File "/Users/keda/Desktop/undaunted/pyenv/lib/python2.7/site-packages/django/conf/__init__.py", 
line 49, in __getattr__
    return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'CHANNEL_PUBLIC'

This is a bug. Please e-mail an admin if the problem persists.

```
I push `enter`:

```
Please enter your desired account name (empty to abort).
```

I close my client, restart it:

```python
1

Please enter your account name (empty to abort).
test

Please enter your password (empty to go back).
jacking
Welcome test! Logging in ...
Traceback (most recent call last):
  File "/Users/keda/Desktop/undaunted/evennia/evennia/commands/cmdhandler.py", line 415, in 
_run_command
    ret = yield cmd.func()
  File "/Users/keda/Desktop/undaunted/evennia/evennia/contrib/menu_login.py", line 140, in func
    self.caller.sessionhandler.login(self.caller, player)
  File "/Users/keda/Desktop/undaunted/evennia/evennia/server/sessionhandler.py", line 295, in login
    player.at_post_login(sessid=session.sessid)
  File "/Users/keda/Desktop/undaunted/evennia/evennia/players/players.py", line 579, in 
at_post_login
    self.puppet_object(sessid, self.db._last_puppet)
  File "/Users/keda/Desktop/undaunted/evennia/evennia/players/players.py", line 180, in 
puppet_object
    raise RuntimeError("Object not found")
RuntimeError: Object not found

Above traceback is from an untrapped error. Please file a bug report.
Traceback (most recent call last):
  File "/Users/keda/Desktop/undaunted/evennia/evennia/commands/cmdhandler.py", line 549, in 
cmdhandler
    ret = yield _run_command(syscmd, syscmd.key, sysarg)
ErrorReported

Above traceback is from a Command handler bug.Please file a bug report with the Evennia project.
l
You are out-of-character (OOC).
Use @ic to get back into the game.
@ic
Usage: @ic &lt;character&gt;
@ic character
That is not a valid character choice.

```

At this point i gave up, and removed the code.

**Comment by Fayos** [comment]
Also will note i have the menu login working, obviously.

**Comment by Griatch** [comment]
Wait, you are talking about importing the `menusystem` contrib but your error seems related to the `menu_login` (which you show gives an error when you try to give a password). Yet you say that your menu login works "obviously". Color me confused. 

Anyway, the `CHANNEL_PUBLIC` (the first error you get) looks like a real bug, it will be fixed.  The later errors seem to be after-effects of that first error.  Thanks for reporting. 

#### Note:  

The instruction in `menusystem.py` (which is, as said, completely unrelated to this error) reads as follows: 

```
For a simple demonstration, add `CmdMenuTest` from this module to the default cmdset.
```
What this means is not to copy&paste the entire code into your default cmdset module. I mean - you *could* do this if you planned to make extensive modifications, but it's not necessary. You just import what you need (in this case an example command) and add it to the character cmdset: 

```python
# in mygame/commands/default_cmdsets.py

from contrib.menusystem import CmdMenuTest # <-added 

class CharacterCmdSet(default_cmds.CharacterCmdSet):
    #...
    def at_cmdset_creation(self):
        # ...
        self.add(CmdMenuTest) # <-added
```

Please see the [Tutorial: Adding new Commands](https://github.com/evennia/evennia/wiki/Adding%20Command%20Tutorial) for more details on this.

**Comment by Fayos** [comment]
Correct, menu login works fine by itself, once i try to activate menu system with menu login, the errors happen.
