### ISSUE TITLE
Failure installing on Windows 7 (64 bit) following Getting Started instructions

### ISSUE THREAD

**Issue by ergodicbreak** [evennia/evennia#764]
hi, it seems Windows installs are working for others (see https://groups.google.com/forum/?fromgroups=#!searchin/evennia/evennia$20windows/evennia/kaka6-e1gOc/YPtQOxVrEpAJ ) so perhaps it's something with my environment; I don't have anything too outlandish though so perhaps it's a bug. 

Here's what I did:
```
PS C:\Users\george> cd work
PS C:\Users\george\work> virtualenv --python="c:\python27\python.exe" evennia-venv
Running virtualenv with interpreter c:\python27\python.exe
New python executable in evennia-venv\Scripts\python.exe
Installing setuptools, pip...done.
PS C:\Users\george\work> .\evennia-venv\Scripts\activate
(evennia-venv) PS C:\Users\george\work> cd .\evennia-venv
(evennia-venv) PS C:\Users\george\work\evennia-venv> git clone git@github.com:evennia/evennia.git
Cloning into 'evennia'...
remote: Counting objects: 22292, done.
remote: Compressing objects: 100% (120/120), done.
rRemote: Total 22292 (delta 64), reused 0 (delta 0), pack-reused 22172eceiving objects:  99% (22263/22292), 29.49 MiB |

% (22292/22292), 29.49 MiB | 187.00 KiB/s, done.
Resolving deltas: 100% (15934/15934), done.
Checking connectivity... done.
(evennia-venv) PS C:\Users\george\work\evennia-venv> cd evennia
(evennia-venv) PS C:\Users\george\work\evennia-venv\evennia> pip install -e .
Obtaining file:///C:/Users/george/work/evennia-venv/evennia
  Running setup.py (path:C:/Users/george/work/evennia-venv/evennia\setup.py) egg_info for package from file:///C:/Users
george/work/evennia-venv/evennia

Downloading/unpacking pypiwin32 (from evennia==0.5.0)
Downloading/unpacking django>=1.8,<1.9 (from evennia==0.5.0)
Downloading/unpacking twisted>=15.2.1 (from evennia==0.5.0)
  Running setup.py (path:C:\Users\george\AppData\Local\Temp\pip_build_george\twisted\setup.py) egg_info for package twi
ted

    file twisted.py (for module twisted) not found
    file twisted\cred.py (for module twisted.cred) not found
    file twisted\internet.py (for module twisted.internet) not found
    file twisted\internet\test.py (for module twisted.internet.test) not found
    file twisted\logger.py (for module twisted.logger) not found
    file twisted\names.py (for module twisted.names) not found
    file twisted\names\test.py (for module twisted.names.test) not found
    file twisted\protocols.py (for module twisted.protocols) not found
    file twisted\protocols\test.py (for module twisted.protocols.test) not found
    file twisted\python.py (for module twisted.python) not found
    file twisted\python\test.py (for module twisted.python.test) not found
    file twisted\test.py (for module twisted.test) not found
    file twisted\trial.py (for module twisted.trial) not found
    file twisted\trial\test.py (for module twisted.trial.test) not found
    file twisted\web.py (for module twisted.web) not found
    file twisted\web\test.py (for module twisted.web.test) not found
    file twisted\cred\test.py (for module twisted.cred.test) not found
    file twisted\logger\test.py (for module twisted.logger.test) not found
Downloading/unpacking mock>=1.0.1 (from evennia==0.5.0)
  Running setup.py (path:C:\Users\george\AppData\Local\Temp\pip_build_george\mock\setup.py) egg_info for package mock

    warning: no files found matching '*.png' under directory 'docs'
    warning: no files found matching '*.css' under directory 'docs'
    warning: no files found matching '*.html' under directory 'docs'
    warning: no files found matching '*.js' under directory 'docs'
Downloading/unpacking pillow (from evennia==0.5.0)
Downloading/unpacking pytz (from evennia==0.5.0)
Downloading/unpacking zope.interface>=4.0.2 (from twisted>=15.2.1->evennia==0.5.0)
  Running setup.py (path:C:\Users\george\AppData\Local\Temp\pip_build_george\zope.interface\setup.py) egg_info for pack
ge zope.interface

    warning: no previously-included files matching '*.dll' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
Downloading/unpacking setuptools (from zope.interface>=4.0.2->twisted>=15.2.1->evennia==0.5.0)
Installing collected packages: pypiwin32, django, twisted, mock, pillow, pytz, evennia, zope.interface, setuptools
*** Error compiling 'C:\\Users\\george\\AppData\\Local\\Temp\\pip_build_george\\pypiwin32\\win32comext\\mapi\\demos\\ma
isend.py'...
  File "C:\Users\george\AppData\Local\Temp\pip_build_george\pypiwin32\win32comext\mapi\demos\mapisend.py", line 14
    except NameError: True = 1==1; False = 1==0
                     ^
SyntaxError: can't assign to keyword

  Running setup.py install for twisted
    file twisted.py (for module twisted) not found
    file twisted\cred.py (for module twisted.cred) not found
    file twisted\internet.py (for module twisted.internet) not found
    file twisted\internet\test.py (for module twisted.internet.test) not found
    file twisted\logger.py (for module twisted.logger) not found
    file twisted\names.py (for module twisted.names) not found
    file twisted\names\test.py (for module twisted.names.test) not found
    file twisted\protocols.py (for module twisted.protocols) not found
    file twisted\protocols\test.py (for module twisted.protocols.test) not found
    file twisted\python.py (for module twisted.python) not found
    file twisted\python\test.py (for module twisted.python.test) not found
    file twisted\test.py (for module twisted.test) not found
    file twisted\trial.py (for module twisted.trial) not found
    file twisted\trial\test.py (for module twisted.trial.test) not found
    file twisted\web.py (for module twisted.web) not found
    file twisted\web\test.py (for module twisted.web.test) not found
    file twisted\cred\test.py (for module twisted.cred.test) not found
    file twisted\logger\test.py (for module twisted.logger.test) not found
    file twisted.py (for module twisted) not found
    file twisted\cred.py (for module twisted.cred) not found
    file twisted\internet.py (for module twisted.internet) not found
    file twisted\internet\test.py (for module twisted.internet.test) not found
    file twisted\logger.py (for module twisted.logger) not found
    file twisted\names.py (for module twisted.names) not found
    file twisted\names\test.py (for module twisted.names.test) not found
    file twisted\protocols.py (for module twisted.protocols) not found
    file twisted\protocols\test.py (for module twisted.protocols.test) not found
    file twisted\python.py (for module twisted.python) not found
    file twisted\python\test.py (for module twisted.python.test) not found
    file twisted\test.py (for module twisted.test) not found
    file twisted\trial.py (for module twisted.trial) not found
    file twisted\trial\test.py (for module twisted.trial.test) not found
    file twisted\web.py (for module twisted.web) not found
    file twisted\web\test.py (for module twisted.web.test) not found
    file twisted\cred\test.py (for module twisted.cred.test) not found
    file twisted\logger\test.py (for module twisted.logger.test) not found

    file twisted.py (for module twisted) not found
    file twisted\cred.py (for module twisted.cred) not found
    file twisted\internet.py (for module twisted.internet) not found
    file twisted\internet\test.py (for module twisted.internet.test) not found
    file twisted\logger.py (for module twisted.logger) not found
    file twisted\names.py (for module twisted.names) not found
    file twisted\names\test.py (for module twisted.names.test) not found
    file twisted\protocols.py (for module twisted.protocols) not found
    file twisted\protocols\test.py (for module twisted.protocols.test) not found
    file twisted\python.py (for module twisted.python) not found
    file twisted\python\test.py (for module twisted.python.test) not found
    file twisted\test.py (for module twisted.test) not found
    file twisted\trial.py (for module twisted.trial) not found
    file twisted\trial\test.py (for module twisted.trial.test) not found
    file twisted\web.py (for module twisted.web) not found
    file twisted\web\test.py (for module twisted.web.test) not found
    file twisted\cred\test.py (for module twisted.cred.test) not found
    file twisted\logger\test.py (for module twisted.logger.test) not found
    file twisted.py (for module twisted) not found
    file twisted\cred.py (for module twisted.cred) not found
    file twisted\internet.py (for module twisted.internet) not found
    file twisted\internet\test.py (for module twisted.internet.test) not found
    file twisted\logger.py (for module twisted.logger) not found
    file twisted\names.py (for module twisted.names) not found
    file twisted\names\test.py (for module twisted.names.test) not found
    file twisted\protocols.py (for module twisted.protocols) not found
    file twisted\protocols\test.py (for module twisted.protocols.test) not found
    file twisted\python.py (for module twisted.python) not found
    file twisted\python\test.py (for module twisted.python.test) not found
    file twisted\test.py (for module twisted.test) not found
    file twisted\trial.py (for module twisted.trial) not found
    file twisted\trial\test.py (for module twisted.trial.test) not found
    file twisted\web.py (for module twisted.web) not found
    file twisted\web\test.py (for module twisted.web.test) not found
    file twisted\cred\test.py (for module twisted.cred.test) not found
    file twisted\logger\test.py (for module twisted.logger.test) not found
  Running setup.py install for mock

    warning: no files found matching '*.png' under directory 'docs'
    warning: no files found matching '*.css' under directory 'docs'
    warning: no files found matching '*.html' under directory 'docs'
    warning: no files found matching '*.js' under directory 'docs'
  Running setup.py develop for evennia
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help

    error: option --home not recognized
    Complete output from command C:\Python34_64\python.exe -c "import setuptools, tokenize; __file__='C:/Users/george/w
rk/evennia-venv/evennia\\setup.py'; exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n')
 __file__, 'exec'))" develop --no-deps --home=C:\Users\george\AppData\Local\Temp\tmp3w01ihje:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]

   or: -c --help [cmd1 cmd2 ...]

   or: -c --help-commands

   or: -c cmd --help



error: option --home not recognized

----------------------------------------
Cleaning up...
Command C:\Python34_64\python.exe -c "import setuptools, tokenize; __file__='C:/Users/george/work/evennia-venv/evennia\
setup.py'; exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" dev
lop --no-deps --home=C:\Users\george\AppData\Local\Temp\tmp3w01ihje failed with error code 1 in C:/Users/george/work/ev
nnia-venv/evennia
Storing debug log for failure in C:\Users\george\pip\pip.log
```

And the tail of pip.log

```
Running setup.py develop for evennia
    Running command C:\Python34_64\python.exe -c "import setuptools, tokenize; __file__='C:/Users/george/work/evennia-venv/evennia\\setup.py'; exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps --home=C:\Users\george\AppData\Local\Temp\tmp3w01ihje
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help
    
    error: option --home not recognized
    Complete output from command C:\Python34_64\python.exe -c "import setuptools, tokenize; __file__='C:/Users/george/work/evennia-venv/evennia\\setup.py'; exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps --home=C:\Users\george\AppData\Local\Temp\tmp3w01ihje:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]

   or: -c --help [cmd1 cmd2 ...]

   or: -c --help-commands

   or: -c cmd --help



error: option --home not recognized

----------------------------------------
Cleaning up...
  Removing temporary dir C:\Users\george\AppData\Local\Temp\pip_build_george...
Command C:\Python34_64\python.exe -c "import setuptools, tokenize; __file__='C:/Users/george/work/evennia-venv/evennia\\setup.py'; exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps --home=C:\Users\george\AppData\Local\Temp\tmp3w01ihje failed with error code 1 in C:/Users/george/work/evennia-venv/evennia
Exception information:
Traceback (most recent call last):
  File "c:\users\george\appdata\roaming\python\python34_64\site-packages\pip\basecommand.py", line 122, in main
    status = self.run(options, args)
  File "c:\users\george\appdata\roaming\python\python34_64\site-packages\pip\commands\install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "c:\users\george\appdata\roaming\python\python34_64\site-packages\pip\req.py", line 1435, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "c:\users\george\appdata\roaming\python\python34_64\site-packages\pip\req.py", line 665, in install
    self.install_editable(install_options, global_options)
  File "c:\users\george\appdata\roaming\python\python34_64\site-packages\pip\req.py", line 775, in install_editable
    show_stdout=False)
  File "c:\users\george\appdata\roaming\python\python34_64\site-packages\pip\util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command C:\Python34_64\python.exe -c "import setuptools, tokenize; __file__='C:/Users/george/work/evennia-venv/evennia\\setup.py'; exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps --home=C:\Users\george\AppData\Local\Temp\tmp3w01ihje failed with error code 1 in C:/Users/george/work/evennia-venv/evennia
```

Note my Python version, 

```
(evennia-venv) PS C:\Users\george\work\evennia-venv\evennia> python --version
Python 2.7.9
```

And of course, 

```
(evennia-venv) PS C:\Users\george\work\evennia-venv> evennia
The term 'evennia' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spe
lling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:8
+ evennia <<<<
    + CategoryInfo          : ObjectNotFound: (evennia:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

One strange thing I noticed was the contents of \evennia\bin\windows\evennia.bat:

```
@"C:\Python34_64\python.exe" "C:\Python34_64\Scripts\evennia_launcher.py" %*
```

Why is it pointing to my Python 3 install?

Thanks for any help, George

**Comment by ergodicbreak** [comment]
Well I think I figured this out. The problem was that I have a custom pip install target for non-virtualenv work. For some reason the target option is incompatible with the --home option used above -- see https://github.com/pypa/pip/issues/1833 .

I do have an older pip (6.08), I haven't checked if upgrading to 7 fixes the issue. But I was able to reconfigure my environment for the present as a workaround.
