### ISSUE TITLE
Evennia start error

### ISSUE THREAD

**Issue by Tirit** [evennia/evennia#856]
Today I had to do a 'evennia start' and it gave me this traceback
>(vienv)evennia@shadow:~/deepshadows/server/logs$ evennia start
>
>0 static files copied to '/home/evennia/deepshadows/web/static', 74 unmodified.
>
>Starting Evennia Server (output to stdout).
>
> Evennia Portal is already running as process 31028. Not restarted.
> (vienv)evennia@shadow:~/deepshadows/server/logs$ Unhandled Error
>Traceback (most recent call last):
 > File "/home/evennia/vienv/local/lib/python2.7/site-packages/twisted/application/app.py", line 657, >in run
>    runApp(config)
> File "/home/evennia/vienv/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 23, in >runApp
>   _SomeApplicationRunner(config).run()
>  File "/home/evennia/vienv/local/lib/python2.7/site-packages/twisted/application/app.py", line 389, 
> in run
>    self.application = self.createOrGetApplication()
>  File "/home/evennia/vienv/local/lib/python2.7/site-packages/twisted/application/app.py", line 454, >in createOrGetApplication
>    application = getApplication(self.config, passphrase)
>--- <exception caught here> ---
> File "/home/evennia/vienv/local/lib/python2.7/site-packages/twisted/application/app.py", line 465, ?> in getApplication
>    application = service.loadApplication(filename, style, passphrase)
>  File "/home/evennia/vienv/local/lib/python2.7/site-packages/twisted/application/service.py", line 
> 403, in loadApplication
>    application = sob.loadValueFromFile(filename, 'application', passphrase)
>  File "/home/evennia/vienv/local/lib/python2.7/site-packages/twisted/persisted/sob.py", line 210, in > loadValueFromFile
>    exec fileObj in d, d
>  File "/home/evennia/evennia/evennia/server/server.py", line 464, in <module>
>    EVENNIA = Evennia(application)
>  File "/home/evennia/evennia/evennia/server/server.py", line 170, in __init__
> self.run_init_hooks()
> File "/home/evennia/evennia/evennia/server/server.py", line 292, in run_init_hooks
> self.at_server_cold_start()
> File "/home/evennia/evennia/evennia/server/server.py", line 437, in at_server_cold_start
>    character.delete()
>  File "/home/evennia/evennia/evennia/objects/objects.py", line 745, in delete
>    self.player.unpuppet_object(sessid)
>  File "/home/evennia/evennia/evennia/players/players.py", line 268, in unpuppet_object
>    raise RuntimeError("No session was found.")
> exceptions.RuntimeError: No session was found.
> Failed to load application: No session was found.

**Comment by Griatch** [comment]
Hard to tell what could be wrong without further data. Could you try to recount any previous actions or changes done to your player/character before you did the (restart, I presume, since it says that the Portal is already running)?

**Comment by Tirit** [comment]
Yeah, the portal does run, and when people try to connect it gives a ... 
> Deep Shadows MUSH DoS protection is active. You are queued to connect in 1 seconds ...

I don't think I've done anything to the typeclasses/players.py and the character object hasn't changed as the last several weeks if not longer. 

Portal Log gives me this.

>2015-10-26 13:19:52-0700 [-] Received SIGINT, shutting down.
2015-10-26 13:19:52-0700 [-] (TCP Port 8000 Closed)
2015-10-26 13:19:52-0700 [-] Stopping factory <twisted.web.server.Site instance at 0x7fe45fa2da70>
2015-10-26 13:19:52-0700 [-] (TCP Port 8001 Closed)
2015-10-26 13:19:52-0700 [-] Stopping factory <twisted.internet.protocol.ServerFactory instance at 0x7fe45fa2d518>
2015-10-26 13:19:52-0700 [-] Stopping factory <evennia.utils.txws.WebSocketFactory instance at 0x7fe45fa2d9e0>
2015-10-26 13:19:52-0700 [-] (TCP Port 6250 Closed)
2015-10-26 13:19:52-0700 [-] Stopping factory <twisted.internet.protocol.ServerFactory instance at 0x7fe45fab1200>
2015-10-26 13:19:52-0700 [-] Main loop terminated.
2015-10-26 13:19:52-0700 [-] Server Shut Down.
2015-10-26 13:19:57-0700 [-] Log opened.
2015-10-26 13:19:57-0700 [-] twistd 15.2.1 (/home/evennia/vienv/bin/python 2.7.6) starting up.
2015-10-26 13:19:57-0700 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2015-10-26 13:19:57-0700 [-] ServerFactory starting on 6250
2015-10-26 13:19:57-0700 [-] Starting factory <twisted.internet.protocol.ServerFactory instance at 0x7ff5d9947200>
2015-10-26 13:19:57-0700 [-] ServerFactory (WebSocketFactory) starting on 8001
2015-10-26 13:19:57-0700 [-] Starting factory <twisted.internet.protocol.ServerFactory instance at 0x7ff5d98c3518>
2015-10-26 13:19:57-0700 [-] Starting factory <evennia.utils.txws.WebSocketFactory instance at 0x7ff5d98c39e0>
2015-10-26 13:19:57-0700 [-] Site starting on 8000
2015-10-26 13:19:57-0700 [-] Starting factory <twisted.web.server.Site instance at 0x7ff5d98c3a70>
2015-10-26 13:19:57-0700 [-] Starting factory <evennia.server.amp.AmpClientFactory instance at 0x7ff5d99ae680>
2015-10-26 13:19:57-0700 [Uninitialized] <twisted.internet.tcp.Connector instance at 0x7ff5d98da290> will retry in 1 seconds
2015-10-26 13:19:57-0700 [Uninitialized] Stopping factory <evennia.server.amp.AmpClientFactory instance at 0x7ff5d99ae680>
2015-10-26 13:19:58-0700 [-] Starting factory <evennia.server.amp.AmpClientFactory instance at 0x7ff5d99ae680>
2015-10-26 13:19:58-0700 [Uninitialized] <twisted.internet.tcp.Connector instance at 0x7ff5d98da290> will retry in 2 seconds
2015-10-26 13:19:58-0700 [Uninitialized] Stopping factory <evennia.server.amp.AmpClientFactory instance at 0x7ff5d99ae680>
2015-10-26 13:20:01-0700 [-] Starting factory <evennia.server.amp.AmpClientFactory instance at 0x7ff5d99ae680>
2015-10-26 13:20:01-0700 [Uninitialized] <twisted.internet.tcp.Connector instance at 0x7ff5d98da290> will retry in 3 seconds
2015-10-26 13:20:01-0700 [Uninitialized] Stopping factory <evennia.server.amp.AmpClientFactory instance at 0x7ff5d99ae680>
2015-10-26 13:20:04-0700 [-] Starting factory <evennia.server.amp.AmpClientFactory instance at 0x7ff5d99ae680>
2015-10-26 13:20:04-0700 [Uninitialized] <twisted.internet.tcp.Connector instance at 0x7ff5d98da290> will retry in 4 seconds
2015-10-26 13:20:04-0700 [Uninitialized] Stopping factory <evennia.server.amp.AmpClientFactory instance at 0x7ff5d99ae680>
2015-10-26 13:20:09-0700 [-] Starting factory <evennia.server.amp.AmpClientFactory instance at 0x7ff5d99ae680>
2015-10-26 13:20:09-0700 [Uninitialized] <twisted.internet.tcp.Connector instance at 0x7ff5d98da290> will retry in 6 seconds
2015-10-26 13:20:09-0700 [Uninitialized] Stopping factory <evennia.server.amp.AmpClientFactory instance at 0x7ff5d99ae680>
2015-10-26 13:20:15-0700 [-] Starting factory <evennia.server.amp.AmpClientFactory instance at 0x7ff5d99ae680>
2015-10-26 13:20:15-0700 [Uninitialized] <twisted.internet.tcp.Connector instance at 0x7ff5d98da290> will retry in 11 seconds
2015-10-26 13:20:15-0700 [Uninitialized] Stopping factory <evennia.server.amp.AmpClientFactory instance at 0x7ff5d99ae680>
2015-10-26 13:20:27-0700 [-] Starting factory <evennia.server.amp.AmpClientFactory instance at 0x7ff5d99ae680>
2015-10-26 13:20:27-0700 [Uninitialized] <twisted.internet.tcp.Connector instance at 0x7ff5d98da290> will retry in 11 seconds
2015-10-26 13:20:27-0700 [Uninitialized] Stopping factory <evennia.server.amp.AmpClientFactory instance at 0x7ff5d99ae680>

**Comment by Griatch** [comment]
This is with the latest Evennia version?

**Comment by Griatch** [comment]
Also, is this happening if you do a full evennia stop followed by evennia start, or only when you do evennia restart?

**Comment by Tirit** [comment]
Yes, I've done a pull just to make sure it is the latest Evennia files. It does it on an 'evennia stop' than an 'evennia start'. I did not see it happen on an 'evennia restart'

**Comment by Tirit** [comment]
Evennia 0.5.0 (rev 23bfa1f) (rev 23bfa1f)
    OS: posix
    Python: 2.7.6
    Twisted: 15.2.1
    Django: 1.8
    Evennia MUD/MUX/MU* development system

    Licence: BSD 3-Clause Licence
    Web: http://www.evennia.com
    Irc: #evennia on FreeNode
    Forum: http://www.evennia.com/discussions
    Maintainer (2010-):   Griatch (griatch AT gmail DOT com)
    Maintainer (2006-10): Greg Taylor

    Use -h for command line options.

**Comment by Tirit** [comment]
So, doing some troubleshooting. I did a whole new 'evennia --init' under a different game name. Stopped everything. Pulled all the files from my Repo to the new game. It worked. It runs.

However, once I coped the backup of the evennia.db3 file. It starts to give and error as above.

**Comment by Griatch** [comment]
Would you mind sharing your "failing" .db3 file? You can attach it here I believe.

**Comment by Tirit** [comment]
Won't let me share that file. Doesn't support it. I dropped it into my google drive. 
https://drive.google.com/file/d/0B2GFUEsx6cLaWlRndElQdHZHQlU/view?usp=sharing

**Comment by Russell-Jones** [comment]
Comparing the schema (from `sqlite3 somedb.db3 .sch | sort > somedb.sch`) the only difference I could find was in objects_objectdb. 
On my most recent game instance (from Oct 18th) it's
```
CREATE TABLE "objects_objectdb" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "db_key" varchar(255) NOT NULL, "db_typeclass_path" varchar(255) NULL, "db_date_created" datetime NOT NULL, "db_lock_storage" text NOT NULL, "db_sessid" varchar(32) NULL, "db_cmdset_storage" varchar(255) NULL, "db_destination_id" integer NULL REFERENCES "objects_objectdb" ("id"), "db_home_id" integer NULL REFERENCES "objects_objectdb" ("id"), "db_location_id" integer NULL REFERENCES "objects_objectdb" ("id"), "db_player_id" integer NULL REFERENCES "players_playerdb" ("id"));
```
On the file you provided it's
```
CREATE TABLE "objects_objectdb" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "db_player_id" integer NULL REFERENCES "players_playerdb" ("id"), "db_key" varchar(255) NOT NULL, "db_typeclass_path" varchar(255) NULL, "db_date_created" datetime NOT NULL, "db_lock_storage" text NOT NULL, "db_sessid" varchar(32) NULL, "db_cmdset_storage" varchar(255) NULL, "db_destination_id" integer NULL REFERENCES "objects_objectdb" ("id"), "db_home_id" integer NULL REFERENCES "objects_objectdb" ("id"), "db_location_id" integer NULL REFERENCES "objects_objectdb" ("id"));
```
That is, db_player_id is the last field, not the second in my game instance. I don't know if the difference is significant.

On another track, did you use pip install --upgrade -r requirements.txt ? Pillow is required to have version < 3

**Comment by ahmedcharles** [comment]
What are the contents of your settings.py file? Other than the secret at the end?

The issue is likely that you're using the same class for guests and players. Though it could be something else.

**Comment by Tirit** [comment]
@ahmedcharles Excluding the fact that I've done 'GUEST_ENABLED = True', nothing has changed in regards 

@Russell-Jones Just did a pip install --upgrade -r requirements.txt, thank for reminding me! I'll check to see if it had any affect on the situation.

**Comment by ahmedcharles** [comment]
I currently believe that this is because the database saves character <-> player <-> session mappings, so it handles reload successfully. However, if the server is not cleanly stopped, it will have stale sessions stored. If there is a guest session stored, the server will try to delete it on cold start, but fail, because the database thinks that a session still exists, even though no sessions can exist on a cold start.

Griatch is probably the best person to fix this, since there are lots of implications to any solution. Though, I suspect that cold starts should probably purge session data, because there are no sessions connected and then the deletion of guests will succeed.

**Comment by Tirit** [comment]
Something happened in this latest push that change and now the 'failed' db is working.

**Comment by Griatch** [comment]
@Tirit 

Nothing done intentionally as far as I know, haven't had time to look into this at all until now. Lost permission to view the google drive file it seems, so hoping to get that again.

**Comment by Tirit** [comment]
Yeah, I wasn't wanting to keep the db up there, since even though they're encrypted there are passwords stored. I just disabled the sharing. It should be re-enabled.

**Comment by Griatch** [comment]
@Tirit 

Thanks, got it now. :)

**Comment by Griatch** [comment]
So, I agree with @ahmedcharles; what happened was that the server was killed in such a way that the normal cleanup operations of sessids could not run - the result was lingering sessids not belonging to anyone. This only readily manifested with Guest-accounts activated but who knows what other effects it could have had. I've fixed it by making sure to always take another cleanup sweep of the db_sessid database table when cold-restarting. With this, @tirit's database starts correctly.
