### ISSUE TITLE
OOCLook command problems

### ISSUE THREAD

**Issue by feend78** [evennia/evennia#907]
I've been working with MULTISESSION_MODE=2, and I'm seeing two issues, somewhat related. 

* After creating a new Player, an error is thrown from the player's `at_look` hook.
* As the superuser, when connecting, no characters are displayed in the first call to `at_look`, but are displayed when using the "look" command.

I'm including both of these problems together, because they both seem to be coming from the same spot in the code, when `at_look` is called with target=None.

**Error**
The error thrown when connecting as a non-superuser Player is:
```
Traceback (most recent call last):
  File "c:\users\dan\sandbox\evennia\evennia\commands\cmdhandler.py", line 435, in _run_command
    ret = yield cmd.func()
  File "c:\users\dan\sandbox\evennia\evennia\commands\default\unloggedin.py", line 241, in func
    session.sessionhandler.login(session, player)
  File "c:\users\dan\sandbox\evennia\evennia\server\sessionhandler.py", line 329, in login
    player.at_post_login(session=session)
  File "c:\users\dan\sandbox\evennia\evennia\players\players.py", line 712, in at_post_login
    self.msg(self.at_look(session=session))
  File "c:\users\dan\sandbox\evennia\evennia\players\players.py", line 816, in at_look
    if is_su or len(characters) < charmax:
TypeError: object of type 'NoneType' has no len()
```

**Character List**
Immediately after connecting, the player's `at_look` hook is called with target=None, which results in the "no characters" message appearing.
```
--------------------------------------------------------------------
Account Superuser (you are Out-of-Character)

Connected session:
* 1 websocket (127.0.0.1)

help - more commands
ooc <Text> - talk on public channel

You don't have any characters yet. See help @charcreate for creating one.
--------------------------------------------------------------------
```

But on entering "look" manually, it instead shows:

```
--------------------------------------------------------------------
Account Superuser (you are Out-of-Character)

Connected session:
* 1 websocket (127.0.0.1)

help - more commands
ooc <Text> - talk on public channel
@charcreate <name> [=description] - create new character
@ic <character> - enter the game (@ooc to get back here)

Available character (1/unlimited):
- Superuser [immortals]
--------------------------------------------------------------------
```

**Comment by Griatch** [comment]
This is not intended behavior, no. I won't have time to look at this in a while though, PRs are welcome in the interim.
